### ISSUE TITLE
Dokku should have a command to keep its base system up to date

### ISSUE THREAD

**Issue by egerlach** [dokku/dokku#1089]
Currently, it's a bit of a pain to keep Dokku's base images up to date (so that your apps have all the security updates). I've written [a script](https://gist.github.com/egerlach/97217e644057afe433b2) that I'm using as a way to keep my installation up to date.

It would be cool if there was some sort of `systemupdate` command that did some/all of this.

If progrium/buildstep#146 and progrium/cedarish#19 are resolved, this script will simplify significantly.

**Comment by michaelshobbs** [comment]
:+1: on the concept. @josegonzalez what are your thoughts here given the deb package situation?

**Comment by josegonzalez** [comment]
Installation is now performed - by default - from debian packages. You can simply `apt-get install dokku`  to upgrade. Source-based installations will continue to be a manual process. Closed by #1058.

**Comment by egerlach** [comment]
@josegonzalez I'm not sure that this addresses the reported issue. This isn't about keeping _dokku_ up to date, it's about keeping the stack that underlies the apps up to date (i.e. the Ubuntu debootstrap container image, etc)

**Comment by josegonzalez** [comment]
Gotcha. Part of this is taken care of by the dokku install - plugin-install is re-run every time you upgrade. The deb package for buildstep *should* pull latest ubuntu stuff, so I'm re-opening so we can fix that.

We can probably make this something like `dokku upgrade` which updates all deb packages and plugins? I'd def be okay with a PR for that :D

**Comment by bchr02** [comment]
+1

**Comment by josegonzalez** [comment]
@bchr02 thanks for the +1, do you have a potential pr that will implement such a feature?

**Comment by michaelshobbs** [comment]
What happened to using the deb package method of upgrade?

**Comment by josegonzalez** [comment]
I think he means rebuilding the herokuish container?

**Comment by bchr02** [comment]
@josegonzalez Nope sorry. Dokku is still very new to me. I find the concept intriguing and full of potential. 

Over the weekend I started testing some Node.js apps on Cloud Foundry within IBM BlueMix PaaS infrastructure. I found it really convenient not having to install, configure, **and maintain** anything (OS, NGINX, ) except for my Node.js app themselves. The only problem was I didn't care for the monthly fees :smile: especially because I already have my own servers.

I first learned about Dokku reading a Digital Ocean tutorial... I then started reading the the Dokku [documentation](http://progrium.viewdocs.io/dokku/installation/) but I didn't find anything about how to maintain the whole thing. It's great that Dokku abstracts all the component of setting up and configuring the underlying system which runs/contains the apps that one is looking to deploy but I feel like that promotes a false sense of security. This solution will appease most to those that don't know how to maintain a system especially one that they don't understand. Which is why I feel it is important that Dokku should document how to best keep everything up-to-date and secure and perhaps provide a mechanism for doing so. Things like:

* Ubuntu
* Docker
* [Buildstep](https://github.com/progrium/buildstep)
* [ssh-command](https://github.com/progrium/sshcommand)
* [pluginhook](https://github.com/progrium/pluginhook)
* ssh
* git
* nginx

There are tons of articles online on how easy it is to use Dokku but not one of them mentions how to keep it secure. It's awesome that I'm not alone in this concern. Thanks @egerlach for being first to bring this issue to light because I feel like it's an important one.

**Comment by u2mejc** [comment]
It's my impression that the dokku environment is always rebuildable? Simply having apt-get update && apt-get upgrade will update your docker version, nginx (proxy) and dokku client which would pull down new target image references for docker. @josegonzalez Does the herokish image run apt-get when it's ran? Pushing an empty commit that documents your upgrading the env seems like it would satisfy this need. Also keeps constancy in the project of features supported directly vs indirectly (example, uninstalling is not supported if you don't use apt-get).

**Comment by egerlach** [comment]
@u2mejc You are correct, when herokuish updates, it does update the base image. However, it does not appear that the herokuish package is updated every time the herokuish image is updated (which *is* updated everytime the base image is updated, now).

Plus, it's not any work here that needs to be captured in the image, but any security updates to underlying packages that the image installs when it's built.

**Comment by michaelshobbs** [comment]
So what is this featuring going to look like? 

```
apt-get update
apt-get install dokku
docker pull gliderlabs/herokuish:latest
```

??

**Comment by josegonzalez** [comment]
@egerlach We *definitely* release a new version of the herokuish package every time we release a new herokuish image. Since those images are built "from source", then they have whatever Ubuntu 14.04 deems is the most secure/up to date for it's system.

@bchr02 The doc would go something like:

- install unattended security updates
- call `apt-get update && apt-get upgrade` on a regular basis.

Not sure what else you are looking for. Anything else - configuring firewalls, locking down remote ssh using fail2ban, etc. - is pretty far out there in terms of what dokku aims to do imo.

**Comment by bchr02** [comment]
@josegonzalez thanks for the reply.

Okay, so what you are saying is:
1. Install the unattended-upgrades package: ```sudo apt-get install unattended-upgrades```
2. Set it with: ```sudo dpkg-reconfigure --priority=low unattended-upgrades```

**Or** manually run them by periodically calling ```apt-get update && apt-get upgrade```

And this should keep **everything** (Ubuntu, Dokku, etc.) updated. Is my understanding correct? Thank you.

**Comment by josegonzalez** [comment]
The unattended-upgrades are only for security upgrades, not every package. Hence the other apt-get calls (which will upgrade dokku/herokuish/etc., as we don't make "security" releases).

https://help.ubuntu.com/community/AutomaticSecurityUpdates

**Comment by bchr02** [comment]
@josegonzalez thank you. I understand now. 
by the way, I found an interesting article on automating the apt-get commands here:
http://www.techrepublic.com/article/automatically-update-your-ubuntu-system-with-cron-apt/

It's too bad we couldn't default new installs to automate both these tasks. It seems like it would make things more secure since most people are likely running Dokku headless.

**Comment by egerlach** [comment]
@josegonzalez Both `herokuish` and `heroku/cedar:14` need to be updated on a regular basis if apps running on dokku are to remain secure (though `ubuntu-debootstrap` is exempt because `heroku/cedar:14` runs `apt-get update && apt-get upgrade`). Unfortunately, it appears that `heroku/cedar:14` is *not* updated when there's an Ubuntu Security Notice, rendering it, `herokuish`, and all Dokku-deployed apps potentially insecure as well.

I've written a [blog post](https://eric-gerlach.squarespace.com/blog/2015/10/27/keeping-your-dokku-deployed-apps-secure-take-3) about the issue if you want more detail.

For @bchr02, updating the `herokuish` package in your host OS is insufficient, because there's a container in the chain of containers that doesn't get updated regularly.

**Comment by josegonzalez** [comment]
@egerlach so you're saying a full-rebuild would be good enough?

**Comment by egerlach** [comment]
@josegonzalez You need to rebuild the `heroku/cedar:14` image, and everything on top of it, on a regular basis, so that packages installed at that layer are up to date. Or do an update at the `gliderlabs/herokuish` level, or at the app container level, but that seems a bit insane.

As I'm thinking about the right way to do this, I'm thinking Dokku should maintain a local `herokuish` container derived from the one from Docker Hub that has had `apt-get update && apt-get upgrade` run on it, and then have a detector that examines that container for out-of-date packages with some frequency and then rebuilds that local container and all apps whenever an out-of-date package is detected.

The other option is to have some sort of process that is centrally run that looks for those out of date packages and builds a new global herokuish package whenever there's an update, and the local machines look for that update and rebuild when they find one.

**Comment by vincentfretin** [comment]
Maybe a bit off topic, but I wanted to share this.
https://github.com/mafr/docker-update-check is a nice script to have a reporting of security updates of ubuntu containers. Maybe you have non Dokku containers on your host and you need to see if there is security updates to do.
I have a cron that executes the following script:

```bash
cd /home/vincentfretin/docker-update-check                                      
./update-check run                                                              
./update-check update                                                           
for container in `docker ps -q`; do                                             
    ./update-check check $container;                                            
    docker inspect --format '{{.Name}}' $container                              
done
```
that produces the following output:
```
--- caa59d090ffa ---
0 packages can be updated.
0 updates are security updates.
/myapp.dokku.me
--- 43f8a14035fd ---
13 packages can be updated.
5 updates are security updates.
/elk_kibana_1
```

**Comment by josegonzalez** [comment]
@egerlach If we copied the script in your blog post, what would we call the command? Ideally we have a `Security` page in the dokku docs and push people towards updating their stuff.

@vincentfretin how does that script compare with what's in @egerlach's [post](https://eric-gerlach.squarespace.com/blog/2015/10/27/keeping-your-dokku-deployed-apps-secure-take-3)?

**Comment by vincentfretin** [comment]
@josegonzalez the script doesn't update anything, it just show you if there are updates.

**Comment by ElRoberto538** [comment]
Hi all, any update on this? So far I am using the info from the blog post by @egerlach, and checking the package versions using docker-update-check linked by @vincentfretin. However it is a very overkill way to maintain things...

**Comment by josegonzalez** [comment]
@ElRoberto538 would you be willing to contribute a patch for this functionality?

**Comment by ElRoberto538** [comment]
@josegonzalez I'm not sure the solution I'm using is particularly ideal - it kind of hammers the server during the rebuild. I could look into making a patch for this, it won't be anytime soon though as I don't have the time available for a while.

**Comment by josegonzalez** [comment]
> it won't be anytime soon though as I don't have the time available for a while.

You and me both ;)

**Comment by josegonzalez** [comment]
Okay so tasks here:

- [ ] Ensure we build against an updated base os when releasing herokuish
- [ ] Setup monthly releases of herokuish
- [ ] Write docs on updating dokku dependencies
  - Link to upstream-related update documentation versus our own for updating stuff like docker or ubuntu...
- [ ] Have a command that will output all the commands that need to run in order for a user to update their system. Potentially have this as an extra binary/package users can run that doesn't depend upon any of the dokku stuff.

**Comment by josegonzalez** [comment]
Please see the main comment in #3039 for more information as to why I think this can be marked as closed. Thanks everyone for your input, and hopefully this first pass brings us closer to the path everyone is seeking :)
