### ISSUE TITLE
dokku command – app:rename old_name new_name

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku#1440]
It would be nice to be able to rename apps easily.

**Comment by josegonzalez** [comment]
Note: this seems to be implemented in heroku as follows:

```shell
heroku apps:rename newname
```

We could have a similar interface:

```shell
dokku apps:rename <app> newname
```

I *think* we could basically do something like:

```shell
pluginhook pre-rename-app
mkdir -p /home/dokku/newname
cp -a /home/dokku/app/. /home/dokku/newname/
dokku apps:destroy app
dokku ps:rebuild newname
pluginhook post-rename-app
```

We'd do the destroy first to clear out any old nginx configurations (if someone uses the domains plugin, this would otherwise interact weirdly.

One thing this won't handle is plugins that link themselves to the old app. I think thats okay, since doing anything else would require lots of coordination.

Note: You'll also want to add the relevant hooks in the events plugin so ^ gets logged.

@matthewmueller want to make a pr to the `apps` plugin in core with this feature as outlined above?

**Comment by zachfeldman** [comment]
+1 for this!

**Comment by josegonzalez** [comment]
@zachfeldman Note: +1s on enhancement requests don't really do much to move the needle much, only on bugs. If you'd like to contribute the feature or at least go through a rough-draft for us, that would be great :)

**Comment by zachfeldman** [comment]
I'm working on a pull request for this right now.
