### ISSUE TITLE
backup:import is broken

### ISSUE THREAD

**Issue by dustMason** [dokku/dokku#1627]
I just tried to use dokku's backup:export and backup:import commands to carry an app config through a server teardown and was unable to import the tarball created by the initial backup:export command.

To export, I did `dokku backup:export filename`. I then booted a fresh server and installed dokku and scp'd up the tarball. When I ran `dokku backup:import filename`, I first got

`/var/lib/dokku/plugins/enabled/backup/commands: line 53: dokku_log_fail: command not found`

Using the -f flag resulted in the same output. I had a look at the source and decided to check out the contents of the tarball. I noticed that the `.dokku_backup_apps` file list included non-app directories like `.ssh` and `.basher`. I removed those and made a new tarball, which I was able to import.

Did I use this feature incorrectly? It seems like those hidden directories weren't supposed to be in the `.dokku_backup_apps` list.

**Comment by michaelshobbs** [comment]
Unfortunately, this feature has been neglected over the past few months and I don't think all plugins are supporting it either. I know from conversations with @josegonzalez, this will be part of our development focus in the short term. 

In the meantime, a full backup of `/home/dokku` and `/var/lib/dokku` should accomplish the same thing.

**Comment by dustMason** [comment]
Good to know, thanks for the reply. In the meantime hopefully this issue will help future backer-uppers.

**Comment by Seralto** [comment]
I'm having problems with backup:import too, where I can generate the file and restore it, but it only creates empty folders.

**Comment by josegonzalez** [comment]
Yeah, the backup feature is hella broken. There is an issue open to consolidate how we do configuration in dokku (probably for 0.5.0) which will make backups a bit more trivial. At the moment, the only method we have is tarring the two directories - as @michaelshobbs mentioned - though you'll want to stop any official services you have in the /var/lib/dokku/services directory first (or pause all writes while backing it up).

**Comment by Seralto** [comment]
Thanks for the reply josegonzalez.

**Comment by u2mejc** [comment]
I was going to take a crack at this bug, but I got to thinking, is this a feature we want to keep? Considering that any app is rebuildable from source? Correct me if I'm wrong, but heroku only supports pg:backup for the postgres databases. Is anyone storing session data on the docker file system? If someone mounted a volume, I would say they could just rsync that to a new instance or be keeping snapshots for disaster recovery.

Documentation may be more maintainable for migrating to a new server:
```
$ git remote rm dokku
$ git remote add dokku dokku@[dokku.me:dokku.me]
$ git push dokku [master]
```
Disaster recovery (local git repo and backups erased):
```
mkdir [app-name] ; cd !$
git init && git remote add dokku dokku@[dokku.me:app-name]
git pull dokku/master && git checkout dokku/master
```
I tried to find a plugin using the backup hooks (like backup-export) but I guess they are not widely used as I couldn't find any using them? I could see a use case for some plugins that lack an export function, but that sounds more like a plugin issue then upstream.

@dustMason @Seralto Since you both had trouble with this feature, can you give your 2¢ here? Would you have a use case where you wouldn't be able to rebuild your apps from just pushing source?

I've done a first pass at a PR for this and adding documentation for backup and recovery. Let me know what you think.

**Comment by dustMason** [comment]
@u2mejc my use case was wanting to bundle up all of the app config for migration to another server, including the app metadata that dokku stores on the host for each app including files like: `DOCKERFILE_ENV_FILE, DOCKER_OPTIONS_DEPLOY, DOKKU_SCALE  HEAD, nginx.conf, DOCKER_OPTIONS_BUILD  DOCKER_OPTIONS_RUN, ENV`. For the case of `ENV` those are mostly secrets that I would not check into a code repo.

**Comment by u2mejc** [comment]
Thank you @dustMason for replying! :+1: Good point, secrets shouldn't be committed in remote code repos. The other env vars you mentioned I believe are codifiable today? I could see trade secrets of how many instances you run, but otherwise nothing really compromisable about committing a Dockerfile and DOKKU_SCALE file in a private repo?

To migrate env vars, today, you can use `dokku config [ <app> | --global ]` to get all of the env exports. Prepending `dokku config:set` to each line (I use vim visual mode) and pasting into the remote server console would quickly rebuild that env. But that's kinda a pain. What if I proposed a new community plugin to export dokku env as say json, similar to aws's cli. This would allow you to keep a local, private / not published, git repo of env vars for your apps and allow codification with save and update functions for updating your dokku app. This would grant a safe place for secrets to be kept locally on an encrypted volume. A later version of this plugin could be extensible to include other plugins too, but I would focus on dokku's config first. Thoughts?

@josegonzalez Can you think of other examples that may be hard to anticipate today with the backup command? Obviously if we keep it, we should create a test for it too.

**Comment by josegonzalez** [comment]
As I stated before, I'd like to consolidate the dokku-specific config - including all these files - into a directory structure we can simply tar up. The new services *mostly* follow this, though they still mix data volumes with everything else.

**Comment by dustMason** [comment]
Yes committing items like the docker config flags would be fine with me and
I think it would be sensible for dokku to look for those files at the repo
root as it already does with nginx config. In fact I don't know if this is
already the behavior. Is it?

The main question, of course, is about ENV. The idea of a json format
sounds cool but since ENV is, by nature, a flat key value structure I think
the existing format works pretty well. I feel like this is really coming
down to adding a small feature to the dokku config command that accepts a
piped in ENV file. To make a backup I can use the output of docker config
like you said. That, plus being able to include the docker flags in my repo
would address my needs.

**Comment by u2mejc** [comment]
>As I stated before

Context reference I believe: https://github.com/progrium/dokku/issues/1558

@josegonzalez Totally understand and I agree, standardizing the dirs will be very beneficial to make things more predictable. But do you think the sole motivation behind that RFC is for backups or do you think they can be evaluated individually? Say if we put aside the work required to unify the dirs, and the backup plugin was still broken, does Dokku still need a tar wrapper? Is that a horse you'd still want to back? I don't have a strong feeling either way, but I have a suspicion that it's destined for the chopping block similar to the discussions about advanced features in the nginx rfc: #1629

@dustMason ah I think you will be presently surprised, all of those advanced and dangerous (read user support issue creating) docker-options are just clicks away! http://progrium.viewdocs.io/dokku/docker-options/#advanced-usage-avoid-if-possible

**Comment by dustMason** [comment]
Thanks @u2mejc. I hadn't made the realization that I already can simply commit those files to my app repo, which solves almost all of my original problem.

So aside from `ENV`, are there any config backup needs that can't/shouldn't be addressed by simply committing the relevant files to the app repo? Or that orthogonal to your discussion about unifying the dirs. The way I'm seeing it at the moment is that a nicely tar-able dir structure might not be needed since the only remaining use case for the backup feature that I can see is `ENV`. Forgive me ignorance if I'm missing something from the greater picture here

**Comment by Seralto** [comment]
Hi @u2mejc, my concern about the backup was about all dokku configuration on the server, not for the application itself  (as you mention it can be restored from source).

**Comment by u2mejc** [comment]
Hi @Seralto, I've come full circle on this issue. There are examples outside my use case that could leave remnants on the server if not committed to your app's git repo. Presently this issue is blocked by #1558.

**Comment by jvanbaarsen** [comment]
Since the backup plugin is in the process of being removed, maybe we can close this issue. see https://github.com/dokku/dokku/pull/1687 for more info /cc @josegonzalez
