### ISSUE TITLE
nginx-vhosts expected behaviors

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#1629]
Over the length of time I've been using and contributing to dokku, the nginx functionality and  implementation complexity of said functionality has increased significantly. It doesn't seem (to me at least) that we have documented fully what the plugin is meant to do, what cases are automated, and what cases are left to the reader to implement with a custom template.

My personal position on this (and with software development in general, I think) is we should do a handful of things very very well and document the edge cases to give users the ability to implement them in their own way. (read: batteries included but replaceable)

This issue is an attempt to document and clarify what this plugin does and subsequently clean up the implementation to this end. I will enumerate my current understanding of this and willfully open the conversation to the community in hopes to solidify the expectation of functionality, and subsequently help prevent the historic regression cycle we've seen in this plugin.

### baseline assumptions
* nginx listener on port 80 
  * no-ssl
  * Loadbalancer (LB) with SSL termination. *not sure how this differs from no-ssl given our current templates*
* nginx listener on port 443 (ssl hosted on box with 301 redirection from port 80)
* some list of domains (`server_name` args) for which to answer
* custom nginx template may override any of the aforementioned scenarios using documented template variables
* dokku will validate (`nginx -t`) all nginx config before successfully deploying an app if VHOST support is enabled for said app

### VHOST/domain support
* local ssl configurations (i.e. non-ssl-terminated LBs) require nginx but **not** a domain (i.e. self-signed certs for development or internal services perhaps)
* non-ssl configurations **do not** require a domain or nginx
* `VHOST` support is on by default but can be disabled both explicitly or implicitly
  * (explicit) `NO_VHOST` env variable
    * nginx listens on random high port
    * container listens on external interface
  * (implicit) if either `$DOKKU_ROOT/VHOST` or `$DOKKU_ROOT/HOSTNAME` contain IPv4/IPv6 addresses, `NO_VHOST` is set for the deployed app
* nginx can be disabled completely
  * removes the app-specific nginx config and restart a container that listens on a random high port on the external interface of the host
* app-specific domains/VHOST support (`$DOKKU_ROOT/VHOST`) works even without a global VHOST (`$DOKKU_ROOT/VHOST`)
* all domains added with the domains plugin can be used to access the app
* default domain is `<appname>.$(cat $DOKKU_ROOT/HOSTNAME)`, if...
  * `$DOKKU_ROOT/$APP/VHOST` doesn't exist
  * `$DOKKU_ROOT/VHOST` and `$DOKKU_ROOT/HOSTNAME` do not contain IPv4 or IPv6 addresses
  * `$DOKKU_ROOT/VHOST` exists 
  * `nginx-hostname` plugin trigger returns nothing

### ssl specifics
* server-wide **AND** app-specific SSL certificates are supported
  * app-specifc certs take precedence over server-wide certs
* SSL certs with SANs are supported
* nginx will proxy the same app on all SSL domains (as found in the defined cert) **and** any additional non-SSL domains added with the domains plugin (without redirection)

I may have missed some cases but I think this illustrates how insane we've allowed our nginx support to become and I hope we can come to consensus on a more restrained scope of functionality or a more rational implementation. Now go ahead, talk amongst ya'selves.

refs: #1625 #1581 #1597 #1575 #674
those are just the open issues regarding nginx config.

**Comment by u2mejc** [comment]
So if I understand correctly, you want to talk about how much we should be supporting, and pair down the feature set while updating the documentation to include all of the known environment vars?

**Comment by michaelshobbs** [comment]
Goals 
- document automated use cases
  - including template variables
- sift through the aforementioned feature set and decide what we want automated and what we want to leave to custom templates
  - include documenting common custom templates

**Comment by josegonzalez** [comment]
@michaelshobbs what things do you hate about what we currently support? If you had a feature list, what would that be?

**Comment by michaelshobbs** [comment]
I dislike automatic configuration of anything but the simplest scenarios. My feature set would look something like
* automatically supported configurations
  * non-ssl nginx on standard port with domain list (container listens on internal interface)
  * ssl nginx on standard port with domain list (container listens on internal interface)
  * nginx can be disabled completely with `$NO_NGINX` or with an IP address in `$DOKKU_ROOT/HOSTNAME` (or `$DOKKU_ROOT/VHOST` perhaps)
  * default domain is `$APP` + contents of `$DOKKU_ROOT/VHOST` or `$DOKKU_ROOT/HOSTNAME` (in that order of priority)
  * domains plugin is still supported as is
  * config validation is performed before nginx is reloaded
  * logs (not mentioned above)
    * `/var/log/nginx/${APP}-access.log`
    * `/var/log/nginx/${APP}-error.log`

clarification on other features
* no ssl cert inspection
  * if an app contains a domain that does not exist in the provided cert then you get a browser warning
  * we always redirect to SSL when we have a cert (can be overridden with a template)
* everything else is done with a custom template and documented template variables
  * `$APP`
  * `$NGINX_PORT`
  * `$NOSSL_SERVER_NAME` (could be an array)
  * `$NGINX_SSL_PORT`
  * `$SSL_SERVER_NAME` (could be an array)

I think the biggest thing is around SSL support. dokku will use an SSL listener if you drop your cert in but it's up to the user to do anything fancier outside of what we do for non-ssl stuff.

**Comment by callahad** [comment]
:+1: for paring down and limiting automatic configuration.

I'd also request: "Works with distro-provided nginx." Right now, the nginx-vhosts/dependencies file tries to add a PPA and install nginx from it, which seems a bit extreme. I want the host system to be as bland and stable as possible. Newer software is easy enough to run inside my deployed containers. :)

As it stands, that would mean supporting: nginx 1.4.6 on Ubuntu 14.04 and 1.6.2 on Debian 8. From reading the changelogs, I don't think we depend on anything introduced in 1.6 or later, and there are no open CVEs in the distro-provided packages.

**Comment by michaelshobbs** [comment]
@callahad the (current) primary install base is definitely Ubuntu and thus, we would need to be comfortable with nginx 1.4.6. IIRC, the move to PPA installation was to jump to 1.6.x from 1.4.x.

**Comment by callahad** [comment]
Are we actually depending on anything in 1.6, though? The PPA line was added [back in 2013](https://github.com/progrium/dokku/commit/de906a22aaf651d0cd78812ef823601e10403f00) with the intention of upgrading to 1.4 for websocket support. Now that 1.4 is in 14.04 LTS's repos, maybe we don't need the PPA?

**Comment by mmerickel** [comment]
The PPA is 1.8. LTS is pretty out of date.

**Comment by michaelshobbs** [comment]
I think we don't have enough information to determine the impacts of downgrading nginx due to the ability to customize with a config template. 

We've already been shipping with a PPA (as was noted) since 2013. What do we as a project gain by removing this?

**Comment by callahad** [comment]
@michaelshobbs Stability in Dokku's foundation, the removal of an external dependency, and greater harmony with the host environment, since Dokku wouldn't need to run roughshod over /etc/apt/sources.list.d/.

I'm not suggesting downgrading, just setting the Depends field in the package control file to `nginx >= 1.4.6` and ensuring that all standard Dokku functionality works with that version of Nginx. Users who need features only available in newer versions of nginx for their custom templates could freely upgrade nginx from the PPA or backports repo. We just wouldn't mandate it for a standard Dokku installation.

**Comment by callahad** [comment]
The broader principle I'm advocating for is explicitly defining Dokku's minimum requirements and attempting to be as minimally invasive as possible. We'd gain more confidence in the underlying system, have fewer moving targets to debug, and would get to piggyback on the existing machinery that keeps LTS releases stable and secure. Maybe this discussion should go to a different RFC?

**Comment by josegonzalez** [comment]
Removing the PPA works for me. The big thing here is just ensuring users have a secure by default setup. If we can depend upon the LTS version for that, awesome.

**Comment by mmerickel** [comment]
Considering the oddities recently addressed with logrotate and permissions, we might be opening up more bugs if we support multiple nginx distributions. For example making sure those new search/replace scripts work with 2 distributions instead of 1. That can also be an issue for a user who wants a newer version of nginx because dokku is currently doing things to those files that may not be appropriate for all distributions.

So far I think most of the changes were done on plugin:install versus at deploy-time or anything of that sort, so if you drop the ppa and everything that touches those files then it'd be upt o a user to fix it when they install their ppa which is fine of course. Since we force a particular nginx right now though, certain parts of dokku can be a bit more predictable.

**Comment by michaelshobbs** [comment]
Stability can mean a few things here. The assumption I'm reading seems to imply that removing a change made 2+ years ago will move that needle somehow. IMO, this has worked fine for that long and seems to more likely open us up to varying issues due to folks expecting 1.8 (now) and/or due to some installations using 1.4.x, others using 1.6.x and still others on a PPA. I think it's important to weigh other possible impacts as well as the intended ones.

**Comment by callahad** [comment]
> we might be opening up more bugs if we support multiple nginx distributions

That's effectively where we are right now, though. As soon as nginx 1.10 is released, the PPA will update, and all of a sudden new users are on a new, untested-by-us version of nginx. We wouldn't see that sort of churn if we stuck with the LTS packages from the distro.

As an individual self-hosting a dokku instance, the most important thing to me is that I can set the system up, turn on automatic security updates, and trust that things won't break in the middle of the night. And that's the explicit contract that LTS releases provide: the feature set of packages is frozen, but vulnerabilities still get patched.

By tracking the latest release of nginx, we're building atop a foundation where the underlying capabilities are in much greater flux. That means my server is more likely to break in the middle of the night, and ain't nobody got time for that. :)

**Comment by michaelshobbs** [comment]
I feel it must be said, especially in the flame scarred landscape that is the Internet, that I greatly appreciate an individual's desire and commitment to clearly convey their point of view.

With that out of the way, :smile:, I'm fine with removing the PPA requirement but couldn't we also gain stability here by pinning to 1.8?

**Comment by callahad** [comment]
:beers:

> couldn't we also gain stability here by pinning to 1.8?

Yep! But I do think 1.4 makes sense given it's what's in 14.04 LTS, so pinning to 1.8 would still require folks to use the PPA, and the PPA doesn't make the same guarantees as the LTS repos. E.g., LTS will backport a security fix from 1.10 to 1.4 if it has to. The PPA will just tell you to upgrade to 1.10. ;)

**Comment by michaelshobbs** [comment]
Fair point. I'm still a bit concerned with downgrading our default and the potential ripple effect but I suppose we can see what happens there. 

@josegonzalez as the keeper of all things .deb (:wink:) you want to put this bit in a PR?

ok now @callahad no more thread jacking :wink: and back on topic. anybody else have thoughts on this plugin?

**Comment by mmerickel** [comment]
> That's effectively where we are right now, though. As soon as nginx 1.10 is released, the PPA will update, and all of a sudden new users are on a new, untested-by-us version of nginx. We wouldn't see that sort of churn if we stuck with the LTS packages from the distro.

Yes, but the distribution I'm talking about is the actual packager... So you wouldn't expect certain files that dokku is tweaking/stomping to change from version to version of nginx from the same packager (ppa) normally.

**Comment by callahad** [comment]
I've copied the entire LTS-vs-PPA discussion over to #1654. @michaelshobbs, please delete the threadjacking comments here :)

**Comment by michaelshobbs** [comment]
You are a gentleman and a scholar :smile:

**Comment by mmerickel** [comment]
A big issue right now is that it isn't clear which options affect which parts of the config. Can I use option A with option B? etc.

re #1597 I think one issue in dokku right now is "which vhosts are ssl terminated?". Currently you can setup ssl certificates on domains but you cannot specify which ones are expected to be ssl terminated. As the linked issue shows it's completely possible to be behind a proxy that is re-encrypting the traffic into a new internal ssl request. This means "port", "proxy_params", and "listen 80" vs "listen 443 ssl" cannot be dictated simply by `DOKKU_SSL_TERMINATED=0/1` and the presence/absence of an ssl cert. It'd be helpful if that were disambiguated in such a way that you could specify `DOKKU_SSL_TERMINATED=fqdn1,fqdn2` to handle the `proxy_params` while leaving port/listen directives up to a separate mechanism (presence/absence of an ssl certificate for starters).

This would mean removing the explicit ssl_terminated nginx template and making the proxy_params in the ssl/no-ssl templates an input parameter.

**Comment by josegonzalez** [comment]
No need to delete. I'll take care of the pr in a bit.

Re: nginx, what features do you want to drop, @michaelshobbs ? Anything we have documented that would not be available to users going forward?

**Comment by landaire** [comment]
Let's Encrypt does not allow wildcard certs, so it'd be great if we could add certs **per domain** instead of **per application**.

With Let's Encrypt I have to explicitly request certs for www.mysite.com and mysite.com. Currently in dokku you cannot use multiple certs per app, but I think it'd make more sense if certs were added per-host instead of per-app since certs are tied to the host anyways. That way I could run `dokku certs:add www.mysite.com < www-certs` and `dokku certs:add mysite.com < certs`, and the config would be auto-updated for each of those hosts. This might cause some complications with wildcard certs but I guess that's an edge case.

**Comment by josegonzalez** [comment]
What about:

```shell
dokku certs:add APP domain < certs
```

?

**Comment by landaire** [comment]
That would work just as well.

**Comment by michaelshobbs** [comment]
to clarify, are we saying we will only configure an SSL endpoint if a user explicitly maps it to a domain?

**Comment by josegonzalez** [comment]
My one thought there is that it would very clearly break wildcards, so if you have your default app to be something that should handle all domains and then your ssl is tied to one, you are foosed.

**Comment by michaelshobbs** [comment]
You would need to either you would still need to add all of your domains with the current functionality, no?

**Comment by josegonzalez** [comment]
Not if you add `*.domain.com` as a domain?

**Comment by michaelshobbs** [comment]
Ah! I've never done that but it does indeed work.

**Comment by u2mejc** [comment]
I think we've ventured into the weeds a little here on one small specific part of this plugin, think we can bring this topic back on track? :wink:

**Comment by wzrdtales** [comment]
As asked in #1821 changing the way how upstream blocks get created. In the current implementation https://github.com/dokku/dokku/blob/a2ccbcbbfbdd41b03fb623c1434f262f5bb030c7/plugins/nginx-vhosts/functions#L228-L236 it does not allow to further change settings for this block.

# Use case

One may wants that as soon as there comes a need for sticky sessions, which comes very quickly as soon as websockets/socket.io are used.

**Comment by Derimagia** [comment]
I think we should think about using a true TCP load balancer / proxy instead of nginx.

Dokku right now is heavily focused towards (as @josegonzalez mentioned it) making web deployment awesome. It does this job really well but it can do a lot more. Running a Mumble or IRC server doesn't work easily on Dokku because of nginx.

If you take a look at #1816 you can see me learning this, and the solution I see is to use something like haproxy instead.  https://github.com/256dpi/dokku-haproxy is an example of fixing this. 

If we don't do this we should at least make it clear that dokku is focused towards web applications, because that isn't very clear right now.

**Comment by u2mejc** [comment]
@wzrdtales Any reason why a custom nginx template doesn't work in your use case?

@Derimagia Nginx is mainly used not just for vhost routing (which is only relevant for http) but also for zero downtime deployments due to port binding on the docker containers. You can easily disable nginx for an app with dokku nginx:disable <app>, but you also *supposedly* do this with a custom nginx template if you upgrade to a nginx version to one that supports streams. I'm not sure when that version of nginx will make it onto ubuntu's stable PPA, but I believe it's not a focus for this project.

**Comment by wzrdtales** [comment]
@u2mejc Simply because of this being static https://github.com/dokku/dokku/blob/a2ccbcbbfbdd41b03fb623c1434f262f5bb030c7/plugins/nginx-vhosts/functions#L228-L236

**Comment by josegonzalez** [comment]
One thing we could do is add separate upstreams per exposed port. The default nginx conf would simply proxy to 5000 if it exists, or the first one otherwise. Then users could do as they please with all other ports (assuming they know what the internal port is).

Regarding applications that use buildpacks but still expose multiple ports, we *could* add that metadata to the `app.json` somehow... But otherwise I think it's a fair compromise to say "buildpacks get 1 port, if you want more, use a dockerfile". Better we stick as close as possible to heroku for buildpacks and innovate elsewhere imo.

One thing @progrium hinted at was using nginx as an appliance; we would simply hit nginx with the requisite data in a json payload and it would reconfigure on the fly. Doing so would get rid of our ability to use custom nginx templates, so I think if we did that, we should drop custom templates all the way?

I do think we should focus on web applications, but not to the extent that we say "fuck apps that happen to not speak https". For instance, I want to deploy an IRC bouncer to dokku, and I don't think there is currently an easy way to do this.

Really what I want is for us to have both nginx and haproxy built into the core. Users can use one or the other for each application, each with varying strengths/weaknesses. That might be asking for a lot though.

**Comment by wzrdtales** [comment]
I don't think we want separate upstreams, but be able to define the upstream part that is not the ip:port definition.

**Comment by okcoker** [comment]
> I don't think we want separate upstreams, but be able to define the upstream part that is not the ip:port definition.

Speaking of, is there currently a way to dictate what port gets put onto the corresponding IP within an upstream block? Or will it always be 80?

**Comment by josegonzalez** [comment]
@okcoker Its always 5000 I think, unless we detect a different port (that should be documented somewhere), which happens for dockerfile deploys.

**Comment by michaelshobbs** [comment]
The dockerfile port config is documented here http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports

**Comment by okcoker** [comment]
> @okcoker Its always 5000 I think, unless we detect a different port (that should be documented somewhere), which happens for dockerfile deploys.

@josegonzalez Not the container expose port, but the port that gets spit out into the final app nginx.conf upstream block. @wzrdtales mentioned the lines [here](https://github.com/dokku/dokku/blob/a2ccbcbbfbdd41b03fb623c1434f262f5bb030c7/plugins/nginx-vhosts/functions#L228-L236) a bit earlier. I'd like to be able to control the port that gets added there.

If this is not the right place for this, I can make an issue. Lmk.

**Comment by josegonzalez** [comment]
Yeah, for buildpacks that will be `5000`. For dockerfile deploys, that can be controlled by the link @michaelshobbs mentioned.

**Comment by josegonzalez** [comment]
Notes for my later review. They absolutely do not reflect what our proxy setup will look like in the future.

---

Here are things I want to support:

- custom templates
- a single file for custom templates (no guessing about which dokku will use depending upon ssl/non-ssl)
- multiple proxied ports, defaulting to the 5000/80 port
- setting a canonical domain name, and defaulting to redirecting to it (anything else == custom template)
- disabling vhosts in ​*just*​ one way. anything that happens to otherwise disable (such as failing to have a global VHOSTS or HOSTNAME file) will result in a deploy error
- dropping DOKKU_SSL_TERMINATED? Maybe that can just be a custom template for users
- moving custom templates to be either the core global, a custom global, or one from within the container, and nothing else.

**Comment by josegonzalez** [comment]
So I've been thinking about this, and basically here is the feature-set I'd like to support:

- Lets get rid of as many "global" configuration keys as possible. Deprecation is fine with me.
- The ability to completely turn off any sort of load balancing for an application. This is application-level, not global.
- Add the ability to completely disable zero-downtime restarts for a given application. As in kill old containers before launching new ones. Lets people bullshit around with UDP ports.
- We always reserve N ports for an application, where N is the number of exposed ports.
- If proxy is enabled and there are no attached domains, we proxy the exposed port to the externally reserved ports. This can be configured and is a comma-separated list of ports. We should be able to query this information.
- Both buildpack and dockerfile applications will support multiple ports. 5000 will default to port 80, and otherwise we will simply map a specific port to the app.
- On initial deploy, we add the "global" vhost as one of the application domains (using the app name as a prefix) if it is available and proxy isnt disabled.
- Add a way to manage the global vhost. If it is ever set/unset/changed, warn the user that this will not affect running applications.
- Custom templating. 
  - Maybe consider dropping them, or at least warning against heavy use of customizing this feature.
  - Only support 1 template name, `nginx.conf.template`. User can set an environment variable for the location of the nginx.conf.template within the container. Fail a deploy if that file does not exist.
  - If the template is copied from within the container into the app dir, we remove it after we use it. This will allow users to revert back to defaults.
  - Always state where the template is coming from (dokku/container/app dir).
  - Deprecate setting proxy conf in app dir. If a user wants to configure it, it seems to me like it's an application level dependency, and thus should be shipped with it.
  - The variables for this template should be a restricted set that includes:
    - a list of internal ports
    - the service name
  - If the proxy requires upstreams, those upstreams should be configurable somehow. This might mean we use a higher-level language for templates (golang?), which will make it easier for users to write nicer templates.

What about ssl?

- Do we need to verify that the cert for a given application is valid for all configured domains?
- Do we fail if the cert isn't valid for a new domain being added to an application?
- We should not drop the existing plugin, I think that's been a boon.

Open question:

- How do we want to handle UDP? The only way to support it would be to disable zero-downtime restarts for that application (something I mention above)

---

You'll note that I am trying to de-emphasize nginx here. What I would like to see is a very generic, well-defined interface to load balancing, documentation around how everything should work, and then a sample implementation with a completely different load balancer, such as haproxy. Note that this *would not* support something like udp, but would at least point users towards potential custom solutions (vulcand, using ELBs, etc.). The less our nginx plugin does, the better.

**Comment by michaelshobbs** [comment]
I like this. Very clear and concise feature set. Regarding SSL, I think we apply the least amount application magic here and say we'll configure nginx with whatever SSL cert/key you define for a given app.

**Comment by u2mejc** [comment]
I think we should still should verify if a cert if valid, but per application only. Very few people [know how to] use SANs today and it's one less global var if it's per app.

I don't have too many strong feeling for this RFC and generally support the rest. My only sticking point, that I don't _think_ is being considered, is I don't want us to create a new DSL, nor templating system, to support. While we may decide to change the name, it really should be nginx.conf.include and we simply include it. (Naming also could also affect the chosen proxy, ie haproxy.conf.include). Testing if the container is accessible after including any template is still necessary, but is pretty straightforward with a pass or fail.

I hope I read that right, is that inline with what you guys were thinking?

**Comment by michaelshobbs** [comment]
Regarding SSL, I don't think we should encapsulate that complexity in this project. Worse case, if someone adds an SSL cert to an app with the wrong CN or SANs list, the browser will throw a warning.

@josegonzalez are we still supporting server-wide SSL certs here?

**Comment by josegonzalez** [comment]
I *really* want to move away from using bash templates. They are icky to use and has caused bugs for our users.

Yes? That seems to be a popular use-case. Would it save a lot of complexity to drop?

**Comment by michaelshobbs** [comment]
No but wanted to clarify

**Comment by progrium** [comment]
[Sigil](https://github.com/gliderlabs/sigil) is great for templating btw. Also, love this approach and plan so far. Great work @josegonzalez

**Comment by josegonzalez** [comment]
Oh that could actually work really well (we'd just want a simple deb package, though I can do that @michaelshobbs ). Good show @progrium, def keeps our deps down and simplifies things I think :)
