### ISSUE TITLE
Release error – Cannot start container: a container has already joined the endpoint

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku#1640]
Not sure why this is happening, but have you seen this error before? 

```
Default types for  -> web
-----> Releasing app (dokku/app:latest)...
remote: Error response from daemon: Cannot start container 6cef21d22bffef108752681cb5a3fb1da3b45083e63dcbbe6f5ed666399e4751: a container has already joined the endpoint
To dokku@finbox.io:app
```

It happens irregularly as we're trying to releasing the app.

**Comment by matthewmueller** [comment]
Looks like it might be a docker error: https://github.com/docker/docker/issues/14107

Are we responsible for upgrading docker ourselves? Or is that something dokku handles?

**Comment by josegonzalez** [comment]
You are responsible for upgrading that. Dokku necessarily does not pin to a version (unless there is breakage, like with 1.7.x) because doing so is contrary to what many users expect. If there is a bug in a specific release and we pin to that release (or greater) then a user is hosed if they want to use a package.

We should definitely have better "upgrading" documentation to cover this.

Did upgrading fix your issue?

**Comment by josegonzalez** [comment]
@matthewmueller *bump*

Note: we are getting to the point where providing a `dokku system-upgrade` command would be useful.

**Comment by matthewmueller** [comment]
@josegonzalez awesome. i *believe* so, but to be honest i don't remember.
