### ISSUE TITLE
Install is broken for Debian

### ISSUE THREAD

**Issue by antoine-lizee** [dokku/dokku#1783]
I get a 'bad Gateway' when trying to get to the web-admin after a fresh install depicted in /docs/getting-started/install/debian.md ([here](http://dokku.viewdocs.io/dokku/getting-started/install/debian/) online) on a system with debian (stable) Jessie.

I tracked down the bug to be sinatra not loading because `apt-get` pre-installs `rubygem-sinatra` from the ppa we just added (https://packagecloud.io/dokku/dokku/ubuntu/ trusty main). This package installs the gem for an incorrect version of ruby (1.9 instead of the default 2.1 on Debian Jessie).

3 remarks:

1. Am I right to try to install Dokku following these instructions on debian? If these are Ubuntu specific, it needs to be mentionned... If it's supposed to be debian compatible, then we gotta fix it :-)
1. Was there a proper way to debug that? I tracked down the bug by actually restarting myself the dokku-installer init script (that failed with sinatra not found).
1. For those who got the same problem, installing the correct packages and restart the init script did the trick:
```
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra ruby-tilt
sudo sh /etc/init/dokku-installer.conf &
```

**Comment by u2mejc** [comment]
Hi @antoine-lizee,

I was able to reproduce your issue in an EC2 instance. You might be right, reading quickly you would probably just noticed a list of steps, but the doc actually describes those as a way to automate the install instead of using the bootstrap script (like ubuntu does). 

I belive the install script has the same issue, the only thing I did after the install was:
```bash
gem install sinatra
sh /etc/init/dokku-installer.conf 
```

Debian isn't our primary target, but I don't think it'll be a hard fix. I'll poke this again in the morning when some of the guys are online.

**Comment by antoine-lizee** [comment]
Thanks @u2mejc 
We could also package for debian by just changing the pre-depends to the right debian alternatives (see above), and store the package in `debian/jessie` of the package repo if we wanted to keep the apt-get philosophy. I would agree that just installing the gems afterwards is an easier path to deployment for these platforms though. Just mentioning it on the `debian.md` would be nice then! I've put in a quick PR, with suggested changes.

**Comment by antoine-lizee** [comment]
Just adding a line maybe in the doc to be even clearer. See #1786.

**Comment by michaelshobbs** [comment]
@u2mejc @josegonzalez I'm fine with updating docs but how hard would it be to make this installation target work?

**Comment by u2mejc** [comment]
@antoine-lizee I think I might be propagating confusion. Ubuntu uses Debian style packages for it's package manager (being a child of debian).

The title:
>Debian Package Installation Notes

might be better at clarifying the purpose of the document if we made it:
>Unattended deb Package Installation Notes

So to clarify, that's not Debian installation instructions. :smile: 

Now that said, I jumped in here because I don't think supporting Debian would be too hard, but I'm not a current Debian user so I might not be the best to say that. Would you be willing to take a crack at a PR to update the deb.mk and bootstrap.sh files to support Debian?

**Comment by josegonzalez** [comment]
Stupid rubygems. The best fix here would be to move the whole web-installer bit to be python, and then just use the system python to handle everything (wouldn't need gems or anything).

**Comment by josegonzalez** [comment]
Lets change the title at least. I'll try and write a python version of the installer, and then we don't need to worry about ruby at all.

**Comment by antoine-lizee** [comment]
@josegonzalez @u2mejc Yeah, exactly, I got that the page was not Debian targeted *afterwards*, as the title is a little ambiguous. 

Indeed, I agree that getting the gem stuff out of the apt-get dependencies is the best bet middle/long term solution, but in the meantime it seems useful to slightly change the doc, see the PR (I've incorporated the title change suggestion).

**Comment by josegonzalez** [comment]
@antoine-lizee mind checking out #1794 and seeing if that would be better for your situation? I *lightly* tested it, so it _should_ work, but i haven't had time to check out if the debian package does the right thing out of the box.
