### ISSUE TITLE
Re-build an image without a git-commit

### ISSUE THREAD

**Issue by darkpixel** [dokku/dokku#182]
Is there currently a way to re-build an image without doing a git commit && git push?

I ran into out-of-memory errors during the build process on a box that had something like 512 MB RAM.  I upped the memory and wanted to re-start the build process without changing the code in the git repo...

**Comment by turicas** [comment]
The cited plugin is not working anymore (uses pluginhook, lacks `plugin.toml`) and I think this feature is very important to be in the core distribution since it can be useful in some cases, like:
- You didn't change your code, but some of your dependencies did (fixed security issues, optimized some routines, fixed bugs etc.), so you could rebuild and have fresh dependencies installed;
- When you're running an app that is not maintained by you and thus don't have write permissions on the mainstream repository; 
- For some reason when I execute `dokku run <appname> bash` it's running and old image (without all pip requirements installed, for example) and I sincerely don't know what to do to fix this. Ability to rebuild the image would help here.

Would you consider reopening the issue and implementing this as a core plugin? I suggest the command `dokku apps:rebuild <appname>`.

**Comment by josegonzalez** [comment]
This command was added a very long time ago in `dokku ps:rebuild` and should be in our process management docs. I definitely recommend looking through our docs in the future for stuff like this, as we cover quite a bit of functionality in the core project now.

Please also avoid commenting on 6 year old issues in the future. It notifies quite a few people who might otherwise no longer be using the project. Thanks!
