### ISSUE TITLE
Create an official Dokku-Persisted Storage plugin

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1820]
It would be great to have a plugin that can handle persisted storage in a nice way. The reason for this, is that not everyone can store data on S3 (because of local law they are prohibited to store anything on servers owned by US companies.)

I think the following API with be awesome: `dokku storage:create app_name`. This will then create a folder in `/home/dokku/storage/`. And the volume will be mounted into the container on `/shared/`.

Downside of the above API is that we only support one shared folder per app, but I think for starters that would be good enough.

Relates to: https://github.com/dokku/dokku/issues/1695

**Comment by josegonzalez** [comment]
What about something like:

```shell
dokku storage:create APP /full/path/in/container
```

```shell
# creates
/var/lib/dokku/data/apps/APP_NAME/directory/from/app/dir/in/container

# mappings would be in
/var/lib/dokku/config/apps/APP_NAME/mappings
# mappings are comma separated paths, in container => out of container
```

**Comment by jvanbaarsen** [comment]
Interesting, that might be even better! But I'm wondering, are people aware of the structure of the container inside? If not, we might over complicate the API. If people are aware, the specifying the path makes total sense.

**Comment by josegonzalez** [comment]
We could assume if they don't set a full path, that it is based on `/app`? And output that as a message to the user.

**Comment by jvanbaarsen** [comment]
:+1:, so to be explicit here:

**Command** `dokku storage:create my_app /shared/`
**Location in container** `/shared/`
**Location on host** `/var/lib/dokku/data/apps/my_app/shared`

**Command** `dokku storage:create my_app`
**Location in container** `/app/`
**Location on host** `/var/lib/dokku/data/apps/my_app/app/`

**Command** `dokku storage:create my_app /shared/location/`
**Location in container** `/shared/location/`
**Location on host** `/var/lib/dokku/data/apps/my_app/shared/location/`

**Comment by josegonzalez** [comment]
We should *never* allow an empty path, so your second example would be wrong. The others work though.

Maybe `storage:attach` is a better name? I'm not sure on the verbiage.

What happens when you attach/detach storage? Should we trigger a restart? If so, we should support --no-restart, similar to the config plugin.

**Comment by u2mejc** [comment]
There is a third party plugin today: (found here: http://dokku.viewdocs.io/dokku/plugins/): https://github.com/ohardy/dokku-volume

Related, I don't think the volume plugin should be hardcoded to use the /var/lib/dokku/data/apps/ dirs, if anything I would want it to be freeform so I can attach like a EBS volume I have mounted.

**Comment by u2mejc** [comment]
To elaborate on my last comment, the entire system should be seen as ephemeral. Not everyone using dokku has physical hosts, most are on cloud VMs (AWS, DO, etc) and those can be retired at the drop of the hat. Lead by example, we don't recommend saving to the local storage when using cloud providers. ;-)

**Comment by josegonzalez** [comment]
You can use a symlink if you want anything fancy. As long as ensure its in the DOKKU_LIB_ROOT, we can ensure we have support for sockerfile deploys of dokku.

**Comment by rdurgarao** [comment]
Is there any alternative way for persisted storage on dokku?

**Comment by u2mejc** [comment]
Looks like the plugin I had been referencing has not been maintained much in the last year (missing the .toml file). I'll consider https://github.com/dokku/dokku/pull/1687 blocked until I can document the new plugin. Seems easy enough, I'll take a first pass at a PR today, but I'm adding ability to add custom paths. :smile: 

More indepth: /var is sometimes moved to a limited partition on physical servers so that temp items do not fill it up (and /tmp is sometime remap as a ramdisk!). It's actually probably not our best location for dokku files, since we're assuming that everyone has moved to a monolithic root partition. It's probably off topic here, but we should probably move dokku inside /usr (user vs variable), similar to the default httpd root.

**Comment by michaelshobbs** [comment]
The `docker volume` command seems relevant here. https://docs.docker.com/engine/reference/commandline/volume_create/
https://docs.docker.com/engine/reference/commandline/volume_inspect/
https://docs.docker.com/engine/reference/commandline/volume_ls/
https://docs.docker.com/engine/reference/commandline/volume_rm/

**Comment by u2mejc** [comment]
@michaelshobbs Correct me if I'm wrong, but that actually not what this issue is about. Docker is great in their reuse of terminology to add confusion. That feature *docker volumes* is not the same as mounting volumes; *docker run -v*. 

For me and the plugin I have in my repo, the -v is what I would want. Say a user uploads a file using a dokku app, but you want to access these on the local host file system, you can't if it's a docker disk image (again aka volume by docker).

So to ask in a more stardard *nix way, for this plugin, do we want to mount local host dirs in the container or add a new docker image to be mounted in the container?

**Comment by michaelshobbs** [comment]
preface: I may be off base here.

My thinking here is to do this the "docker way" by using their "volume" object. The only difference between a `docker volume` and a `bind-mount (-v)` is the storage location. A `bind mount` stores files in the filesystem location you specify and a `docker volume` stores file in the docker daemon's storage location. 

My hypothesis (I've seen reference to this in some of the dockercon presentations) is that in upcoming versions of docker will allow you to share volumes between docker hosts.

Now, I'm not saying we design and implement a feature today based on tech that may potentially exist in the future. We may though want to keep in mind that the folks at docker are also very much incentivized to make the storage situation more widely, shall we say, palatable.

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
