### ISSUE TITLE
Unattended upgrade is not working

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1851]
When running an Unattended upgrade, I still get the following question:

```
Configuring dokku
-----------------
Enable the web-based config page?
```

I use the following command: `$ sudo apt-get install -qq -y dokku`. Is this something I'm doing wrong?

**Comment by josegonzalez** [comment]
How did you setup debconf?

**Comment by jvanbaarsen** [comment]
Yeah, after posting this I realised that might be the problem. Doing a test run now to see if I setup debconf with `webconfig` set to `false` will work. (As always, thanks for the blazing fast response :yellow_heart: )

**Comment by jvanbaarsen** [comment]
@josegonzalez Ok, I installed with the following command:

```
    "sudo echo 'dokku dokku/web_config boolean false' | debconf-set-selections && "\
      "sudo echo 'dokku dokku/vhost_enable boolean false' | debconf-set-selections && " \
      "wget https://raw.githubusercontent.com/dokku/dokku/v0.4.6/bootstrap.sh &&
        sudo DOKKU_TAG=0.4.6 bash bootstrap.sh"
```

When I try to upgrade, I get the following:

```
Configuring dokku
-----------------
Hostname or IP for server:
```

So it seems not to be working the way I would expect (or I have run into a bug :D ). What do you think?

**Comment by jvanbaarsen** [comment]
Oh wait, I now get a different error when installing with the above settings:

```
Error: keyfile '/root/.ssh/id_rsa.pub' not found.
       you can enter a new keyfile path when you restart the installation.
dpkg: error processing archive /var/cache/apt/archives/dokku_0.4.6_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/dokku_0.4.6_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Is that because I'm required to have a SSH key present on my root user? Since that is not the case when running the normal install

**Comment by jvanbaarsen** [comment]
@josegonzalez Ah I see it now, when I say `web_config=false`, it will check if the keyfile is present. I that really a required thing? Can the keyfile not be optional?

**Comment by josegonzalez** [comment]
A "normal" install will more or less force users to use the web ui to setup their first user, which is why we can ignore the key file not existing on disk (it will be created by the user in the web ui).

- On new installations, we *require* either web install or the file on disk to setup dokku. Doing otherwise would allow users to get into a state where they cannot push a repository, causing stupid issues like "whoamygod dokku doesn't work".
- On upgrade, we only use the file if the system is [being reconfigured](https://github.com/dokku/dokku/blob/master/debian/postinst#L87).

If you use debconf and set defaults before installing a package, debconf will prompt you for values that weren't set, ignoring any `-q` flags we call in the bootstrap script. You should set all the values before calling bootstrap if you want a fully unattended installation process.

On upgrades, you shouldn't be prompted for these values unless you previously didn't set them. In this case, if you always upgrade with the bootstrap script, you won't get any prompts unless we add new values.

**Comment by jvanbaarsen** [comment]
@josegonzalez Ok I understand the reasoning behind this. Since I'm creating a webUI where you can do al this stuff, would you be open for a PR where you can opt-out of the required params? So default behaviour stays as is, but only if you're sure what you're doing you can opt-out

**Comment by josegonzalez** [comment]
Why aren't you setting a key?

**Comment by jvanbaarsen** [comment]
At that point I don't have a key for any user. The flow is as follow:

1. User fills in a form in the IC app with the following fields: Server name, Ip Address
2. User sees a public key they need to add to their server where they are going to install Intercity/Dokku on.
3. App checks if the key has been added to the authorized_keys, if so it starts installing Dokku

In step 3, there is no SSH key generated for the root user. (And there will never be).

Users can then add "Deploy users" to Dokku via the Intercity web interface.

**Comment by josegonzalez** [comment]
Alright, you've convinced me I guess. Feel free to make a PR.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
Will do so later this week.

**Comment by jvanbaarsen** [comment]
@josegonzalez Is there a way to test the debian installation script from source? (as in, I changed some line of code in there, and now I want to see what happens if I use my local code as a debian package)

**Comment by josegonzalez** [comment]
You can build a new set of packages via the following command:

```shell
vagrant up build
```

This will build *all* packages, and you can test subsequent changes by calling the following:

```shell
vagrant ssh build
make deb-dokku
```

Note that you'll be making packages with the same version as the current stable release, so your testing environment may need to purge the old package to test.

**Comment by jvanbaarsen** [comment]
Thanks!

**Comment by josegonzalez** [comment]
Closing as there is a pr open.
