### ISSUE TITLE
How are the Docker containers built?

### ISSUE THREAD

**Issue by npazo** [dokku/dokku#1932]
Question, not an issue.

I am trying to understand how Docker containers are created, and what is used to do so. If I am starting up a Rails application, I know that it uses the Heroku Rails build pack, but which container does it use? 

I am trying to figure out if there are performance improvements that can be made to save on resources and I know that with Docker containers going as slim as possible is often a way to do this.

**Comment by josegonzalez** [comment]
What do you mean by "which containers"? 

Dokku uses docker to create a docker image. If you are using buildpacks instead of a Dockerfile, this means that you'll be using the base [herokuish](https://github.com/gliderlabs/herokuish) image to kick off the building of the image. This is configurable by setting a `DOKKU_IMAGE` environment variable in the `$DOKKU_ROOT/dokkurc` file.

You can also use dockerfiles to build an image as documented [here](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/).

**Comment by npazo** [comment]
I don't know how I missed that. Thank you.

So it's safe to say that the images being built out of the box are pretty bloated and un-optimized for specific languages?

**Comment by josegonzalez** [comment]
No, it's not safe to say that. What gives you that idea?

Feel free to hop on our [irc](https://webchat.freenode.net/?channels=dokku) or [slack](https://glider-slackin.herokuapp.com/) if you'd like to discuss this. My nick in both places in `savant`.
