### ISSUE TITLE
Turning off wildcard

### ISSUE THREAD

**Issue by djbk** [dokku/dokku#1937]
What's the best way to do this?

I have a solution, but I'm not exactly sure if it's the best way (still new to nginx, dokku, etc.). For example, let's say I'm redirecting <code>www.example.com</code> to <code>example.com</code>. On digitalocean, I added a "www" record. In my app I added an nginx template file with an additional server block that listens for server_name <code>www.example.com</code> and redirects to <code>example.com</code>. Is this correct? Will I face any issues in the long run?

From all the docs/tutorials I've read, they all add a wildcard, so I'm just a bit cautious.

**Comment by djbk** [comment]
Well, it seems like I can't access different apps on different subdomains now. Do I really need a wildcard??

**Comment by jvanbaarsen** [comment]
@djbk Here is information on how to turn off the Wildcard: http://dokku.viewdocs.io/dokku/nginx/#default-site

**Comment by josegonzalez** [comment]
You do not need a wildcard `A`/`CNAME` record. You can just as well enter specific DNS records as necessary.

Our docs say to use a wildcard because it will result in the fewest issues while provisioning new applications, and otherwise we will have a lot of support requests asking why certain DNS requests are failing.

As @jvanbaarsen mentioned, you can turn off the catch-all as well by setting a custom vhost.

**Comment by djbk** [comment]
I see. Thanks guys.
