### ISSUE TITLE
Allow custom base image

### ISSUE THREAD

**Issue by ojii** [dokku/dokku#194]
It would be amazing if the base image would be configurable (at least on a system level, ideally on an app level). I'll look into how to achieve this if this is a desired feature.

**Comment by oelmekki** [comment]
Hi there,

If I got the proposed solution right, this means we have to fork dokku 
to customize base images? I certainly would love a more "implemented" 
way to do it too :)

A major advantage of dokku which makes it even better than heroku is
the ability to build pretty much any kind of setup using docker images.

It would be even more mind blowing if we could combine the power of
dockerfile with the power of buildpacks: you use a dockerfile to build
a base image and add your specific system dependencies, then you use
the power of buildpacks to automatically do all the already well
figured out things, instead of having to either go with a common stack
(buildpacks) or drop it altogether to build everything from scratch
(dockerfile).

**Comment by josegonzalez** [comment]
A few things:

- You can set the `DOKKU_IMAGE` env var as specified [here](https://github.com/dokku/dokku/blob/master/dokku#L14) to any base image. I would recommend looking at [gliderlabs/herokuish](https://github.com/gliderlabs/herokuish) as a starting point, and modifying it as necessary.
- There is no need to fork dokku, just the base image. You can set it globally in your `/home/dokku/.dokkurc/image` file (all files in the `.dokkurc` directory are sourced in).
- You can use the [`dokku-apt` plugin](https://github.com/F4-Group/dokku-apt) to install packages in your app's environment, avoiding the need to fork anything.

**Comment by oelmekki** [comment]
Thanks Jose :)

The `DOKKU_IMAGE` env variable alone will allow to solve the issue that 
led me to comment here.

That being said, regarding general user experience, don't you think it 
could make sense if instructions to build the base image for a project 
was included as Dockerfile in this project repos, while still being 
able to take advantage of buildpacks?

`dokku-apt` is fine, but there is often more to system preparation than
just installing packages, like sending or changing config files, adding
certs, ... all kind of things I'm sure we can find way to do, but that
would feel natural in a Dockerfile.

**Comment by josegonzalez** [comment]
You are *more* than welcome to make a pull request with any documentation you think is good for dokku :) Probably a page under the `Development` section with simple instructions on changing the base image, as well as a link to the `gliderlabs/herokuish` project? 

Let me know if you need help with that pull request :)

**Comment by oelmekki** [comment]
> Probably a page under the Development section with simple instructions on changing the base image, as well as a link to the gliderlabs/herokuish project?

Sure, this will already help :)

Regarding code PR, I'm not really used to write sh code that seriously, 
but I'll give a try.
