### ISSUE TITLE
Broken link in Azure installation instructions

### ISSUE THREAD

**Issue by simenbrekken** [dokku/dokku#1973]
[The instructions for installing Dokku on Azure](http://dokku.viewdocs.io/dokku/getting-started/install/azure/) points to https://azure.microsoft.com/en-us/documentation/templates/dokku-vm which doesn't exist.

I've been unable to locate a replacement link but perhaps someone else more familar with Azure knows where to start looking.

**Comment by josegonzalez** [comment]
@sedouard can you take a look at this? You contributed the initial integration, and the template files exist [here](https://github.com/Azure/azure-quickstart-templates/tree/master/dokku-vm) so...

**Comment by sedouard** [comment]
hey sorry about that @simenbrekken. There's something wrong with the template search index.

I reported the issue here:

https://github.com/Azure/azure-quickstart-templates/issues/1343

In the mean-time you can go to the github page directly:

https://github.com/Azure/azure-quickstart-templates/tree/master/dokku-vm

**Comment by sedouard** [comment]
I guess I included the link to the search index because it's much more approachable for people unfamiliar with templates. But it's been buggy - I think they're hitting github API limits so changing to he github url is probably a safer bet
