### ISSUE TITLE
Replace nginx proxy with interlock version

### ISSUE THREAD

**Issue by blackxored** [dokku/dokku#1996]
One of the main limitations of running Dokku under Docker Swarm is the fact that the Nginx proxy runs outside the container and unless you hack your way into container networking from the outside, it has no way of correctly proxying to containerized services in an overlay network. 
This has been a problem for quite a while in the Docker ecosystem itself, but recent features of Swarm have their authors and evangelist pointing out to ehazlett/interlock as a solution. It's a dynamic load-balancer based on docker events, and integrating with dokku would allow us to run multi-host containers where dokku and the LB lives on the swarm master. 
Let me hear your thoughts about this.

**Comment by josegonzalez** [comment]
In dokku 0.5.0, we are allowing users to set a different plugin to handle proxying. For instance, you could swap the nginx one for haproxy, or use traefik, or this interlock version.

That said, one of the main goals with dokku is to create an awesome, single-server experience. Our current nginx implementation fits that bill well. If you'd like to PR a change to use ehazlett with nginx as the default that maintains BC with our current setup, I'd love to see it, otherwise I think this belongs in a plugin.

@michaelshobbs thoughts?

**Comment by michaelshobbs** [comment]
The proxy swap feature is definitely at the plugin level. The stock nginx-vhosts plugin is not intended to be used with another binary. That said maybe it would work but I don't think it makes sense for core to adopt a different version of nginx. Definitely a great idea for a plugin.

**Comment by josegonzalez** [comment]
Right, thats what I meant. Each application can set it's preferred method of load balancing, and if someone wants to integrate with ehazlett/interlock, more power to them.

**Comment by josegonzalez** [comment]
Closing as I think we've answered how this *should* work, and 0.5.x should make this much easier to do.
