### ISSUE TITLE
nginx configuration in WORKDIR is possibly dangerous (depending on container)

### ISSUE THREAD

**Issue by hojerst** [dokku/dokku#2067]
I'm trying to host a "FROM php" Docker based app behind an SSL proxy. The documentation states this can be achieved by adding a "nginx.conf.sigil" either to WORKDIR or the root of the app repository. However it seems, that on Docker based apps, only the <WORKDIR>/nginx.conf.sigil is working. The nginx.conf.sigil in the root of the app repository is ignored.

However, adding a nginx.conf.sigil to the WORKDIR might influence the application that is packaged. This is the case for a "php" Docker image based app: The WORKDIR is exposed as the webserver's root. So there are currently only 2 options:
  - expose nginx.conf.sigil in webserver root, which is potentially dangerous
  - rewrite official Docker images, which somehow negates the benefits of the image

I propose to, either respect "nginx.conf.sigil" in the applications root directory or at least move the nginx.conf.sigil inside the app container to / which seems like a safer location (although not perfect imho).

**Comment by josegonzalez** [comment]
You can delete your `nginx.conf.sigil` in the `ENTRYPOINT` of your application, which would fix your particular security worries.

If you're deploying via a tagged image or a tar blob, you don't get the application's "root" directory - the code simply won't be in the git repo - so neither of your solutions work.

For PHP applications, I've never seen the recommendation that your application root be what is exposed as the webserver. In fact, it's usually something like `web` or `webroot`. Doing otherwise means potentially exposing actual source code, which is way worse than exposing an nginx conf template.

**Comment by hojerst** [comment]
Deleting the nginx.conf.sigil in the ENTRYPOINT is a good workaround. Thanks for the idea.

Nevertheless, I think there is a misunderstanding what i meant with "root". I'm using a git repo with a Dockerfile for deployment. So in this case there IS an "application root" ("git source root"). Furthermore I recommended to move the nginx.conf.sigil to "/nginx.conf.sigil" instead of "<WORKDIR>/nginx.conf.sigil". 

Regarding my particular case (php app): Please have a look at Docker's official "php" (hub.docker.com/_/php) image. e.g. https://github.com/docker-library/php/blob/0d23b3d08770889c6cb31e8e5374334879103f92/5.5/apache/Dockerfile

This image sets the WORKDIR to /var/www/html and later exposes the "current working directory" as webserver's root directory. You can <?php include() ?> code from anywhere else to protect at least a part of your source. However the app needs to be designed for this. There are apps out there, that are not designed for this. One example is wordpress and the official wordpress image is based on the official php image.

**Comment by josegonzalez** [comment]
- Not everyone has that git source root. As I mentioned before, users can deploy image tags or tar blobs, both of which go through the same system.
- The two paths you mentioned in last comment are both `/nginx.conf.sigil`.
- For wordpress, the `ENTRYPOINT` suggestion still applies, and your git application directory doesn't, so we cannot do what you are suggesting there anyhow.

Given our constraints, I don't think there is anything we can do here. @michaelshobbs thoughts?

**Comment by hojerst** [comment]
Sorry, I made a typo in the path in my comment. I meant: 'I recommended to move the nginx.conf.sigil to "/nginx.conf.sigil" instead of "WORKDIR/nginx.conf.sigil"'.

Ok, I see your point here. I thought the system differentiates between a Dockerfile deployment and a tag based deployment. Considering your clarification that the same subsystem must handle a Dockerfile/git based deployment and a tar/tag based deployment, the current behavior makes sense.

However, "/" should be a better "inside of container"-location than WORKDIR: The WORKDIR is some kind of application state. As you can see by the php/wordpress example: Some (widespread) containers have assumptions regarding the content of WORKDIR. I know that the same might hold true for the container's root "(/)" or any other directory. However, as most images are based on some kind of linux distribution and the root folder normally belongs the system, this should rarely be the case.

Note: As a mentioned earlier: The ENTRYPOINT which deletes WORKDIR/nginx.conf.sigil is a good workaround but this needs to be considered by every container developer who uses dokku and a affected base image.

**Comment by michaelshobbs** [comment]
@josegonzalez my thoughts...
IMO, dockerfile apps are very much left to the reader. Every time we attempt to "constrain" dockerfile functionality to some "standard" we end up pissing off some other segment. If you want a "safer" deployment method that comes with some "bumpers" and doesn't require you to think about how the app is executed, then use a buildpack. Otherwise, you're on the hook for your app execution and layout when you choose the flexibility of a dockerfile. 

In this context, if you're choosing to use a dockerfile and a custom nginx template and you're worried about that leaking, then handling that concern in your `ENTRYPOINT` script is perfectly reasonable.

**Comment by josegonzalez** [comment]
In that case, I'll add a warning to the dockerfile docs to state "CAUTION: Hot Coffee is Hot". We've had a few similar issues with Dockerfile deploys where users expect the same sort of care as buildpacks, and I think that's the opposite of how we've approached development of features for it (power user feature).
