### ISSUE TITLE
Question: is Dokku logo Creative-Common?

### ISSUE THREAD

**Issue by julienma** [dokku/dokku#2123]
Hey,
I really like the Dokku logo.
Does anyone know who made it, and how it is licensed? Can I use it in some personal projects related to Dokku?

![](https://avatars3.githubusercontent.com/u/13455795?v=3&s=400)

**Comment by josegonzalez** [comment]
@julienma do you mind going on slack/irc and getting in touch with me directly? The questions are valid, I just need to understand what you're trying to do.

**Comment by u2mejc** [comment]
@josegonzalez You should reply here too for future ref. 😉

**Comment by josegonzalez** [comment]
I spoke to him offline, and will update this thread when I have a concrete answer.

**Comment by mimischi** [comment]
Any updates on this one? And is there any "press kit" for the logo? Couldn't find any higher resolution than the one linked above.

**Comment by josegonzalez** [comment]
@mimischi there isn't a press kit, though I have the .ai files etc.

At the moment there is no license so it's basically not for public use. As I understand copyright law -
 as told to me by a lawyer in the somewhat recent past - since there is no explicit license, the only users that may legally use it without repercussions are myself and those I have personally given a grant. As such, the Dokku project may use it - we've done so for stickers, logos, and the website - and I may use it, but thats it.

If you have a reason you want/need it, you can post it here and I might give you a grant, depending on what it is.

**Comment by he8us** [comment]
Hello @josegonzalez,
I want to write a post series on dokku and I wanted to use the logo to illustrate the posts. Do you need more informations in order to grant or deny the use of the logo (and bigger if possible)

**Comment by mschipperheyn** [comment]
I recommend releasing this in creative commons so people can use it to put on leaflets, sites etc to promote the fact they are using Dokku. There is no real reason to clamp down on public use.

**Comment by Liberatys** [comment]
@josegonzalez Hey :D Sorry for bothering ^^ I wrote you an email in regards to us (www.renuo.ch) using the dokku logo on our website? We've been investing a lot of time in learning and using dokku and would like to showcase that effort on our website :D Have a great day

**Comment by schmijos** [comment]
I assume:

> You need permission to use a logo **unless** it is for editorial or information purposes, such as when a logo is used in a written article or being used as part of a comparative product statement.

[https://www.upcounsel.com/permission-to-use-logo#can-you-use-logos-without-permission]

**Comment by josegonzalez** [comment]
I am still not giving anyone permission to use the logo.
