### ISSUE TITLE
No (or little) downtime server updates

### ISSUE THREAD

**Issue by ncri** [dokku/dokku#2131]
After I read a comment by @michaelshobbs in another issue, stating that "Upgrading is not advised on running apps. You'll want to stop everything first.", I wonder how to upgrade the server with no or little downtime? Logging into my digital ocean droplet i see upgrade notes quite frequently. If I stop the app I obviously have downtime. Also many times upgrades need a server restart. Wondering how Heroku does it. I assume they upgrade on a new server then start the app there and switch over to avoid downtime. Possibly there is a way to mirror/clone a droplet on digital ocean. Maybe someone can point me to some information about this? Thanks! 

Oh, and @josegonzalez: feel free to ask me to post this on SO. :) I only posted it here, because you wrote that I should open a new issue for this... ;-)

**Comment by haywirez** [comment]
Not sure if this is possible without rerouting traffic to another DO instance.

**Comment by ncri** [comment]
And I wonder if even that is possible? As one would have to do a DNS change. But I haven't looked into Digital Ocean's options yet, maybe they offer something like that. Seems a bit tricky though. 

But how about minimizing downtime if it's not avoidable? With Heroku we are basically used to zero downtime. I'm wondering how much downtime to expect with a Dokku based server setup, when frequently updating the server.

**Comment by ncri** [comment]
Interesting coincidence, I just got a link to this post: https://blog.heroku.com/archives/2016/3/21/patching-glibc-security-hole:

"For the Common Runtime and Private Spaces this is built into our infrastructure. When we push a new software version, we build a new base image (which is what dynos live on top of) and cycle your dynos off to a fresh instance using the new image."

Slick. However I'd prefer to move away from Heroku. :)

**Comment by haywirez** [comment]
Digital Ocean has the option of [floating IPs](https://www.digitalocean.com/community/tutorials/how-to-use-floating-ips-on-digitalocean).  You should be able to seamlessly route traffic to another droplet while you upgrade on the other one.

**Comment by josegonzalez** [comment]
> If implementing or even thinking about the stuff below hurts your brain, maybe it's worth the money you saved on not paying Heroku. They are a fine service, and Dokku by no means replaces everything they do, otherwise we wouldn't be having this conversation.

Scaling is a complex problem, and there are companies with entire divisions whose job is to implement things such as this.

Open questions/concerns:

- Where does your datastore live, and what happens when the server running that datastore stops working?
- If you have to move your datastores, do you expect to survive that move with zero-downtime?
- How do you currently take backups? Are all settings backed up, can can you easily restore that from one machine to another?
- Outside of running dokku, is there any software (fail2ban, iptables, etc.) where you installed something new or modified existing configuration, and how easy would it be for you to replicate that?
- Do you have a floating ip (DigitalOcean), elastic ip (AWS) or a similar construct? What happens when your server dies, does that ip get re-associated to your new instance, or is it just sitting there?
- If you shot your node in the head *right now*, what happens to your infrastructure?
- DNS is always going to crush your soul for some stupid reason, so don't expect TTLs to work as you expected everywhere.

The above questions are why something like Heroku is *really* nice. It's no longer your problem. By using Dokku, you trade one set of problems for another, and now you own availability.

How do *we* do high availability?

- Ask yourself what the monetary cost of downtime is, and spend around that amount of time/money implementing your solutions.
- Use managed datastores (RDS, ElastiCache, CloudAMQP, etc.) where the providers have implemented HA solutions for those datastores.
- Use HA datastores (RethinkDB clustering, MySQL replication, Postgres, HA RabbitMQ Queues, Elasticsearch Clustering, Redis Sentinel) where a managed solution isn't possible.
- Test test test your downtime/recovery solutions by shooting a node in the head and seeing what happens. Ideally zero to no downtime.
- Run more than one of everything.
- Use configuration management (Ansible, Chef, FSS, Puppet) to automatically provision new servers. `cloud-init` can even kick off runs when a server starts.
- Test changes/upgrades in a staging environment before promoting to production.

How could you implement an HA version of dokku?

- Docker swarm, which is an open problem I'm actively working on (though it's definitely possible).
- There is a chef cookbook out there that does provisioning on opsworks. @michaelshobbs uses this workflow I believe.

**Comment by ncri** [comment]
@haywirez: Sounds quite interesting, I will look into it.

@josegonzalez: Thanks a lot for this great list for getting started with this topic. I'm well aware Heroku is great and it takes a lot of workload away from us. However, I'm also excited about having more control over the server and testing out various alternative setups. And thanks to Dokku I think we are getting closer to a low(ish) maintenance setup, which can be operated similarly than Heroku. Afterall Dokku closely mimics Heroku deploys. However, failover scenarios are very important and only with suitable solutions/procedures in place I would make the switch away from Heroku for a larger production app.
