### ISSUE TITLE
Procfile for cron jobs

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#2135]
I cant seem to get worker processes running properly per the instructions at http://dokku.viewdocs.io/dokku/deployment/one-off-processes/

Ive got a Procfile that looks like this:

```
web: newrelic-admin run-program gunicorn app:app --log-file=-
worker: while true; do sleep 10; done
```

However, when I try to spin things up, I get this in the log and the worker container doesnt stay running. Thoughts on what I might be missing here?

```
2016-04-23T03:51:44.391450253Z app[worker.1]: /tmp/bashenv.434844067: eval: line 487: syntax error near unexpected token `do'
2016-04-23T03:51:44.391474581Z app[worker.1]: /tmp/bashenv.434844067: eval: line 487: `echo while true; do sleep 10; done'
```

Output of the following commands

- `uname -a`: Linux <REDACTED> 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           488        362        126          0         28        123
-/+ buffers/cache:        210        278
Swap:         1023        113        910
```

- `docker version`:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

- `sigil -v`: `0.4.0`
- `dokku version`: `0.5.4`

**Comment by josegonzalez** [comment]
First, the docs link isn't readthedocs. I'm in the process of getting that taken down. The doc is actually here: http://dokku.viewdocs.io/dokku/deployment/one-off-processes/ .

We should probably change the docs to say `sleep infinity`, since herokuish eval's the command via echo. I may have been high when I wrote those docs or something.

Do you want a worker process, or something to randomly run cron tasks in? If the former, I suggest looking into a background queue worker, like [rq](http://python-rq.org/) or [amqp-dispatcher](https://github.com/opschops/amqp-dispatcher) for python. For the latter, I'll fix the docs.

**Comment by mattberther** [comment]
Thanks @josegonzalez. I appreciate the response.

**Comment by josegonzalez** [comment]
Let me know if that `sleep infinity` works for you. Seemed to work here.

**Comment by mattberther** [comment]
Worked great. Thanks!
