### ISSUE TITLE
dokku upgrade wipes out VHOST, empties HOSTNAME

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2146]
Whenever dokku is upgraded (automatically via Ubuntu updates or manually triggered) the /home/dokku/VHOST file gets wiped out. Also, /home/dokku/HOSTNAME gets emptied out.

Whenever an upgrade is done I have to manually patch these 2 files and restart nginx.

**Comment by michaelshobbs** [comment]
This looks [by design and overridable](https://github.com/dokku/dokku/blob/v0.5.5/debian/postinst#L81-L90). I'm not all that fluent in the language that is .deb but I **think** if you define `dokku/vhost_enable` and `dokku/hostname` using `debconf-set-selections` you won't lose those files on upgrade.

**Comment by josegonzalez** [comment]
I think maybe a better experience would be to only "update" the HOSTNAME/VHOST if there is a value from debconf, otherwise maybe warn if we are updating it?

**Comment by shritesh** [comment]
I stumbled upon the same issue today (upgrading from 0.5.6 to 0.5.7). Will it be a good idea for the debconf selections to be set by the initial web-config?

**Comment by josegonzalez** [comment]
Totally looking at fixing this before the o.5.8 release.
