### ISSUE TITLE
How to set which libstdc++.so.6.* version to load within docker container?

### ISSUE THREAD

**Issue by benmarten** [dokku/dokku#2176]
I am running into an issue with a specific library version being referenced from the node-module `nodegit`.

The nodegit module is looking for module `GLIBCXX_3.4.20` which is present on the system:
`ben@box1:~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 |grep 'GLIBCXX_3.4.20'
GLIBCXX_3.4.20`

but it seems the docker image does not pick up the correct version, but an earlier one (libstdc++.so.6.0.17):

	ben@box1 ~> sudo find / -name 'libstdc++.so.6.*'
	/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21-gdb.py
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
	--> /var/lib/docker/aufs/mnt/3d8a87af0a330227065dafd57a7eaacad0d99f9d6c5a3b2d9c082c47e34366bc/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17

How can I tell dokku/docker to include version *.20 of that lib in the container?

This is tested on fresh Google Cloud Engine instance, Ubuntu 14.04LTS & latest dokku from today.

This issue seems related, but the proposed solution (`LD_LIBRARY_PATH=/usr/lib`) does not solve it for me: https://github.com/docker-library/gcc/issues/18

**Comment by michaelshobbs** [comment]
Generally speaking, node deps are handled by the buildpack. Also, the dokku base-image [herokuish](https://github.com/gliderlabs/herokuish) is based on [heroku/cedar:14](https://github.com/gliderlabs/herokuish/blob/v0.3.13/Dockerfile#L1).

I'm curious, have you attempted to deploy this on Heroku proper and does it work?

**Comment by benmarten** [comment]
It runs into the exact same error on heroku! :(
On my Ubuntu box, at least I am able to install the required library via `apt-get` though. I'd assume docker would be able to pick that up somehow?

**Comment by michaelshobbs** [comment]
The filesystem inside a docker container is wholly segregated from the host filesystem. Only those files/directories you explicitly add to the image are included.

In order to deploy this with dokku, you could try one of 3 approaches (disclaimer: not sure which of these would actually work)
- [dockerfile deployment](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/) where you use a `Dockerfile` to install the desired version of glibc and any dependent packages + nodegit
- use the [dokku-apt](https://github.com/F4-Group/dokku-apt) plugin to install the desired glibc version at app deploy time
- build and use a custom herokuish image that has the desired glibc version installed

Though the last two seem fraught with peril as the heroku buildpacks download compiled binaries that might be linked to the older version.

**Comment by benmarten** [comment]
Thanks so much for the explanation and possible solutions...
I agree that dokku-apt seems the easiest route, I am currently running into an issue there (https://github.com/F4-Group/dokku-apt/issues/16) but I'll report back when that's solved ;)

**Comment by cmmartin** [comment]
Hey @benmarten. Did you ever find a solution?

**Comment by cmmartin** [comment]
For those interested, I was able to successfully install [nodegit](https://github.com/nodegit/nodegit) in dokku using [dokku-apt](https://github.com/F4-Group/dokku-apt) and it was relatively painless. Simply install the plugin and include the following files in the root of your project...

apt-repositories
```
ppa:ubuntu-toolchain-r/test
```

apt-packages
```
libstdc++-4.9-dev
```

**Comment by benmarten** [comment]
@cmmartin It's been a while; so honestly I don't remember if i ever solved it. Seems you did though! Thanks for providing the info :)

**Comment by aral** [comment]
Note that the `apt-repositories` file requires an empty line at the end or it will not work. Thanks again, @cmmartin, this saved me lots of time :)
