### ISSUE TITLE
Official support for Ubuntu 16.04

### ISSUE THREAD

**Issue by cmosetick** [dokku/dokku#2263]
The Ubuntu Trusty 14.04, deb package appears to install correctly on Xenial 16.04 as well.

Ideally though there is a specific .deb package in packagecloud.io for 16.04.

Additionally, the `bootstrap.sh` seems to assume 14.04.

Note:
I tested the install of the 14.04 .deb package on 16.04 doing things manually, rather than using bootstrap.sh

**Comment by josegonzalez** [comment]
Things to do here:

- [ ] Modify [debian install docs](https://github.com/dokku/dokku/blob/fc63061eafffc93ec13503c36dcade0339fe0bff/docs/getting-started/install/debian.md) for each new supported distro (Debian 8.2 and Ubuntu 16.04)
- [ ] Modify the [bootstrap.sh](https://github.com/dokku/dokku/blob/af486050546f18ad9c0f702315bdd39660f80202/bootstrap.sh) to support `1.0.0+` dokku installation
- [ ] Modify the [bootstrap.sh](https://github.com/dokku/dokku/blob/af486050546f18ad9c0f702315bdd39660f80202/bootstrap.sh) for each new supported distro (Debian 8.2 and Ubuntu 16.04)
- [ ] Modify the [home landing page](https://github.com/dokku/dokku/blob/2b019aef2fc5803f0899113b67c7733b35c14d58/docs/home.html#L135) to use a variable for the distro for the "manual" install process.
- [ ] Modify [deb.mk](https://github.com/dokku/dokku/blob/d2ee0994c08a8b1a51d10d14215e374ac1aaeb41/deb.mk#L67) for each new supported distro (Debian 8.2 and Ubuntu 16.04)
- [ ] Fix the release process to upload to each new supported distro (Debian 8.2 and Ubuntu 16.04).

**Comment by miguelcobain** [comment]
So, for beginners, will we be able to run dokku 0.6.5 without problems with the bootstrap.sh install method?

**Comment by josegonzalez** [comment]
You can already use the bootstrap.sh on debian 8.2 and Ubuntu 16.04 - we build debian packages which are distributed agnostic - this will just make that more explicit.

**Comment by miguelcobain** [comment]
@josegonzalez thank you.

So, for guture reference, what are the OS requirements for running dokku?
Any (ymmv, of course) debian based distro? Because the README states:
> A fresh VM running Ubuntu 14.04 x64

**Comment by josegonzalez** [comment]
Our latest packages currently officially support Debian 8.2, Ubuntu 14.04, Ubuntu 16.04. We do not officially support any non-LTS release of any distro, though I am happy to make fixes against them if they don't break official support otherwise.

We also have Arch support, maintained by @MorrisJobke (hope you've been keeping up!).

**Comment by MorrisJobke** [comment]
> We also have Arch support, maintained by @MorrisJobke (hope you've been keeping up!).

Sure :) I often just lack a bit behind in time (mostly 1-3 days after the official release) but beside that it's up to date :)

**Comment by andyjeffries** [comment]
Just so you all know, I'm running Dokku from bootstrap on multiple Ubuntu 16.04 machines (because I didn't know it wasn't supported) and it installed and ran/runs flawlessly on all of them.

**Comment by josegonzalez** [comment]
Yeah this is just so the packaging has an "official" url for 16.04 as well as 14.04. We test on 14.04 because thats what our CI runs.

**Comment by fruitl00p** [comment]
We too are now running a few boxes on 16.04 (dokku 0.8.2) and everything works but the SPDY / HTTP2 detection stuff... (nginx by default is 1.10.0)

Should i make a separate issue to get this up to par?
(we have alot of great experience with running the dockerized niginx image `nginx:1.12-alpine` without any issues)

**Comment by josegonzalez** [comment]
SPDY/HTTP2 detection is a bit "flaky" in your case because of broken http2 support, and missing spdy support. Related [issue](https://github.com/dokku/dokku/issues/2435). You'll want to upgrade your nginx to get http2 support.

I'd welcome a documentation PR that clarifies our nginx spdy/http2 support :)

**Comment by manuel-colmenero** [comment]
I found an issue with HTTP2 and nginx/stable (1.12.1) in Ubuntu 16.04. The version detection functions are failing because `ngnix` is not found (because the `dokku` user hasn't `/usr/sbin` in `$PATH`).

Also the `is_http2_enabled` function is checking whether nginx is there which is not necessary, it gets the version passed as an argument, which was obtained by running nginx itself.

Should I send a pull request?

**Comment by josegonzalez** [comment]
Why does your `dokku` user not have that in the path? If the binary that the upstream nginx package installs isn't in your PATH, that sounds like something you may have manually edited. How did you bring up the server?

Also, it does that check because our initial retrieval of the version doesn't check if nginx is installed. I guess we can probably just return false if we can't find a version...

**Comment by manuel-colmenero** [comment]
I got a fresh Ubuntu 16.04 install from [OVH](https://www.ovh.de/virtual_server/vps-ssd.xml) and followed the instructions on the dokku website (those with the "pipe to bash" command).

Also, I didn't edit anything, the only "custom" thing I did was installing nginx 1.12 from their PPA. (Location of the binary is the same, though).

The user `dokku` is not part of the administrators so I guess it's normal that it doesn't have `/usr/sbin` in `$PATH`.

IMHO even if it is because OVH customized their image a little:
- I think relying on `nginx` being in path for dokku to work is somewhat shaky. (Or worse, relying on being the user being an admin).
- I think [that check](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L182) is redundant because `nginx` was called a second ago, _without any checks_. Also, for added redundancy, both `is_spdy_enabled` and `is_http2_enabled` check for the `nginx` binary being in `$PATH`. I know about defensive programming, but is that not a little too much?

**Comment by manuel-colmenero** [comment]
I just cranked up the Vagrant box (checked out a fresh dokku master branch, runned `vagrant up`), and poked around a bit. Seems like the issue persists and version checking is broken there too. I added the following line:

```bash
    local NGINX_VERSION="$(nginx -v 2>&1 | cut -d'/' -f 2)"
# !!!
echo NGINX_VERSION "$NGINX_VERSION"
    local SPDY_SUPPORTED="$(is_spdy_enabled "$NGINX_VERSION")"
    local HTTP2_SUPPORTED="$(is_http2_enabled "$NGINX_VERSION")"
```

And then run `nginx:build-config`

```
dokku@dokku:~$ dokku nginx:build-config frontend
NGINX_VERSION var
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
