### ISSUE TITLE
[RFC] Replace docker binary calls with direct api calls

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2267]
Dokku currently calls the docker binary on the same host whenever communicating with Docker to run commands. This has a few limitations:
- The `docker` cli interface has changed in the past, requiring patches and new releases to support the new interface.
- Dokku can currently only orchestrate docker if it is installed on the same host.
- Dokku package installations have a _hard_ dependency upon the `docker-engine` package, which means there is a bit of fancy footwork to make it happy within a Dockerfile deploy.

@michaelshobbs mentioned that we could communicate directly with the docker api. This would mean a few things:
- We can peg to a specific version of the api as - in theory - the api will not be broken regardless of your docker version.
- We can support systems such as Joyent's Triton or similar that expose a docker-like api.
- We can support remote clients.

There are currently 30 unique direct api calls within the core - not counting documentation, tests, or official plugins. 

There is quite a bit of api stability to be gained here, though updating the core and official plugins to use an internal api wrapper could be a substantial piece of work. Opening this issue for discussion purposes.

**Comment by u2mejc** [comment]
I support this. I had talked to Michael about switching to the API back when I first did a tech demo of dokku on swam, before 1.0. The API back then was, rough. I carry forward the impression that it's still a second class citizen to the CLI, but I think the advantages still outweigh that negative. 

Expanding the advantages mentioned above, a normal stable API should have:
- Machine readable responses, no more crazy bash / regex fu skillz needed. I used one file from another project: https://github.com/ingydotnet/json-bash/blob/master/lib/json.bash which worked really well to build pseudo objects with and then easly reference.
- No local docker client required, and no special dokku_client.sh remote wrapper required anymore

If we implement this as a pluggable abstraction layer, we could allow swapping back ends with other services like ECS, or maybe even Mesos, etc.

Targeting the most recent api version for each release would ensure the most longevity possible if we don't pin to docker client versions. This is not to be beholden to always having to update our code to support any new changes for the sake of change, instead it's because Docker doesn't have an official deprecation cycle published for their API. In addition to that, they haven't to put forth any guarantees that the API won't change inside version (peering into the code makes that more obvious).

**Comment by josegonzalez** [comment]
I'm going to close this. It's unlikely to be worked on - at least until the majority of the docker-related stuff goes into Golang - and the dokku binary api has been relatively stable as of late.

A better bet at the moment is to focus on making "schedulers" a thing, which is something I have an upcoming PR for.
