### ISSUE TITLE
[RFC] Support further commands from app.json

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2269]
### High-level plan

- [x] ~Create a golang project - `go-app-json-util` - that can be used to validate and extract information from an `app.json` file~ Not necessary, we can do this in golang now
- [x] ~Replace our app.json handling for deployment tasks with the above util~ Not necessary, we can do this in golang now
- [x] Create a generic `app-json` plugin that handles the logic around processing the `app.json` file.
- [ ] Add a `post-create` hook that sets `env` based on the `app.json` file's `env` stanza
- [x] Support the `scripts.postdeploy` key by setting an `app-json` property that tracks if the command has been run before.
- [ ] Add a `dokku.datastores` key that can be used to automate creation/attachment of datastores.

Let's avoid adding support for the buildpacks stanza for two reasons:

- Heroku now uses a special `buildpacks` api for this - with an accompanying cli command - and has deprecated other methods. It's unclear what they are doing here, but introducing yet another variable will make it difficult for folks to reason about their app buildpack usage in the long-run.
- Herokuish handles buildpack detection, and I'd rather not introduce another wart in how it does so.

### Original Post

Since Dokku 0.5.0, we have support for application deployment tasks specified under the `scripts.dokku` namespace in an application's `app.json` file. This allows users to run a given task during the pre-deploy and post-deploy plugin triggers. There are a few enhancements we can make to this system:
- Support a list of commands for pre and post-deploy.
- Support the initial environment variable setting that Heroku does with the app.json (under the `env` key).
- Support the initial deploy script that Heroku does with the app.json (under the `scripts.postdeploy` key).
- Support setting buildpacks on the initial deploy (under the `buildpacks` key).
- Support plugin creation/manipulation.

All of the above features need not be implemented at once - and maybe some don't make sense for Dokku - but it's worth discussing out in the open.

A related plugin for dokku in this space is the [dokku-require](https://github.com/crisward/dokku-require) plugin by @crisward, which supports both linking the official service plugins, running arbitrary dokku commands, as well as mounting volumes. I'm not a fan of some of the implementation - e.g. I don't think we should create/link services on every deploy - but it does service as a good proof of concept.

**Comment by crisward** [comment]
It'll be cool to see this feature in core.

The create/link on every deploy I've found useful. If you want to start over it's fairly easy to just delete a database and rebuild. The only other way would be to detect if the database already exists or is linked. It seems the best code to handle that is the database plugin, which they all seem to currently do. 

Out of interest, what is use case for first push only? 
What about a flag to give the user choice.
ie.
```json
"dokku":{
    "plugins":[
      {
        "name":"mariadb",
        "commands":["mariadb:create mydb","mariadb:link mydb $APP"],
        "first_push":true
      }
    ]
  }
```
or
```json
"dokku":{
    "plugins":[
      {
        "name":"mariadb",
        "first_push_commands":["mariadb:create mydb","mariadb:link mydb $APP"],
      }
    ]
  }
```

**Comment by josegonzalez** [comment]
@crisward mostly because i see the app.json as a "setup" format. If you do it each time but edit the env vars, that might make for a sucky experience for users.

**Comment by crisward** [comment]
Good point regarding env.. I'll raise it as an issue on the plugin and have a think of a good way to allow for first deploy only ability. Not sure if env's should be in app.json anyway, but choice would be a good thing.

**Comment by jonathanhefner** [comment]
I really like this proposal.  I'm writing a plugin for my own short-term use that implements some of the things mentioned here.  I'd like to eventually contribute back any features that are appropriate to core, but I have a few questions.  For context, here is what I am implementing:

* Environment variables are set from the `env` stanza.
  * Values can be derived from generators, [as described in Heroku's app.json spec](https://devcenter.heroku.com/articles/app-json-schema#env).  For my plugin, generators must be app commands prefixed with `"!"` (a la git aliases). **(1)**
* Plugins are installed from a `dokku-plugins` stanza.
  * Each plugin can be specified as a String or JSON Object.
  * The String or the Object's `"plugin"` property can either be a git URL or a simple name which is interpolated into `"https://github.com/dokku/dokku-$name.git"`.  **(2)**
  * An Object can specify an `"as"` property (like [addons from Heroku's app.json spec](https://devcenter.heroku.com/articles/app-json-schema#addons)).  Doing so will `create` and `link` the plugin using the name specified. **(3)**
  * An Object can specify an `"install"` property, which is an array of commands that will be executed after install, a la dokku-require's `"commands"`.  **(1)**
* If a DOKKU_SCALE file does not exist, one is created from the [`formation` stanza](https://devcenter.heroku.com/articles/app-json-schema#formation).  **(4)**
* The app's domain is extracted from the [`website` stanza](https://devcenter.heroku.com/articles/app-json-schema#website) and added via `domain:add`.  **(5)**

So my questions are:

**(1)** Can `dokku run` be used at this phase of the life cycle?  My use case for deriving environment variables from generators is running a Rails command which decrypts e.g. AWS credentials which have been encrypted and committed to the git repository.  So the JSON would look something like this:

```json
{
  "env": {
    "AWS_ACCESS_KEY_ID": {
      "generator": "! rails credentials:get aws.access_key_id"
    },
    "AWS_SECRET_ACCESS_KEY": {
      "generator": "! rails credentials:get aws.secret_access_key"
    }
  },

  "dokku-plugins": [
    {
      "plugin": "postgres",
      "as": "pg",
      "install": [ "postgres:backup-auth pg $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY" ]
    }
  ]
}
```

And I want to evaluate `dokku run rails credentials:get ...` to populate the necessary environment variables to run `postgres:backup-auth pg ...` after plugin installation.


**(2)** Is installing a plugin idempotent?  Will trying to install the same plugin a 2nd time be a no-op?  And, if so, is each plugin identified by its full git URL?  (e.g. If a plugin is forked, and the user changes the git URL in app.json to the fork, will the fork be installed?)  Also, is there a safe easy way to clean up plugins that are no longer referenced?


**(3)** What is the proper mechanism to determine a plugin's command namespace?  e.g. The dokku-graphite-grafana plugin uses the `graphite` namespace, instead of `graphite-grafana`.  How can that be programmatically determined to properly invoke `graphite:create` and `graphite:link`?


**(4)** The [documentation about the DOKKU_SCALE file](http://dokku.viewdocs.io/dokku/deployment/process-management/#manually-managing-process-scaling) says "Dokku will always use the DOKKU_SCALE file that ships with the repo to override any local settings."  What does "local settings" mean?  Will implicitly creating a DOKKU_SCALE file hinder the user at some point?


**(5)** Is applying the domain from the `website` stanza a bad idea for reasons I'm not familiar with?  My experience is limited to run-of-the-mill Rails web apps.


(Sorry for the long post! :sweat_smile:)

**Comment by josegonzalez** [comment]
@jonathanhefner mind finding me on the slack channel? This might be easier to discuss via a slack call :) (I'll be sure to get an update here).

Re: your questions:

1. Sure, but not at the moment. My concern here is that this leads to arbitrary code execution on the host. I'd like to be careful about how we expose things. Instead of generator, maybe `command`?
2. Not sure, but don't think so. Regardless, I don't think we should expose plugin installation at this phase, as that requires root (for good reason, the `install` hook is executed as root).
3. The `graphite-grafana` plugin is poorly named, as is the `nginx-vhosts` plugin. Other than that, we should assume that the plugin name matches the namespace.
4. If you use `ps:scale`, a `DOKKU_SCALE` within the repository will currently override it. I don't like the `DOKKU_SCALE` file at all, and would prefer it be something more vendor neutral, but it is what it is.
5. That stanza is meant more for like, if I built an OSS project called `lollipop` and the project's page was `https://lollipop-paintshop.com`. If we want to use the `domains` plugin, we'd need a separate stanza.

**Comment by decentral1se** [comment]
For anyone looking for solutions now, I've been using a combinator of the ansible-dokku ansible roles and https://github.com/decentral1se/dokku-ansible-playbook to provide a lot of my pre-deploy/post-deploy automation logic. The vault is useful to storing secrets directly encrypted in your repostiory which I find to be a big benefit. Definitely would be nice to have a lot of this tucked into the app.json, of course :)

**Comment by josegonzalez** [comment]
Closing in favor of more specific issues.
