### ISSUE TITLE
Pass application name as option instead of argument

### ISSUE THREAD

**Issue by haggen** [dokku/dokku#2321]
Arguments are variable and could be misinterpreted. Options are safer. So instead of this:

    $ dokku ps myapp

We should do this:

    $ dokku --app myapp ps

My use case is: I have written a small script that appends the directory name onto the dokku command, so I can run this:

    ~/myapp$ dokku ps

That it get translated to this:

    ~/myapp$ dokku ps myapp

But I have to be very careful about what commands I execute, for instance, if I simply run `dokku` I get a `myapp is not a valid command` or something like it.

I'd say heroku uses options instead of argument for this very reason.

So, are there any plans to change the CLI signature? Thanks in advance.

**Comment by josegonzalez** [comment]
This exact feature has been available since [0.5.0](https://github.com/dokku/dokku/blob/master/HISTORY.md#050) and is supported in our [official bash client](http://dokku.viewdocs.io/dokku/community/clients/#bash-zsh-etc-dokku_clientsh) by default. You don't need to make your own cli tool to interact with Dokku.

**Comment by haggen** [comment]
Oh gee, how did I miss that. :P Thanks!

**Comment by josegonzalez** [comment]
@haggen I apologize, on irc I said this was available in `0.6.0`, but it was `0.5.0`. In any case, you'll definitely want to run the same version of the client as you have installed on your server, otherwise args can be switched up.

As well, the `dokku` binary will only set the `--app` option when it is executed in a repository with a `dokku` remote.

**Comment by haggen** [comment]
Thanks a lot @josegonzalez!
