### ISSUE TITLE
Running "dokku:ssh-keys add" via dokku_client.sh puts wrong key name

### ISSUE THREAD

**Issue by IlyaSemenov** [dokku/dokku#2368]
Description of problem:

Running `dokku:ssh-keys add` via dokku_client.sh silently puts the app name instead of the key name:

``` console
$ cat gitlab.pub | dokku ssh-keys:add gitlab
SHA256:CuDHNdVnVaN35nwLdaoAfEalepXJ9ispgrLEUeS24iw

root@dokku:~# tail -n1 /home/dokku/.ssh/authorized_keys
command="FINGERPRINT=SHA256:CuDHNdVnVaN35nwLdaoAfEalepXJ9ispgrLEUeS24iw NAME=\"myapp\" ... gitlab
```

Note that `NAME` is set to "myapp" instead of "gitlab".

Running the same command via SSH works fine:

``` console
$ cat gitlab.pub | ssh dokku@dokku.myapp.com ssh-keys:add gitlab
SHA256:CuDHNdVnVaN35nwLdaoAfEalepXJ9ispgrLEUeS24iw

root@dokku:~# tail -n1 /home/dokku/.ssh/authorized_keys
command="FINGERPRINT=SHA256:CuDHNdVnVaN35nwLdaoAfEalepXJ9ispgrLEUeS24iw NAME=\"gitlab\" ... gitlab
```

Output of the following commands:
- `uname -a`: Linux dokku 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `sigil -v`: 0.4.0
- `dokku version`: 0.7.0
- `dokku plugin | grep ssh`: ssh-keys             0.6.4 enabled
- `dpkg -l | grep sshcommand`: ii  sshcommand                         0.5.0                           amd64

**Comment by u2mejc** [comment]
This appears to be a larger regression from here: https://github.com/dokku/dokku/issues/1638

I'm pushing a patch that should fix trace, domains, etc... I don't think we have testing for this since it's inside /contrib/.

Unfortunately, I also pushed another patch earlier which clarifies that keys should be added by root or *admin* (as define by dokku ssh-keys / sshcommand). This means that dokku_client.sh isn't supported for adding keys (simialrly like plugins:* isn't) since the ssh user is always "dokku". 

Please feel free to submit a PR if you'd like to enhance dokku_client.sh futher. I can't speak for the rest of the core contributors, but of note, I've been trying to make all of my contributions work over ssh so you can simply `alias dokku='ssh dokku@dokku.me'`. Using that method instead, you can subsitute for the root user and load keys remotely:
```
$ alias
alias dokku='ssh root@dokku.me dokku'
$ cat ~/.ssh/gce_id_rsa.pub | dokku ssh-keys:add test2
ec:fb:d9:99:13:0f:ca:d6:9a:bb:4b:5c:4e:ca:58:2c
```

**Comment by IlyaSemenov** [comment]
@u2mejc 

> should be added by root or _admin_ (as define by dokku ssh-keys / sshcommand). This means that dokku_client.sh isn't supported for adding keys (simialrly like plugins:* isn't) since the ssh user is always "dokku".

But _admin_ **is** the ssh user "dokku", so I don't see how the former is inferred from the latter. I think it's perfectly fine when _admin_ runs server-wide commands with dokku_client.sh. Like for example, admin can already use dokku_client.sh to run both `dokku config` and `dokku config --global`, and I don't really see much difference in managing global vars vs. global users (or global databases, etc.)

I don't think that dokku_client.sh needs to be enhanced for this matter (how? by hardcoding the list of commands that are knowingly "global"?). Wouldn't it be better if `--app` was supported globally for all commands, probably parsed by the entrypoint, and simply ignored when it isn't needed / doesn't make sense? This is extra coupling, of course, but the concept of "current app" is such a very frequent case that it can receive first-class treatment.

**Comment by u2mejc** [comment]
@IlyaSemenov Thank you, you're correct. Convention is a little confusing here, but system user vs sshcommand's user name. The ssh user is `dokku` and does own the authorized_keys file. I can't remember what the web gui sets the first sshcommand user as (I think it's admin, but I'm also hoping to deprecate that web gui in favor of documenting how to use ssh-keys:add).

I also agree, I hate white/black listing certain commands. To clarify the original issue, the app name from the local repo (being passed as the prepended argument `--app <name>`) isn't properly handled by _all_ of the core plugins. We could update the core plugins to all support the prepended argument. `parse_args` could check if the plugin is found in core and pass the app name, if not, it would shift the arguments (dropping the app name from the beginning.)

Beyond just privilege escalation reasons, the other reason root is required for ssh-keys:add is the dokku user can't read the local user's key file. The root / admin check at https://github.com/dokku/dokku/blob/master/dokku#L65 can simply get a ` && -z "$2"` which allows dokku_client.sh to pass keys again for `*admin*` users. Obviously the remote server can't read local files on your desktops so dokku_client.sh would need to be updated to pipe keys found as arguments.

Before we go much futher, @michaelshobbs @josegonzalez should I continue to kick along dokku_client.sh or how do you feel about updating the documentation to alias dokku over ssh? (fyi this is how I use it and catch the tty errors from time to time.)

**Comment by josegonzalez** [comment]
Web gui uses `admin` as the user.

I would keep updating `dokku_client.sh`. We don't often add new core commands and can take them into account when updating the whitelist in the client.

**Comment by IlyaSemenov** [comment]
> We could update the core plugins to all support the prepended argument.

That would be perfect, and would resolve the actual problem described in this ticket.

> Obviously the remote server can't read local files on your desktops so dokku_client.sh would need to be updated to pipe keys found as arguments.

`dokku ssh-keys:add` already supports receiving keys via the pipe, so I don't see a problem here. Moreover, I personally think it's better if dokku_client.sh is kept as thin as possible and doesn't get bloated with patches for specific commands unless absolutely necessary.

**Comment by u2mejc** [comment]
>`dokku ssh-keys:add` already supports receiving keys via the pipe, so I don't see a problem here. Moreover, I personally think it's better if dokku_client.sh is kept as thin as possible and doesn't get bloated with patches for specific commands unless absolutely necessary.

Ah, let me explain.

The `dokku ssh-keys:add` command is expected to be run locally. The help text is static if you run `dokku` on the server directly or remotely via `dokku_client.sh`. If I use `dokku_client.sh ssh-keys:add foobar /Volumes/Macintosh\ HD/tmp/my_key.pub` as passed path (without piping, because the dokku help told me I could), I would not get the expected result (from the user's standpoint). Hence the dokku_client.sh would need to be updated. I would like to keep the file path support and not force piping (believe it or not, not every dokku user understands what pipes are).

I wonder aloud if anyone would complain if I just strip the guts of dokku_client.sh, just made it pipe to ssh and fix any dokku commands that can't handle it so that tests passed. I think I'll create a branch to demonstrate it tonight.

**Comment by IlyaSemenov** [comment]
> I would not get the expected result (from the user's standpoint).

Not if dokku_client.sh was clearly documented to be a **thin** wrapper that only checks "git remote" to discover the host and the app name and intentionally not trying to be any smarter than that. Everyone knows that abstractions leak, so why not let it leak when it's expectable and justifiable (as with referring local resources vs. remote resources)? `ssh-keys:add` is not the only command that leaks this way, it's also `certs:add` and probably others.

Essentially, the overall problem can be generalized as "What dokku_client.sh is *supposed* to be, and thus where its development is headed?" [The documentation](https://github.com/dokku/dokku/blob/master/docs/community/clients.md) doesn't really tell that, hence the misunderstanding.

**Comment by josegonzalez** [comment]
As I commented in the pull request @u2mejc made, I think the proper thing is to move the blacklist to the `dokku` bin. That way it's kept up to date with the rest of the codebase. Community plugins would then be unaffected, and this reduces complexity in the `dokku_client.sh`.

**Comment by josegonzalez** [comment]
Closing as #2557 is up.
