### ISSUE TITLE
Can't deploy when using git-lfs

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2401]
```
alex@P-Wing:~/Projects/testapp$ git push dokku master 
Git LFS: (0 of 41 files) 0 B / 58.27 MB                                              
batch request: exit status 128
error: failed to push some refs to 'dokku@example.com:testapp'
```

I've tried shelling into the server and installing [git-lfs](https://git-lfs.github.com/) to no avail. Surely if the Dokku user had access to it, it would work right?

Thanks all. If you need to see info about my server, see #2400

[More info](https://github.com/github/git-lfs/tree/master/docs/api) about the git-lfs API.

**Comment by alexgleason** [comment]
After a bit of research I've found that git-lfs expects there to be an API it can talk to at `https://dokku@example.com/testapp.git/info/lfs`

This must implement the [spec](https://github.com/github/git-lfs/blob/master/docs/spec.md).

A workaround is to ignore git LFS when pushing to Dokku with `git push dokku master --no-verify`, but this will result in all the LFS-tracked assets simply not appearing at all, which isn't desired. My website has a bunch of broken/missing images.

I've instead written a script to make a copy my directory without git-lfs and force push it to Dokku. Also not ideal but it works at least.

Can Dokku support git-lfs?

**Comment by josegonzalez** [comment]
Dokku does not run any persistent daemons of any kind, so at the moment it's a bit out of scope.

I'd also argue that this isn't necessarily a common use case - even [Heroku doesn't support it](https://devcenter.heroku.com/articles/git#deploying-code) - so I'm going to close this.

If you'd like to sponsor the development of this functionality, please do so with a monetary contribution [here](https://opencollective.com/dokku?utm_campaign=dokku&utm_medium=github&utm_source=opencollective#support)

**Comment by alexgleason** [comment]
@josegonzalez Open Collective looks really cool. I was expecting you to direct me to something like Bountysource. Is there a way to put money towards a feature?

Thanks for the info. I'm surprised Heroku doesn't support git-lfs. It's a shame there's no easier way around this, because Dokku doesn't need to care about pulls, it just needs to have the files when they get pushed.

Thinking out loud, but I don't think it needs a daemon? I bet you could use a plugin to allow `dokku git-lfs myapp`, which would create a new Docker image containing an implementation of the lfs spec, automatically serve it on `https://example.com/dokku/myapp.git/info/lfs` with the proper ports open, then when an repo is pushed with LFS it will authenticate with that container and send over the files. Then Dokku would connect to the container and download the files when it receives code.

I think we would need to build a Docker container implementing the LFS API and then create a Dokku command that creates them and then hooks into the deploy process to download the files.

**Comment by josegonzalez** [comment]
I'm going to lowball myself and say this is ~20 hours of work, and my normal freelance rate is $150 an hour, so a 3k donation would be needed to support this functionality. If I saw a sponsorship somewhere in that range, I think I'd know what the money is set aside for ;)

It needs to be something persistent, so probably a docker container with a git-lfs api running with the files mounted from disk. Would also require *not* using that domain to host an app on the push domain, assuming the container is running through dokku. Finally, you'd need to ensure you could hit the git-lfs api from both internal and remote, since I assume the server's local git command needs access to this api.

When I say daemon, I mean something that is running constantly. Dokku is merely a command that gets executed by sshcommand, and is only really triggered on push.

**Comment by josegonzalez** [comment]
As an aside, if the above seems incredibly off-putting, I apologize. If this were clearly under the purview of Dokku, I'd be happy to work on it - and probably for free! - but given the need for it, what other players in the space are doing, and the complexity involved, I feel less bad about asking for "market rate". Please don't take this personally, I'd probably respond the same way for any other similar issue.

If you're interested, I'd also be happy to help work with you on a separate plugin/extension/app that builds out this functionality as OSS. I'm available on our slack/irc as `savant` if you'd like to chat further online. However, I think at most this would be an official plugin, and not in dokku-core itself.

**Comment by alexgleason** [comment]
No worries, not at all off-putting. I'm kind of a communist and I dream of a moneyless society where everyone just does what they want. Unfortunately we still exist in this system of capitalism, so we have to live somehow. I struggle with this daily. It's like I have a life of making websites I don't care about and then a separate life of writing free software.

If I have more problems needing to deploy git-lfs I'll take a stab at writing a Dokku plugin. It wouldn't be my first. But I haven't been able to contribute code as much lately because I just went into freelancing myself and I'm trying to start a web collective. I'm asking $60/hr in Philadelphia and getting turned down, so let me know if you ever want to work together. I'm a pretty good developer so I guess it's a matter of knowing the right people.

**Comment by CQCumbers** [comment]
I have several services I would like to deploy to dokku that use git-lfs, especially some 3D rendering and deep learning projects. I understand that lfs is a narrow use case, but is there any sort of workaround available if I need the tracked files to be copied to the server? Everything I've tried seems to push lfs pointers to dokku instead of the actual files.

**Comment by jcrben** [comment]
@alexgleason maybe you you could share the script you use as a workaround. git-lifs is not essential for my app but was trying it out in one of my apps and noticed this issue. not sure what you mean by copying the directory and force-pushing since it seems like you'd need to commit these files for them to actually get pushed right? so have a temporary repo where you commit and push that?
