### ISSUE TITLE
certs:info plugin command mis-claims self-signedness

### ISSUE THREAD

**Issue by owlvark** [dokku/dokku#2421]
The last line in the output of `dokku certs:info <app>` states the certificate is self-signed when it is really one that is validated by a certificate authority.

Output of the following commands
- `uname -a`: Linux ip-xxxxxx 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: Mem:           992        778        214          2        169        306
  -/+ buffers/cache:        302        689
  Swap:            0          0          0
- `docker version`: Client:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:        Thu Aug 18 05:22:43 2016
  OS/Arch:      linux/amd64
- `docker -D info`: Cannot connect to the Docker daemon.
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`: docker: Cannot connect to the Docker daemon.
- `dokku version`: 0.7.1
- `dokku plugin`: plugn: dev
  00_dokku-standard    0.7.1 enabled    dokku core standard plugin
  20_events            0.7.1 enabled    dokku core events logging plugin
  apps                 0.7.1 enabled    dokku core apps plugin
  build-env            0.7.1 enabled    dokku core build-env plugin
  certs                0.7.1 enabled    dokku core certificate management plugin
  checks               0.7.1 enabled    dokku core checks plugin
  common               0.7.1 enabled    dokku core common plugin
  config               0.7.1 enabled    dokku core config plugin
  docker-options       0.7.1 enabled    dokku core docker-options plugin
  domains              0.7.1 enabled    dokku core domains plugin
  enter                0.7.1 enabled    dokku core enter plugin
  git                  0.7.1 enabled    dokku core git plugin
  logs                 0.7.1 enabled    dokku core logs plugin
  named-containers     0.7.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.1 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.1 enabled    dokku core plugin plugin
  proxy                0.7.1 enabled    dokku core proxy plugin
  ps                   0.7.1 enabled    dokku core ps plugin
  repo                 0.7.1 enabled    dokku core repo plugin
  shell                0.7.1 enabled    dokku core shell plugin
  ssh-keys             0.7.1 enabled    dokku core ssh-keys plugin
  storage              0.7.1 enabled    dokku core storage plugin
  tags                 0.7.1 enabled    dokku core tags plugin
  tar                  0.7.1 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.): AWS

How was Dokku installed?: bootstrap.sh

How reproducible: always happens

Steps to Reproduce:
1. install cert with `dokku certs:add <app> CRT KEY`
2. run `dokku certs:info <app>`

Actual Results:

```
-----> Fetching SSL Endpoint info for xxxx...
-----> Certificate details:
=====> Common Name(s):
=====>    xxxx.com
=====>    xxxx.com
=====>    dev.xxxx.com
=====>    www.xxxx.com
=====> Expires At: Jul 18 12:00:00 2017 GMT
=====> Issuer: C=US, O=DigiCert Inc, CN=DigiCert SHA2 Secure Server CA
=====> Starts At: Jul 13 00:00:00 2016 GMT
=====> Subject: C=US; ST=xxxx; L=xxxx; O=xxxx Inc.; CN=xxxx.com
=====> SSL certificate is self signed.
```

Expected Results:

```
...
=====> SSL certificate is verified by a certificate authority.
```

Additional info:
Note that Nginx is completely happy with the supplied server.crt and web browsers report the website https is "verified by DigiCert Inc".
It appears the plugin determines self-signedness with the line:

```
    local SSL_VERIFY_OUTPUT="$(openssl verify -verbose -purpose sslserver "$APP_SSL_PATH/server.crt" | awk -F ':' '{ print $2 }' | tail -1 | xargs || true)"
```

When I run `openssl verify -verbose -purpose sslserver /path/to/server.crt` I get:

```
error 20 at 0 depth lookup:unable to get local issuer certificate
```

A little digging indicates that the intermediate cert should be passed to `openssl verify` with `-CAfile intermediate.crt`, but I'm not sure how feasible that is as what would be the intermediate.crt is in the server.crt file.

**Comment by josegonzalez** [comment]
I think this is actually that your certificate does not include the intermediate cert file, and as such is actually not well-formed. I had a similar issue in production recently and it turned out that the downstream provider had not included the intermediate cert (and also blamed my systems for not being able to properly verify ssl on his).

I think Dokku is doing the right thing here. While we might be able to "warn" of a misconfiguration, I think the fact that the report output says something you don't expect should be a clue as to the fact that the provided cert isn't correct.

**Comment by stephenhowells** [comment]
I've tried to install two separate SSL certs that I've bought in the past few months from two separate certificate authorities and I am completely certain that I included the intermediate certs exactly as the Dokku documentation states. Yet, I too get the same `error 20 at 0 depth lookup: unable to get local issuer certificate` message. Chrome states that the certificate is valid and trusted when I visit the domain in the browser.

If I manually verify using the individual root, intermediate, and domain certs it works just fine:

```bash
$ openssl verify -CAfile ca.crt -untrusted intermediate.crt server.crt
server.crt: OK
```

While Googling the issue it states the error arises because the local copy of the root CA certificate is not in the trusted certificate store. Instructions on how to install the root CA into the local trusted store are unclear and don't work, at least not on an Ubuntu 18.04 VPS on AWS. I have to imagine that nearly everybody who tries to use a purchased SSL with Dokku gets erroneously greeted with the error that its self-signed. I think it's worth reopening this issue. The command `openssl verify -verbose -purpose sslserver "$APP_SSL_PATH/server.crt"` is problematic as @owlvark pointed out.

**Comment by stephenhowells** [comment]
I'm happy to submit a PR but my only idea is to maybe include the root CA cert in with the `.crt` and the `.key` as a third file required but that feels a bit clunky. ¯\_(ツ)_/¯

**Comment by josegonzalez** [comment]
Pull requests are always welcome.

**Comment by yegor256** [comment]
@josegonzalez can you please re-open this? The problem is not solved and it's not clear what is the solution? Where exactly should I add the intermediary certificate? I tried `/etc/ssl/certs` directory, but it doesn't help.
