### ISSUE TITLE
Setup is too confusing!

### ISSUE THREAD

**Issue by john-doherty** [dokku/dokku#2455]
**Please** can someone write a quick, bullet pointed list of the steps required to go from nothing _(no dokku instance)_ to a git push? 

For example:

1. Create a droplet using Dokku under One-click apps
2. From your terminal, execute `ssh ...`

I've burnt many hours trying to setup a dokku instance so I can *git push* a ghost node app but failed. From reading the list of github issues, I'm not the only one. This could be resolved with a simple, to the point list of steps.

**Comment by jvanbaarsen** [comment]
Not really sure if you used google. But I googled it for you: https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-dokku-application

**Comment by john-doherty** [comment]
Thanks @jvanbaarsen, did you follow the steps too? Or did you skip right past:

**"Note: The Dokku project has changed significantly since this guide was written. The instructions below may not reflect the current state of the Dokku project."**

At the top of that article?

**Comment by josegonzalez** [comment]
This is available on our official documentation in a few places, in various states of detail (though all functionally complete):

- The [readme](https://github.com/dokku/dokku#installing)
- On our [homepage](http://dokku.viewdocs.io/dokku/) (for various platforms, methods)
- On the getting started [page](http://dokku.viewdocs.io/dokku/getting-started/installation/)
- Advanced installation for various [platforms and methodologies](http://dokku.viewdocs.io/dokku/getting-started/installation/#installing-via-other-methods)

We've taken feedback from quite a few github issues to clarify our documentation/hunt down bugs, so if there is something that is still unclear, I'd be happy to hear about it so that we can further improve our installation user experience. Please feel more than welcome to jump on our [IRC or Slack](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels) rooms.

As far as tutorials online, while I cannot comment on every single tutorial, I briefly read through the one posted by DigitalOcean and it seems more than adequate. I asked them to place that disclaimer in case a user is having issues - I'd rather the DO people *not* be blamed by a small change in the installation method - though I know that our contact at DO has been quite good at keeping it up to date. I'll reach out and have them remove the disclaimer and also update it with a more detailed version that I've personally vetted.

Hope that helps.

**Comment by john-doherty** [comment]
@josegonzalez I did follow the [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-go-app) before opening this issue but was unable to get it working. I then followed a series of stack overflow posts with no luck. I also found [this post from 2014](https://github.com/dokku/dokku/issues/663) reporting the same issues. 

I appreciate this is an open source project and I would be more than happy to contribute a "How to" guide, if only I could figure out "how to" ;)

Something to be aware of is the lack of stable documentation increases the barrier to entry for many, which in turn risks the success/adoption rate of the project - which is a shame because it's a fantastic solution.

**Comment by josegonzalez** [comment]
@john-doherty I'm sure you actually didn't follow the tutorial to the letter as you said. There are a few things our users mess up:

- Adding multiple keys to the image when booting on DO (known bug, filed and fixing)
- Not using the correct user (`dokku`) for the remote host
- Not running the web installer after booting the image
- Attempting to add their ssh key directly without using `sshcommand` or our helper `dokku ssh-keys:add` wrapper

As I mentioned before, we have pretty good documentation on our site. I can't really comment on blogs and tutorials on other sites, though I've endeavored to have those updated. You really should jump onto our [IRC or Slack](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels) so we can help figure out what step you missed. I highly doubt the DO tutorial is missing a step, but I'm willing to concede that I could be wrong.

Feel free to contact us via those two support forums and we'll see what we can do to help solve your issues.

**Comment by john-doherty** [comment]
@josegonzalez I finally managed to figure out "How To" by visiting the IRC chat as you suggested. 

As promised, I've documented [How to git push to a Dokku Droplet from a Mac](https://gist.github.com/john-doherty/81d9b98f9cf566c0da235f4c1c32fb98) in the hope that it will help others.

Thanks for your support!

**Comment by josegonzalez** [comment]
Okay, so @michaelshobbs and I discussed your issue (I didn't know that was you) and the two things you didn't do correctly were:

- manually added keys to authorized_keys
- using root for the remote user

The former shouldn't be necessary, as you added your key via the web panel (I assume) if you followed the DO tutorial. There is a known issue if you add multiple ssh keys to your webserver where the web ui will handle it improperly, which may be something you ran into.

For the second, they actually have the correct remote.

I'd be interested in seeing you go through just the DO tutorial and figuring out if you hit the first problem, or if you saw another issue entirely. Feel free to hit us up on chat.

Regarding your tutorial, would probably be better if you either:

- reached out to DO and had them update the tutorial to your specs
- added the bits you think our docs are missing to the various places where we show users how to install dokku.

**Comment by john-doherty** [comment]
@josegonzalez I'd be happy to review the docs once I have everything working and clear in my head, it's quite the learning curve. 

Unfortunately, although I'm now able to `git push dokku master` I keep getting ` [remote rejected] master -> master (pre-receive hook declined)  error: failed to push some refs to ...` errors.

I've followed the suggested solution to similar issues raised on github which resulted in [an update](http://dokku.viewdocs.io/dokku/getting-started/upgrading/#upgrade-instructions) but it's not working for me :(

**Comment by josegonzalez** [comment]
Can you hop on chat so we can see whats going on here?
