### ISSUE TITLE
Official Dokku Neo4j Plugin

### ISSUE THREAD

**Issue by diwu1989** [dokku/dokku#2473]
Will you consider adding an official dokku Neo4j plugin?
It's very useful for any kind of graph based application.

**Comment by josegonzalez** [comment]
As mentioned in [this tweet](https://twitter.com/dokku/status/781244096606154752), if you'd like a custom service plugin, please message me directly - slack/irc works, I am `savant` on both - to start commissioning that service. Otherwise, we're unlikely to provide an official integration for a new datastore.
