### ISSUE TITLE
Orphaned containers not cleaned up after unclean reboots

### ISSUE THREAD

**Issue by CherryDT** [dokku/dokku#2482]
Due to unfortunate circumstances (unclean reboots, one of them having Docker not started), it happened a few times that Docker was interrupted before deleting some of its temporary containers. It would be good if there were a way to clean them up with a command.

`dokku cleanup` does nothing for those, so as a workaround I use this command to clean all containers which are old and either have the `random_words` form or the `something.1234567890` form.

```
docker ps -q --format={{.Names}} | grep -P '^\w+$|\.\d{10,}$' | xargs docker rm -f
```

### Debug info
```
ubuntu@ip-172-31-14-40:~$ uname -a
Linux ip-172-31-14-40 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-14-40:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1998         798         592          35         607        1087
Swap:             0           0           0
ubuntu@ip-172-31-14-40:~$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
ubuntu@ip-172-31-14-40:~$ docker -D info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 206
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 247
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-14-40
ID: NNPG:RC22:ADXA:2TRA:MNFY:MZQM:ZY5I:YA4F:4OGK:RSRL:CPDR:HC4K
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
ubuntu@ip-172-31-14-40:~$ sigil -v
0.4.0
ubuntu@ip-172-31-14-40:~$ docker run -ti gliderlabs/herokuish:latest herokuish version
herokuish: 0.3.18
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v81
  heroku-buildpack-java      v44
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v109
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v5
  emberjs.tgz                latest
ubuntu@ip-172-31-14-40:~$ dokku version
0.7.2
ubuntu@ip-172-31-14-40:~$ dokku plugin
plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.2 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  repo                 0.7.2 enabled    dokku core repo plugin
  secure-apps          1.0.0 enabled    secures an application using basic authentication
  shell                0.7.2 enabled    dokku core shell plugin
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
ubuntu@ip-172-31-14-40:~$
```

It's on an AWS EC2 t2.small instance.

**Comment by josegonzalez** [comment]
To be clear, this user's docker didn't start properly - a docker issue, not dokku, and should be reported upstream - causing our `dokku ps:restore` which happens on boot to not run. That would have obviated any need for `dokku ps:restartall` to be manually run.

As far as the docker issue is concerned, I'm fairly confident that the user upgraded their kernel but didn't install the related `aufs` module, so a reboot caused it to use the new kernel without aufs, causing docker to fail to start because the setup was different from what it expected.

**Comment by CherryDT** [comment]
I didn't upgrade anything manually, maybe something was upgraded automatically...?

Anyway, what is strange is that I get the same situation with messed up domains every time when I reboot (even though now the AUFS is installed and docker is started by its own)... But good to know that `ps:restore` would be the right way...

**Comment by josegonzalez** [comment]
You probably have unattended-upgrades setup (not something dokku does).

Can you check to see that there is a `systemd` file for the `ps:restore` call? Logs from it's run would be useful as well.

**Comment by CherryDT** [comment]
I have edited the issue to be more clear and remove the unnecessary part. Mysteriously, it works now, though (the container restore), even though it didn't work on the second reboot either, but on all afterwards.

I don't have logs from the `dokku-redeploy` task though, because persistent journals were not enabled and now it looks OK.

**Comment by josegonzalez** [comment]
Hmm looks like there are two cases where we are not labeling containers with a `dokku` label:

- when outputting the installed `herokuish` version
- when calling `docker build` for a dockerfile deploy

The former doesn't matter since we run it with `--rm`. The latter, however, doesn't remove intermediate containers, so they are apparently left behind.

@CherryDT would you happen to know if only Dockerfile apps are affected here? If so, then we can at least cut out those docker-named containers.

I'm curious about the others with the numbered extensions, as we should be labeling *those* properly. If you can get the docker inspect for the containers - specifically if they are running and what labels they have - that would be useful to dig further into the problem.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in a few months.

**Comment by CherryDT** [comment]
This slipped under my radar. However I don't want to mess with the server at the moment... I could set up a new one and play with it but I don't have time for that either...sorry

**Comment by josegonzalez** [comment]
I've looked again, and actually I cannot find a case where we aren't labeling things properly. Without seeing more logs/inspect output from dangling images, there isn't much I can do here.

This is working fine on all systems I've installed Dokku on.

**Comment by freddi301** [comment]
Hi,
I have same issue, restarting width `reboot` command, i get `appname.123456789` containers along with the actual `appanme` container, and they keep duplicating on every reboot.
All the conatiners are running the webapp correctly, even those with numreic suffix.
This is bad because if `dokku ps:stop appname` it stops the `appname`  container, but htose with suffices keep working, keep drawing resources and does not permit me to fallback by IP in DNS to another machine.
let me know what logs do you need @josegonzalez

**Comment by josegonzalez** [comment]
Part of this is due to a bug where docker doesn't respect restart policies on boot. The other is that they also don't keep IPs/Ports on boot. A partial fix will be [this](https://github.com/dokku/dokku/issues/2403).

If you'd like to contribute to the fix, awesome. Otherwise, you're just going to have to deal with it by stopping those apps and calling `ps:rebuildall` after you've rebooted the box.
