### ISSUE TITLE
Clarification of restart policies

### ISSUE THREAD

**Issue by chiedo** [dokku/dokku#2643]
I'm a little confused as to what the purpose of restart policies are.

I've been deliberately crashing my apps after setting a restart policy of always.

The docker container is restarting as I can see the container when I run `docker ps` but my web process is still not reachable (nginx returns a 502 error).

When I manually run `dokku ps:restart` every thing is working as it should.

I've tried this on multiple node apps.

Am I misunderstanding how dokku restart policies are supposed to work or is something broken?

**Comment by josegonzalez** [comment]
Does the IP change for the service? If it does, we're being bitten by yet another issue created by the whole docker networking fiasco.

In this case, we'd almost certainly need to setup a daemon to listen to the event stream to rebuild nginx configs whenever the process gets restarted.

See #2403 for more information.

**Comment by chiedo** [comment]
Yep, that's it. It's the IP change... I'll follow the conversation on issue #2403

**Comment by rvalyi** [comment]
Hello. First I was a bit scared when I read this. So I tried killing my process inside the docker container by doing something like ```docker exec sha1_of_container ps -aux``` to see what are the processes. Then I ran ```docker exec sha1_of_container kill -9 process_id```. I could observe that the docker restart policy does work here: when it's set to always then the process is properly supervised by Docker and properly restarted with a new id. During this test, the docker container stays the same with the same ip and it is still reached by Nginx as expected.

So @chiedo I wonder what exactly did you do to crash your process and observe an IP change of the container? As far as I can see it seems to work for me but may be I just tested it naively.

**Comment by chiedo** [comment]
Hey @rvalyi

Its hard to reproduce as it only happens sometimes.

Where I've seen it happen the most though is when running `sudo reboot`

**Comment by rvalyi** [comment]
@chiedo thank you for having clarified this. I totally understand that rebooting will bring us in the limitations described in https://github.com/dokku/dokku/issues/2403. Now this is something different than bare process supervision. This is more related to reboot or possibly the death of some container. I`m not sure under which circumstances a container may die instead of only the process inside it. But as far as the process inside the container is concerned the Docker supervision with its restart policy seems to work and it avoids the container to die when the contained process dies. So for instance the attempts to put monit or other supervisors inside the Docker container itself seems useless to me as Docker itself seems to do the job pretty well. Now sure we still need something for accidental reboots but fortunately it tends to happen much less than web apps failures.

**Comment by josegonzalez** [comment]
Docker no longer guarantees that networking info will stay the same across restarts of a container, which is what this issue was about. We'll solve it by implementing the solution in #2403.
