### ISSUE TITLE
Wishlist / Request for Guidance: Routing non-HTTP traffic

### ISSUE THREAD

**Issue by callahad** [dokku/dokku#2662]
More and more I find myself wanting to run things that aren't necessarily talking HTTP.

__What I Want:__

- Two TLS-secured services exposed on two different vhosts:
    - Taskwarrior speaking a custom protocol over port 53589.
    - ZNC speaking both IRC and HTTP over port 6697.
- Connections are only allowed to the correct vhost/port combination:
    - `taskd.example:53589` and `znc.example:6697` are both accepted.
    - `taskd.example:6697` and `znc.example:53589` are both rejected.

Clients send SNI data, so it should be possible to route the incoming connections before TLS termination. Termination could be performed by Dokku or by the applications themselves.

__Nice to Have:__

- Certificates and their renewal (Let's Encrypt) are managed by Dokku.
- All of the `proxy:*`, `domain:*`, etc. commands work as normal.

 As far as I can tell, this isn't currently possible.

1. Am I mistaken?
2. What would need to happen for Dokku to support this use case?
3. Would any of the existing commands need to be changed? How so?
4. If I want this to be supported in upstream Dokku, would it be better to extend nginx-vhosts using the TCP/SNI routing features available in Nginx 1.11.5 (released last October, not yet in the Nginx Stable channel), or would it make more sense to somehow switch over to Haproxy, which has supported this kind of routing since 1.5.0 (in Debian Stable and CentOS 7, but not in Ubuntu 14.04 LTS).

...I guess I'm asking for a spec that I or someone else could attempt to implement. Thoughts?

**Comment by josegonzalez** [comment]
You need a tcp proxy of some sort. The common use for dokku is for web applications, and thus we don't support this at the moment. I'm not sure what the nginx changes would look like for us - tcp stream "vhosts" must be included under the `streams` block instead of `http`, and they also don't support hostnames (because the proxying happens at the TCP level, before nginx can check on the request's hostname). Thus, TLS encryption would likely have to be reworked, and domain management just isn't possible (at least not afaik).

The proxy protocol should support it just fine, as it's just `scheme:host-port:container-port`, so you could imagine `tcp:1234:1234` being something that nginx "knows" how to route.

There is this [haproxy plugin](https://github.com/tasanakorn/dokku-haproxy), but it doesn't understand the new proxy scheme stuff. Probably worth implementing - I made a PR yesterday to it to add support for understanding when we want to switch to it vs another proxy implementation.

**Comment by josegonzalez** [comment]
Closing. The proxy plugin allows developers to create their own proxy implementations, and I think our usage of `nginx` is just fine here in its current settings, as it covers the 80% case.
