### ISSUE TITLE
Moving dokku containers to new host

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#2794]
What is the recommended approach to moving an active dokku container (ie: redis/rabbit) that may have data into it to a new host without any data loss?

**Comment by joshmanders** [comment]
Is it using the official dokku-redis plugin? If so use the backup/export commands on old server, and import command on new server.

**Comment by josegonzalez** [comment]
Service plugins such as redis/rabbit should be brought up new on the new host with whatever config necessary - queues, exchanges, bindings, users - and then the application pointed at that new host.  You can then bring up a copy of the app to drain the old services of any data. You may also use a service-specific tool - such as rabbitmq shovels - to move data around.

For datastores such as mysql or postgres, you can look into the primary/follower pattern as it pertains to the datastore. We don't support multi-node setups out of the box, so that will need to be custom. You may also wish to schedule downtime to move that data over.
