### ISSUE TITLE
Git push to remote over HTTPS (using git-http-backend)

### ISSUE THREAD

**Issue by davecap** [dokku/dokku#2947]
I'm not sure if this is already supported, but is it possible to hook up Dokku to receive git pushes through git-http-backend (with nginx and fcgiwrap)? It might be possible to hook up the core git plugin functions to git-http-backend. There would also need to be another auth methanism (basic auth) which could be provided by a Dokku plugin. The main use case for this for organizations that block port 22 outbound. Github and Heroku both support HTTPS-based git push.

**Comment by sam3d** [comment]
I'm afraid this is not currently possible.

However, if you're looking to circumvent an outbound port 22 block it might be worth [changing the server port for ssh](https://uk.godaddy.com/help/changing-the-ssh-port-for-your-linux-server-7306) so that, at least as a temporary measure, you have a way to deploy within your organisation.

I've ended up using my phone's data connection for dokku deploys before!

**Comment by josegonzalez** [comment]
While this is not currently possible, if you have a potential enhancement, we'd definitely be interested in taking a look.

**Comment by davecap** [comment]
Thanks, I did try the alternative port method but the other ports were also blocked :) In the end, for this particular case, we were able to set up a host-specific proxy on port 22.

**Comment by josegonzalez** [comment]
Closing this as it's something users can setup via something like [this guide](https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP), but isn't something that is needed by the majority of our users.

**Comment by josegonzalez** [comment]
For anyone landing on this issue, the following repository exists and has been tested with Dokku. For now, it is an unofficial project: https://github.com/dokku/git-http-backend
