### ISSUE TITLE
Port mapping with EXPOSE docker instruction doesn't work

### ISSUE THREAD

**Issue by ston3o** [dokku/dokku#2970]
Description of problem
---

Documentation say "If ports are specified via EXPOSE in your Dockerfile, we will proxy requests to the first port specified. Your application must be configured to listen on that port."

The port binding doesn't work for me even with EXPOSE instruction.

Here my `dokku report` : http://sprunge.us/WUBX

How was Dokku installed ?
---

`apt-get install dokku`

How reproducible
---

Steps to Reproduce:

```bash
docker pull ghost
docker tag ghost dokku/ghost
dokku apps:create ghost
dokku domains:add ghost ghost.mydomaine.com
dokku deploy ghost
```

Actual Results
---

502 (Bad Gateway) with error message "We're sorry, but something went wrong."

DOKKU_NGINX_PORT=80
DOKKU_PROXY_PORT_MAP=http:80:5000
PORT=5000

Expected Results
---

DOKKU_NGINX_PORT=80
DOKKU_PROXY_PORT_MAP=http:80:2368
PORT=2368

**Comment by josegonzalez** [comment]
Can you show the output of a deploy after running the command `dokku trace on`?

As well, that isn't the workflow for deploying an image. You should be using `dokku tags:deploy`, as mentioned [here](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-from-a-docker-registry).

**Comment by ston3o** [comment]
@josegonzalez Now I have a different result with `dokku tags:deploy` command : 

```
DOKKU_DOCKERFILE_PORTS=2368/tcp
DOKKU_NGINX_PORT=80
DOKKU_PROXY_PORT_MAP=http:80:5000
PORT=2368
```

Expected result : `DOKKU_PROXY_PORT_MAP=http:80:2368`

Here the output of `dokku tags:deploy ghost` command : http://sprunge.us/IXHT

**Comment by josegonzalez** [comment]
Ah okay, so what happens here is that when you run:

```
dokku domains:add ghost ghost.mydomaine.com
```

That sets the port map. We don't override that in _any_ case, so what you're seeing is the defaults taking over. If you skip that, then we pull the exposed ports and would set the mapping like so:

```
DOKKU_PROXY_PORT_MAP=http:2368:2368
```

We will *never* use port 80 as the host port if we detect the dockerfile/image has a specific port exposed. This was because it was confusing many of our raw dockerfile users who specified ports for a reason.

The fix here is just better documentation around port handling. I'll see if I can split out all those docs into one cohesive page.
