### ISSUE TITLE
Warn before changing nginx configuration

### ISSUE THREAD

**Issue by NiklasRosenstein** [dokku/dokku#2988]
I feel like dokku could have given me a little warning before it is going to delete all my configuration files in sites-available during the installation. :see_no_evil:

**Comment by josegonzalez** [comment]
It would if we touched that directory. We don't even reference sites-available.

**Comment by NiklasRosenstein** [comment]
But, after I ran the dokku boostrap.sh, my sites-enabled directory was empty. Maybe something causes the files to be deleted implicitly?

**Comment by josegonzalez** [comment]
We literally have no references to either sites-available or sites-enabled. Dokku uses neither directory. Maybe the installation of nginx removed the contents?

In any case, this isn't a Dokku bug.

**Comment by NiklasRosenstein** [comment]
Does dokku bootstrap reinstall nginx even if it is already installed?

**Comment by josegonzalez** [comment]
Oh actually we touch `sites-enabled` - guess github's search didn't pull this up - in the `preinst` step. This originated [here](https://github.com/dokku/dokku/commit/a9e0a7b57ed7eff49c4c86fdafbf666585a41b00), but we don't actually run the above for `rpm` installs. My guess is that existing stuff conflicts with the web-installer - which *also* removes the files.

I'm going to roll the fix for this into #2247, which needs to be done before the 1.0 anyhow.

Thanks for reporting!
