### ISSUE TITLE
Add "*.domain.tld" as a domain for application.

### ISSUE THREAD

**Issue by seospace** [dokku/dokku#3075]
I want my application to handle all subdomains for domain.tld
I found this nice article: http://entulho.fiatjaf.alhur.es/guias/wildcard-subdomains-on-dokku/

Is that article up-to-date or something has changed?
If nothing has changed, is it possible to change the behavior of domains plugin to add new command?
Like:

````dokku:domains create-wildcard domain.tld````
And then modify nginx with:
````~^(.*)\.domain\.tld$````

I guess bad things can happen right? I may be wrong but maybe it's easier than i think?

But what if we could add that wildcard ONLY if there are no other domains already added to an application? 

That can give us at least basic functionality that can be worked on later?

For me (someone who has no idea ) it looks like it could be added and shouldn't be hard.
I am right or not? 

If yes, i can take the challenge and try to write it (i will learn bash as i have no idea about it, can be a good lesson).

What do you think maintainers?

**Comment by josegonzalez** [comment]
I don't think it makes sense to do a "create-wildcard" type setup. The domains plugin isn't really aware of whether or not you are using nginx, and its possible for a user to change to another proxy implementation that _does_ understand a wildcard. If anything, this is a bug in `nginx` itself and you should file an issue there.

If you want a default application to handle all requests to a given server, you can name it so that it comes lexicographically first in the nginx import configuration. For instance, you would name your application `00-default`.

If you want to create a custom `nginx.conf.sigil` for your application to include custom configuration such as what you mentioned, that is also possible as well. The documentation for this is available [here](http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-the-nginx-configuration).

Finally, please see our documentation regarding [default site handling](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site).

Hope that makes sense.

**Comment by seospace** [comment]
@josegonzalez thank you, I've dived more and it looks more clear how to handle that
Nginx docs say clearly:
````
A special wildcard name in the form “.example.org” can be used to match both the exact name “example.org” and the wildcard name “*.example.org”
````
I actually tested that:
- I've made [default site handling file from the docs](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site)
- now everything that is not handled by Nginx should show 410 ( and it does)
- I've modified my nginx.conf.sigil from:
````{{ $.NOSSL_SERVER_NAME }}````
to
````.{{ $.NOSSL_SERVER_NAME }}````
- everything works as expected, subdomains are handled by the app

Does that change anything for this issue or still **that is just nginx configuration related**?
````
.domain.tld is invalid. exiting...
````
Best Regards

**Comment by josegonzalez** [comment]
@seospace I don't have any context for the following output:

```
.domain.tld is invalid. exiting...
```

Do you mind showing how you triggered that error? The exact command, the output, and also the trace output?

**Comment by seospace** [comment]
@josegonzalez the command is:
 ````dokku domains:add appname .domain.tld````
And the output is:
````.domain.tld is invalid. exiting...````

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by calebhaye** [comment]
> @josegonzalez thank you, I've dived more and it looks more clear how to handle that
> Nginx docs say clearly:
> 
> ```
> A special wildcard name in the form “.example.org” can be used to match both the exact name “example.org” and the wildcard name “*.example.org”
> ```
> 
> I actually tested that:
> 
> * I've made [default site handling file from the docs](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site)
> * now everything that is not handled by Nginx should show 410 ( and it does)
> * I've modified my nginx.conf.sigil from:
>   `{{ $.NOSSL_SERVER_NAME }}`
>   to
>   `.{{ $.NOSSL_SERVER_NAME }}`
> * everything works as expected, subdomains are handled by the app
> 
> Does that change anything for this issue or still **that is just nginx configuration related**?
> 
> ```
> .domain.tld is invalid. exiting...
> ```
> 
> Best Regards

@seospace It seems like every request made to the any of the wildcard domains are returning a 410.  The request isn't being handled by the app.  I followed the instructions you've outlined above.  Am I missing something?

**Comment by josegonzalez** [comment]
@calebhaye please open a new issue with all the information we request. Adding a wildcard domain should work fine now.
