### ISSUE TITLE
Migrate to other host, with allot of apps

### ISSUE THREAD

**Issue by reneweteling** [dokku/dokku#3078]
Hey guys,

Loving the product, even so much that I'm running too many apps for my server and need to upgrade, at the moment I've got about 55 apps running on Dokku and need to migrate to a larger server.

What's the best way to do this, all the pg / maria and redis are already backedup to s3, but I would really like to migrate everything without installing all the apps seperately. Especially all the config, env variables, plugin settings (lets encrypt for each domain, pg backups for each app etc)

I saw that you had a backup feature somewhere in the 0.4 range but it's discontinued. 

Thanks so much, hope hearing from you.

**Comment by josegonzalez** [comment]
There is currently no built-in method to do this at this time. A few notes:

- Application configuration can be exported via `dokku config:export`.
- Many plugins have a `report` command that you can use to see what the exact configuration of that plugin is. Many also have a `set` command for setting specific configuration.
- I highly recommend using configuration management for configuring your servers going forward. I have an unreleased set of ansible roles/libraries for doing exactly this - and its how we manage infra for the [CakePHP project](https://www.youtube.com/watch?v=264ho9xqeJU) - but you should be able to do similar yourself going forward.
- The backup functionality was discontinued because it was pretty buggy, a pain in the ass to keep up to date, and not consistent across all plugins. As we contain almost all config/data in the `/var/lib/dokku` and `/home/dokku` directories, backing those up will often be enough to migrate your application.
  - In the future, we'll likely be a bit better about how we store data in `/var/lib/dokku`, and there is a related config RFC open at the moment for just this purpose.

Sorry we don't have a better backup story, but I hope the above helps get you started.
