### ISSUE TITLE
[enhancement][information] LetsEncrypt wildcard SSL support is live

### ISSUE THREAD

**Issue by seospace** [dokku/dokku#3120]
SSL wildcards are alive https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by josegonzalez** [comment]
What exactly are you looking for here? Dokku core doesn't touch letsencrypt - thats in a separate plugin.

If anything this belongs in the other plugin. Please note that a wildcard cert requires DNS changes, so the automation will be less than ideal there.

Closing since the core doesnt touch letsencrypt.
