### ISSUE TITLE
Feature Request: Support passing environment variables to `dokku run`

### ISSUE THREAD

**Issue by ankane** [dokku/dokku#3291]
Hey, thanks for this awesome project. It's incredible!! I had trouble figuring out what to do with feature requests from the Contributing Guide, so let me know if this is the wrong place.

Currently, passing environment variables to commands like this:

```sh
dokku run HELLO=world rails console
```

Throws an error

```sh
setuidgid: fatal: unable to run HELLO=world: file does not exist
```

It'd be great if this set the `HELLO` variable and ran the command. This is the behavior on Heroku.

**Comment by josegonzalez** [comment]
I dont see where in their docs they say they support this: https://devcenter.heroku.com/articles/one-off-dynos

**Comment by ankane** [comment]
Hey @josegonzalez, I don't think it's explicitly documented, but think they try to have it behave as similar to a normal shell as possible. If you need an app to test it on, you can use [this link](https://heroku.com/deploy?template=https://github.com/pghero/pghero) for one click deploy.

There is a `-e` option that's documented in the CLI.

```sh
heroku help run
...
  -e, --env=env        environment variables to set (use ';' to split multiple vars)
```

which allows you to do

```sh
heroku run rails console -e "VAR1=value1;VAR2=value2"
```

**Comment by josegonzalez** [comment]
Ah okay, looks like its a flag to heroku run. Can you show the full output of `heroku help run`?

**Comment by ankane** [comment]
Yeah, here's the full output for the latest version (7.18.3):

```
run a one-off process inside a heroku dyno

USAGE
  $ heroku run

OPTIONS
  -a, --app=app        (required) app to run command against
  -e, --env=env        environment variables to set (use ';' to split multiple vars)
  -r, --remote=remote  git remote of app to use
  -s, --size=size      dyno size
  -x, --exit-code      passthrough the exit code of the remote command
  --no-notify          disables notification when dyno is up (alternatively use HEROKU_NOTIFICATIONS=0)
  --no-tty             force the command to not run in a tty
  --type=type          process type

DESCRIPTION
  Shows a notification if the dyno takes more than 20 seconds to start.

EXAMPLES
  $ heroku run bash
  Running bash on app.... up, run.1
  ~ $

  $ heroku run -s hobby -- myscript.sh -a arg1 -s arg2
  Running myscript.sh -a arg1 -s arg2 on app.... up, run.1

COMMANDS
  run:detached  run a detached dyno, where output is sent to your logs
```

**Comment by alexquick** [comment]
@josegonzalez How heroku handles `-e/--env` is a little involved because these arguments go in the same position as arguments to the invocation itself. Heroku prefers treating them as arguments to `run`, so if you want to pass an `-e` flag to the dyno verbatim you must do either:
* `heroku run -- myscript.sh -e some_not_env_value`
* `heroku run myscript.sh "-e some_not_env_value"`

And even more interesting, if you run `heroku run myscript.sh pos_one -eTRACE=on pos_two` myscript is invoked with pos_one and pos_two as arguments, with TRACE set in the environment.

Additionally, as @ankane said you can set environment variables as raw pairs, though it seems to be undocumented:
```
$ heroku run SAMPLE=a_sample env | grep SAMPLE
Running SAMPLE=a_sample env on xxx... up, run.nn (Free)
SAMPLE=a_sample
```

I could work on this but I feel like it may not be worth the extra complexity to maintain heroku compatibility.

I've got two simplified proposals:
1. Let users pass args to `run` before the app name: `dokku run [-eblah=blah --env blah2=blah] myapp myscript`. This is good because it's a non-breaking change and is simple to explain. The downside is that dokku doesn't normally put any arguments between the command and app name, so it could be confusing.
2. Accept -e/--env as arguments directly following the app name: `dokku run myapp [-eblah=blah --env blah2=blah] myscript`. This would require adding support for `--` to allow passing verbatim arguments and would introduce a small breaking change. I think it's unlikely to affect many (if any) people because it's most commonly something like `rails`, `npm`, or `manage.py` that's occupying this place in the command line currently.

Do you think either of these would be pursuing? What do you think the ideal cli for this would look like?

**Comment by josegonzalez** [comment]
@alexquick I'm fine with doing something simplified, as long as it makes sense :)

For the proposals:

1. We have flags before the app name already. The config plugin you refactored does that, as do any other golang plugins - both the `buildpacks` and upcoming `resource` plugin do it that way. Bash-based plugins all handle arguments differently, though as they get ported to golang, it'll be something we need to deal with.
2. I don't have any concerns about this, though it may be more confusing to users?

I think you mentioned wanting to use a different library for argument parsing? Might be a good opportunity to investigate, so long as the outcome is nicer :)

**Comment by charleshan** [comment]
Can we support this in Procfile as well?

I need to add `REMAP_SIGTERM=SIGQUIT celery -A proj worker -l info` to the Procfile but I get the same error as above.

```
setuidgid: fatal: unable to run REMAP_SIGTERM=SIGQUIT: file does not exist
```

Reference: https://devcenter.heroku.com/articles/celery-heroku#using-remap_sigterm

**Comment by josegonzalez** [comment]
Given how herokuish executes commands, I don't think thats possible. If you'd like that to be supported, the gliderlabs/herokuish project is where you'd want to contribute that support.

Closing as there is a pull request open :)
