### ISSUE TITLE
Deletion of files in sites-enabled nginx directory by debian preinst script

### ISSUE THREAD

**Issue by chupasaurus** [dokku/dokku#3303]
https://github.com/dokku/dokku/blob/a468b3b17bfcc2ec4b732526b4a50ae773dd5806/debian/preinst#L28
`rm -f /etc/nginx/sites-enabled/*`
I just want to know the reasons.

**Comment by josegonzalez** [comment]
[We've just always done it](https://github.com/dokku/dokku/commit/b6767f8efc10bbf4df2ab99b9f1e97378aea45fd). Otherwise, the default site would override our web installer, which would break installation.

Dokku expects to be able to own the entire server. That you can use the server for other things is just a bonus, but we do expect to be able to control how things get served etc. on a server.

Hope that helps.
