### ISSUE TITLE
Custom proctype (flower)

### ISSUE THREAD

**Issue by mbaechtold** [dokku/dokku#3320]
Let me first say thank you for this awesome project.

Now, I'm using Dokku to deploy my hobby Django projects, which is working fine. I even make use of the `worker` and `beat` proctypes using [Celery](http://www.celeryproject.org).

Now I want to run an instance of [flower](https://flower.readthedocs.io/en/latest/), the web based tool for monitoring and administrating Celery clusters which runs its own Tornado server.

How could I deploy this tool? I don't even need an Nginx in front of it, I'd already be glad to open an SSH tunnel to the internal port flower is running on.

Could you please provide some hints where to look for, maybe in the documentation? Do I need to build my own docker container for this?

**Comment by josegonzalez** [comment]
The process types are just identifiers. The only special one is `web`, which we expose via the configured proxy plugin (nginx is built in but you could make your own plugin for another webserver) and scale to 1 by default.

You can name your process types whatever you want, you'll just need to scale them up to at least 1. Because we deploy via containers with ephemeral ip addresses, you'll need to do a `dokku ps:report APP` to see what container id is running for your app and then `docker inspect` that.

If you want to deploy this standalone, you could just deploy it as a regular app. No fancy dancing needed.

In the future, we _may_ support injecting all container information into the `nginx.conf.sigil` generation so you could mount a non-web proctype for hosting, but thats not possible at the moment.

Hope that helps. Feel free to drop onto our slack with further questions :)

**Comment by CleitonDeLima** [comment]
@mbaechtold 
Did you use the flower in the dokku?

**Comment by mbaechtold** [comment]
Hey @CleitonDeLima. 

No, I abandoned that endeavour because I have switched from Celery to https://python-rq.org.
