### ISSUE TITLE
Add system fonts

### ISSUE THREAD

**Issue by jrmedd** [dokku/dokku#3440]
My app generates .pdf files using CairoSVG using a .ttf font not installed by default. CairoSVG requires fonts to be installed on the system to locate and use it. 

I've tested this after installing the font on macOS (~/Library/Fonts) and Ubuntu (/usr/share/fonts). What approach should I use to include the font when deploying with Dokku (using git)?

I've read online that a .fonts directory in my application's root should work, but it doesn't seem to.

I'm using version 0.13.4

**Comment by josegonzalez** [comment]
You may wish to use the [dokku-apt](https://github.com/F4-Group/dokku-apt) plugin if the font is installable. Otherwise, you'll likely need to either use a [Dockerfile for deploys](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/) or [develop a custom plugin](http://dokku.viewdocs.io/dokku/development/plugin-creation/) using the [pre-build-buildpack](http://dokku.viewdocs.io/dokku/development/plugin-triggers/#pre-build-buildpack) trigger.

Hope that helps.
