### ISSUE TITLE
app container failed to start

### ISSUE THREAD

**Issue by onebook0505** [dokku/dokku#3495]
When I run command `dokku ps:scale node-app worker=2`, I get error app container failed to start, how can I solve it?

Thank you for your answer.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
The issue here ended up being that the user read [an article](https://devcenter.heroku.com/articles/background-jobs-queueing#approach) on increasing application concurrency. The article said that this could be accomplished by using/scaling `worker` processes, which is true but requires actual application changes.

In this case, there was no actual `worker` process type to scale, thus the containers failed to start.
