### ISSUE TITLE
App name with dot (.) leads to unexpected behavior

### ISSUE THREAD

**Issue by MarcDiethelm** [dokku/dokku#3529]
Tested with v0.15.5.

Dokku allows creation of apps with `.` in their names.

With vhosts deployment enabled at a server with domain `domain.tld`...

Create (optional)
```shell
dokku apps:create foo.bar
```

Standard deploy (with dokku repo set)
```shell
git push dokku:foo.bar
```
Creation and deployment both succeed...

Now strictly according to the docs the app should be deployed to `//foo.bar.domain.tld`. This isn't the case. The app is instead deployed to `domain.tld` (where it may take precedence over already deployed apps).

Either Dokku should treat the name `foo.bar` as invalid or deploy to `//foo.bar.domain.tld`.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

As well, please include the output of a deploy that exhibits this issue.

**Comment by josegonzalez** [comment]
According to the docs - and to my own testing - this is working as documented, but not as you want it to. The only way to do what you want is to use the `domains` plugin to explicitly set the domains for your app. The following scenarios should explain why this is the case.

### Scenario 1

- global vhost: dokku.me
- app name: test
- resulting app vhost: test.dokku.me

```shell
dokku apps:create test
dokku domains:clear test
dokku domains:report test --domains-app-vhosts
dokku --force apps:destroy test
```

### Scenario 2

- global vhost: dokku.me
- app name: test.me
- resulting app vhost: test.me

```shell
dokku apps:create test.me
dokku domains:clear test.me
dokku domains:report test.me --domains-app-vhosts
dokku --force apps:destroy test.me
```

### Scenario 3

> I have no idea why [anyone](https://github.com/dokku/dokku/commit/f23809e75f305715fdb580be90340cfc6cfc85de#diff-b505d6d5ec42c48ef5e318fc15869008R35) thought this was a good idea...

- global vhost: dokku.me
- app name: test.me.dokku.me
- resulting app vhost: test.me.dokku.me.dokku.me

```shell
dokku apps:create test.dokku.me
dokku domains:clear test.dokku.me
dokku domains:report test.dokku.me --domains-app-vhosts
dokku --force apps:destroy test.dokku.me
```

---

I think it's worth breaking BC to fix scenario 3 so that you can name an app `test.dokku.me` and have that be the domain name. I'll push a PR up for that.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
