### ISSUE TITLE
ps: scale cleanups

### ISSUE THREAD

**Issue by scjody** [dokku/dokku#3708]
As a followup to https://github.com/dokku/dokku/pull/3703, we should consider cleaning up some of the `ps:scale` code:

* If a `DOKKU_SCALE` file doesn't exist and a "can-scale" check is done, [one will be created](https://github.com/dokku/dokku/blob/8c6e4c648330ec0d421870190caa460bdf753f4d/plugins/ps/functions#L249). All we really want to do here is to check if the app image contains a `DOKKU_SCALE` file, so not everything `generate_scale_file` does is necessary or useful. In particular, if a "can-scale" check is done before the app is deployed we'll end up with a default `DOKKU_SCALE` file containing only `web=1`.
* Consider some refactoring in `generate_scale_file`: Can this function generate and update the scale file as needed? Can we switch it to use `procfile-util`?

@josegonzalez mentioned (in an internal discussion):

> General comment: I meant to have `procfile-util` be used to manage the `DOKKU_SCALE` file, but I'm also quite unhappy with the `DOKKU_SCALE` file handling within Dokku in general. I would like to deprecate it in favor of an entry in `app.json`, and also write whether the app has a `DOKKU_SCALE` file or not (and therefore _can_ scale) as a property for the plugin/app combination.

We also discussed replacing the `DOKKU_SCALE` file in the app's home directory. This file is  a bit weird in that it means "this is what I want the scaling to be" in the app's repo, but "this is what the scaling _is_" in the app's home directory. We don't currently have a good short term proposal on what to replace `DOKKU_SCALE` with, but querying Docker for the current scale status would work if it can be done efficiently.

@gyfis FYI, since you're working in this area.

**Comment by josegonzalez** [comment]
Querying docker's current state won't work if the containers die or are pruned, unfortunately :(

**Comment by gyfis** [comment]
Thanks for the tag!

Based on my (very limited) experience running a production app on dokku, I would prefer to not query Docker for the current scaling state - it doesn't seem very stable.

As for the `DOKKU_SCALE` in the file app's home directory (again with very limited knowledge about the topic) - I like the fact a _current_  scaling is written somewhere explicitly, to keep track. Is it only a naming issue (plus some refactor), e.g. what about `DOKKU_CURRENT_SCALE`? 

We don't personally use the `DOKKU_SCALE` in the app's repo so I'm biased, but I can also see you deprecating the app's repo `DOKKU_SCALE` in favor of a no-deploy dokku ps:scale command before deploy or for scaling (which would be the only(?) way to scale, instead of pushing a new version with a new `DOKKU_SCALE` file).

**Comment by scjody** [comment]
Yes, a `DOKKU_CURRENT_SCALE` file would work. We were trying to come up with an alternative that didn't involve a file in the app directory, but there doesn't seem to be a simple one that would work with Dokku as it is now.

We intend to continue to support both use cases: scaling via a file in the repo (whether that's `DOKKU_SCALE` or an entry in `app.json`) _or_ scaling via `ps:scale` if there is no file. We've found that some users prefer one or the other depending on their particular workflows.

**Comment by josegonzalez** [comment]
Going to merge this into #4500. The ps plugin was otherwise refactored to make the code here a bit faster and easier to understand, but the upcoming changes should completely clarify what is happening.
