### ISSUE TITLE
Question: Private Buildpack Hosting?

### ISSUE THREAD

**Issue by weisisheng** [dokku/dokku#3751]
Installed Dokku on AWS Beijing and everything basically works.  If I try to do anything productive with buildpacks, it fails for some reason even though git is (not yet) blocked in China.

This has been asked in the past without real clear direction.  Easier to host a private git repo on S3 or create a dockerfile?  I have basic knowledge of docker but would appreciate any links.  I am also considering out loud whether it will face "blocked" issues while building.

Thanks in advance.  I asked this in #IRC group and crickets so appreciate any wisdom

**Comment by josegonzalez** [comment]
The IRC crickets are due to me moving apartments and not having the irc-to-slack relay running yet (I don't even have a bed frame yet lol). Slack might be the better option if it's not blocked. I'll get the relay running sometime this week/weekend (in Montreal for work).

You can host custom buildpacks at any git-like URL. I'd imagine that part of the reason your builds may fail is that buildpacks can and will fetch dependencies from various places across the net (S3, Language repositories, Github, etc.) so you'd need to figure out what exactly is failing for your build and then fork the buildpack to pull from a non-blocked location.

**Comment by josegonzalez** [comment]
Addendum: In terms of using a Dockerfile, it should be the same as any other dockerfile, nothing special about Dokku. Please refer to our dockerfile deploy docs for more detailed info.

**Comment by weisisheng** [comment]
Thanks so much for the fast response.  Best of luck with the move!

**Comment by weisisheng** [comment]
Some anecdotal which might help others.  I haven't gone the dockerfile route yet but pinning/tagging a 
node.js version in my package.json got me past that step.

Added this:

  "engines": {
    "node": "12.13.0"
  }

https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

Now onto yarn install...
