### ISSUE TITLE
Always show Nginx default page

### ISSUE THREAD

**Issue by Albert-Gao** [dokku/dokku#3802]
I am deploying an express + React app, everything works fine until I want to use Nginx to serve all non-API requests.

The static files are in the `{APP_ROOT}/public/`

I want to:

- All non-file-extention requests should return index.html
- All /api/* request should proxy to backend
- All js, css, images goes to `{APP_ROOT}/public/`

```nginx
  location    / {
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    try_files $uri $uri/ public/index.html;
  }

    location /api/ {
        gzip on;
        gzip_min_length  1100;
        gzip_buffers  4 32k;
        gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
        gzip_vary on;
        gzip_comp_level  6;

        proxy_pass  http://{{ $.APP }}-{{ $upstream_port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
    }
```

I created the `nginx.conf.sigil` at the app root. Only modified the `location` part, the others are the same from the default template https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil

However, the server always shows the default nginx page rather than my page.

I tried something like:

```nginx
    root {{ $.DOKKU_ROOT }}/{{ $.APP }}/public/;
    try_files $uri /index.html;
```

Still 500

What am I missing here? Thanks :)

**Comment by josegonzalez** [comment]
The nginx server runs outside of your app's container, and will not have direct access to the built assets. This is by design - the proxy layer is more or less explicitly separate from the actual app code. As well, the `$DOKKU_ROOT/$APP` path is a path to the "git bare" repository. This is different from a regular repository in that there is no working tree ([see this article for a longer explanation](https://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/)).

You will need to proxy those requests from within your app container, or build a custom plugin that uses one of the plugin triggers - perhaps `nginx-pre-reload`? - to extract all the data onto a path on disk - please don't put it somewhere in `$DOKKU_ROOT/$APP`, thats not where that goes - and then a custom `nginx.conf.sigil` in your app that points to that path as necessary.

Hope that helps. If not, feel free to stop by our slack channel for further discussion.

**Comment by Albert-Gao** [comment]
I see, thanks :)
