### ISSUE TITLE
Backup for Dokku Persistent Storage

### ISSUE THREAD

**Issue by AxelTheGerman** [dokku/dokku#3820]
## Description of problem
I'm using dokku to deploy a web application where users can upload files. I'm using the persistent storage plugin to provide that to the docker container - http://dokku.viewdocs.io/dokku~v0.19.11/advanced-usage/persistent-storage

Is there a way to back up this directory using dokku or do I need to configure something on the dokku host myself (and if so, any recommendations, best practices, documentation?)

#### Expected Results

Similar to the postgres plugin, I would like to configure backups to S3 for my persistent storage volumes:
```
# setup s3 backup authentication
dokku postgres:backup-auth lolipop AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY

# remove s3 authentication
dokku postgres:backup-deauth lolipop

# backup the `lolipop` service to the `BUCKET_NAME` bucket on AWS
dokku postgres:backup lolipop BUCKET_NAME

# schedule a backup
# CRON_SCHEDULE is a crontab expression, eg. "0 3 * * *" for each day at 3am
dokku postgres:backup-schedule lolipop CRON_SCHEDULE BUCKET_NAME
```
https://github.com/dokku/dokku-postgres#backups

Is this possible at all? I found also this project https://github.com/dokku/docker-s3backup which maybe just needs some easier integration, e.g. CRON schedule

**Comment by josegonzalez** [comment]
Dokku does not provide any wholistic backup solution at this time. We actually removed the "backup" code a while back since it wasn't maintained and actually had a pretty awful interface (cat'ing files to generate a tarball...).

The backup code for the datastores was built because a community user sponsored the work (any sponsored work ends up becoming OSS by default).

Part of this problem should be solved by #1558, which will allow us to have a consistent interface for where files are stored, and therefore we could simply say "backups are a tarball and go".

In your case, you could certainly wrap s3backup into a separate plugin that acts standalone on a given directory. I don't think we'd do that in the core, at least not at this time.

Hope that helps.

**Comment by AxelTheGerman** [comment]
Thanks @josegonzalez ! I also see you're the maintainer of `docker-s3backup` so our paths might cross again.

Thanks also for all the amazing work on dokku!

**Comment by tarikmiljkovic** [comment]
@josegonzalez why on redeploy of an app, Dokku destroys DB like Postgres and how to avoid it?

**Comment by AxelTheGerman** [comment]
@tarikmiljkovic not sure I am following. None of my deploys are destroying the DB 🤔 

Are you deploying via git or docker? Are you de-deploying the same version?

This issue was more of a feature request for backups, if you are encountering bugs related to DB being destroyed it is probably better to create a new issue 🙂
