### ISSUE TITLE
App starts correctly inside Docker but not reachable on the outside

### ISSUE THREAD

**Issue by apa512** [dokku/dokku#3823]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem

I can deploy my app (with no CHECKS) but it's not available on port 80 on the host.

### How reproducible

Install latest Dokku on Ubuntu 18.04 and push a Clojure app. I have a Procfile and no Dockerfile, which apparently enables something called herokuish.

#### Actual Results
`curl localhost:80` => The "We're sorry, but something wen't wrong" page

`curl 172.17.0.2:5000` =>
`curl: (7) Failed to connect to 172.17.0.2 port 5000: Connection refused`

`dokku enter myapp`
`curl localhost:5000` => My website's HTML

#### Expected Results

`curl localhost:80` => My website's HTML

I'm probably missing some basic settings, but from reading the docs I would expect my app to work out of the box.

Based on what little I know about Docker, it seems weird that no ports are exposed:
`sudo docker ps`
```CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS               NAMES```

```d6b214a7fa9b        dokku/myapp:latest                     "/start web"        12 minutes ago      Up 12 minutes                           myapp.web.1```

**Comment by Cellane** [comment]
The part about no exposed ports should be really fine, actually. Dokku installs and configures Nginx to act as a proxy, and the upstream for that proxy server is set to be (in your example) 172.17.0.2:5000. On all my Dokku servers, I don’t see any Dokku-managed containers having any exposed ports at all. (Actually I think this must happen by design, because if you scaled your app to multiple containers instead of just one, and each of those containers would expose the same port, things would surely blow up, right?)

I think one thing to check in the case when you can access the website from inside the container but not from outside is which address & port does your application listens on. If I’m not mistaken, it should listen on `0.0.0.0:5000` (or to be precise, `0.0.0.0:$PORT`). If, for example, it only listens on `127.0.0.1:5000`, I think you’ll end up in a situation exactly like you’re describing – that is, inaccessible website.

**Comment by apa512** [comment]
@Cellane Thanks. You were right about my app only listening on 127.0.0.1 (https://github.com/pedestal/pedestal/issues/604).
