### ISSUE TITLE
Document the official dokku shell client

### ISSUE THREAD

**Issue by scratchmex** [dokku/dokku#3963]
Hi, I'm starting to use Dokku and I will love some handy features of the Flynn CLI.
- Auto setting git remote when inside a git repo. When creating an app with `dokku apps:create` like when doing `flynn create`: 

> If run from a git repository, a 'flynn' remote will be created or replaced that
allows deploying the application via git.

- As well as when deleting the app deleting the remote in the git.

- Auto linking backing services to application. When creating a resource like `dokku postgres:create` auto setting the env variables if inside a git repo with dokku remote set instead of manual linking with `dokku postgres:link`

**Comment by josegonzalez** [comment]
For the local client within the repository, we already perform the first two bullet points:

- create: https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L129
- destroy: https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L138

As far as the third, I don't think that makes sense unless those plugins become bundled with the core project, which I have no current plans for at this time (nor do I think that makes sense, since they evolve at a different pace).

For the first two bullet points, are you currently not seeing that behavior with our client?

**Comment by scratchmex** [comment]
Sorry, I was creating the apps outside the git repo. Maybe the documentation doesn't mention it? I'm 90% sure I checked.

I agree the plugins should remain apart. Maybe I can suggest to them that as a kind of default behavior.

Thanks for your reply.

**Comment by josegonzalez** [comment]
I don't think we could reasonably add support into non-core plugins for that sort of automagic functionality, unfortunately, as there is no "client-server" model in place.

We can certainly create a docs page for the official client. I'll change this issue to reflect that.
