### ISSUE TITLE
logrotate fails on dokku-letsencrypt logs

### ISSUE THREAD

**Issue by jbothma** [dokku/dokku#4000]
## Description of problem

Cron reports an error when trying to rotate letsencrypt logs

subject `Cron <root@dokku9> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )`

message

```
/etc/cron.daily/logrotate:
error: destination /var/log/dokku/letsencrypt.log.1.gz already exists, renaming to /var/log/dokku/letsencrypt.log.1.gz-2020052106.backup
error: error setting owner of /var/log/dokku/letsencrypt.log.1.gz to uid 1001 and gid 1001: Operation not permitted
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

### How reproducible

Reliably on multiple dokku versions

### Steps to Reproduce

1. install dokku and dokku-letsencrypt
2. start an app
3. letsencrypt the app
4. read cron error mails and find the above error

#### Actual Results

letsencrypt logs are not rotated beyond letsencrypt.log.1

We get an email every morning noifying of this cron error

#### Expected Results

letsencrypt logs are rotated, cron doesn't encounter errors

### `dokku report APP_NAME` output

----> dokku version: dokku version 0.19.11
-----> dokku plugins: 
       plugn: 0.3.2
         00_dokku-standard    0.19.11 enabled    dokku core standard plugin
         20_events            0.19.11 enabled    dokku core events logging plugin
         app-json             0.19.11 enabled    dokku core app-json plugin
         apps                 0.19.11 enabled    dokku core apps plugin
         builder-dockerfile   0.19.11 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.19.11 enabled    dokku core builder-herokuish plugin
         buildpacks           0.19.11 enabled    dokku core buildpacks plugin
         certs                0.19.11 enabled    dokku core certificate management plugin
         checks               0.19.11 enabled    dokku core checks plugin
         common               0.19.11 enabled    dokku core common plugin
         config               0.19.11 enabled    dokku core config plugin
         docker-options       0.19.11 enabled    dokku core docker-options plugin
         domains              0.19.11 enabled    dokku core domains plugin
         elasticsearch        1.12.2 enabled    dokku elasticsearch service plugin
         enter                0.19.11 enabled    dokku core enter plugin
         git                  0.19.11 enabled    dokku core git plugin
         http-auth            0.4.0 enabled    HTTP authentication for apps
         letsencrypt          0.9.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.19.11 enabled    dokku core logs plugin
         memcached            1.9.5 enabled    dokku memcached service plugin
         network              0.19.11 enabled    dokku core network plugin
         nginx-vhosts         0.19.11 enabled    dokku core nginx-vhosts plugin
         plugin               0.19.11 enabled    dokku core plugin plugin
         postgres             1.9.5 enabled    dokku postgres service plugin
         proxy                0.19.11 enabled    dokku core proxy plugin
         ps                   0.19.11 enabled    dokku core ps plugin
         redis                1.10.4 enabled    dokku redis service plugin
         repo                 0.19.11 enabled    dokku core repo plugin
         resource             0.19.11 enabled    dokku core resource plugin
         scheduler-docker-local 0.19.11 enabled    dokku core scheduler-docker-local plugin
         shell                0.19.11 enabled    dokku core shell plugin
         ssh-keys             0.19.11 enabled    dokku core ssh-keys plugin
         storage              0.19.11 enabled    dokku core storage plugin
         tags                 0.19.11 enabled    dokku core tags plugin
         tar                  0.19.11 enabled    dokku core tar plugin
         trace                0.19.11 enabled    dokku core trace plugin

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

same behaviour with ansible-dokku and standard install script.

AWS and hetzner Ubuntu 18.04

**Comment by jbothma** [comment]
It looks like the initial letsencrypt.log is owned by `dokku:dokku` but logrotate on ubuntu is configured to run as `syslog:dokku`

## Workaround

Ensure `letsencrypt.log.1` belongs to syslog:dokku

## Potential fix

Ensure initial letsencrypt.log belongs to syslog:dokku before logrotate gets to it

I'm not sure if this will fix it but I suspect so, if what's happening is that logrotate renames it to .1 without trying to fix ownership, and then tries to set ownership when compressing it.

**Comment by josegonzalez** [comment]
Wait is the group or the user dokku? What _should_ we do when we want to log output to /var/log? Does anyone know?

**Comment by josegonzalez** [comment]
For my investigation alter this week:

```
(cmd | tee >(logger -t 'dokku-letsencrypt' -i  -p user.notice)) 3>&1 1>&2 2>&3 | tee >(logger -t 'dokku-letsencrypt' -i -p user.err)
```

**Comment by josegonzalez** [comment]
If we use the logger commands above, we'll want to also switch the cron-entries to drop the file argument in each line. The files will then be owned by `syslog:adm`, assuming rsyslog is running.

Seems like logrotate does not complain about those permissions - because the owner is syslog, it can do what it likes.

**Comment by josegonzalez** [comment]
I looked into `logger` and it seems there is [some funny business](https://unix.stackexchange.com/a/598775/105389) due to how logger and systemd work. `systemd-cat` is an alternative but would tie us to systemd, which I want to avoid so that we continue to support the docker-based installation method.

Based on [this](https://unix.stackexchange.com/a/598775/105389), I constructed the following snippet that I put in `/usr/local/bin/shell-logger`:

<details>
  <summary>/usr/local/bin/shell-logger</summary>
  ```shell
  #!/usr/bin/env bash

  main() {
    declare TAG="$1"
    declare LEVEL="$2"
    while read -r line; do
      builtin_logger "$TAG" "$LEVEL" "$line"
    done </dev/stdin
  }

  # modified from: https://unix.stackexchange.com/a/598966/105389
  # license: https://creativecommons.org/licenses/by-sa/4.0/
  builtin_logger() {
    declare TAG="$1"
    declare LEVEL="$2"
    declare MSG="$3"
    if [[ "${SHELL_SERVICE_LOG_SOCK-}" == "" ]]; then
      declare -g SHELL_SERVICE_LOG_SOCK
      SHELL_SERVICE_LOG_SOCK="/tmp/service-log.$$"
      SHELL_ID="$$"
      sh -c "socat UNIX-RECV:'$SHELL_SERVICE_LOG_SOCK' UNIX-SENDTO:'/dev/log' &
                SOCAT_PID=\$!
                trap \"if [ -e '$SHELL_SERVICE_LOG_SOCK' ]; then rm -f '$SHELL_SERVICE_LOG_SOCK'; kill \$SOCAT_PID 2>/dev/null; fi\" EXIT INT TERM
                tail --pid=$$ -f /dev/null" &
      sleep 0.1 # waiting for socat to run (TODO inotify)
    fi
    logger -u "$SHELL_SERVICE_LOG_SOCK" -t "$TAG" --id "$SHELL_ID" -p user."$LEVEL" -- "$MSG"

    # added to print to stdout/stderr
    if [[ "$LEVEL" == "info" ]]; then
      echo "$MSG"
    else
      echo "$MSG" >&2
    fi
  }

  main "$@"
  ```
</details>


I then ran this like so:

```
dokku ps:rebuild app > >(shell-logger dokku info) 2> >(shell-logger dokku err)
```

This mostly works (output goes to stdout/stderr + journalctl) except that it always shows logging output as "blob data". If I do something like `builder:set`, it logs fine, so I'm not sure what exactly is going on with journalctl.

---

If we go with the above route, the ideal case is that we modify the `dokku` binary to be a thin wrapper around something like `unlogged-dokku`. The `dokku` binary would call `unlogged-dokku` for the actual logic, wrapping it with the `shell-logger` binary (we'd ship that as well). This would allow _all_ dokku commands to be logged, not just logrotate or anything else, meaning we could drop those completely. Some other ideas:

- Pass `DOKKU_PID` to the `shell-logger` and using that as the id of the log message so all log messages from a given command have the same ID.
- Use `--journald` flag to pass more structured information to each log message (such as the cron-id if available)
- Use the called command as part of the tag namespace
- Log certain commands to a file

This is all a bit ambitious, but at least gives us a jumping off point.

**Comment by josegonzalez** [comment]
The easier fix is just to use copytruncate, which will leave file permissions alone at the cost of _potentially_ losing a few log lines.

Closing as there is a pull request open.
