### ISSUE TITLE
Horizontally scaling Dokku network-wise

### ISSUE THREAD

**Issue by tucnak** [dokku/dokku#4012]
Hello,

First of all, big thanks for the fascinating project that is Dokkku. I've been using it happily for years now. At some point I've realised I'm now hitting scale with my VDS instance, so I would like to learn more and possibly, contributed to the cause w.r.t. horizontal scaling. Making custom buildpacks is a breeze, mounting data and database backups are fun, too.

I've got a couple questions though. One of the things I noticed is that Dokku will actually allow you to create an app with a slash in it. Although `$ dokku apps:create app/service` will complete without errorrs, when pushing, you'll realise that apps apparently cannot contain anything out of the ordinary [A-Za-z0-9_]. I can see the reason for that has to do with how containers are provisioned, but isn't it more of an artificial problem? I would very much like to organise my many apps into some app groups, so I could have `<app_name/service_name>` structure and use that to manipulate the apps both via Git and in–terminal. And the names could then be slugged into something else via a simple replacement: `/ -> __`. I would love to have the output of `$ dokku apps:report` more informative and add a little structure to it:

```
=====> My Apps
aletheia/
    api [n]
    web [m]
veritas/
    web [n]
    api [m]
    worker [0]
```

And the number in brackets could indicate the number of currently running instances.

But this is the not the primary matter of my question. Is there a way in Dokku to run multiple machines (think georeplication), have some Edge-style load balancer and be able to run the microservices in a shared VPN? I know there's probably a way to do that with Kubernetes, but it would've been very cool if I could just go and spin a few dokku instances, use a single dokku command to connect them into a single VPN and then use master instances to push the code across. A/B can be implemented fairly easily, once this framework is in–place.

Is this something you're looking for assistance with?

Cheers,
Ian

**Comment by josegonzalez** [comment]
A few notes:

- Being able to put a `/` in the app name is a bug. I'll fix that.
- Utilizing the directory structure to "group" apps is going to be a wild pain. You can use hyphens to "group" them, but otherwise i don't think breaking internal app referencing is worth the extra complexity (random plugins will almost certainly break, and routing will be a bit more confusing).
- You can push code to multiple servers at once, and also put an nginx load balancer in front of everything if desired. I don't think there is anything special we can/should do to help with that.
- You can build a plugin that pushes an image to other servers and deploys that image. The first part of that could be a wrapper around docker save/load. The second is just using our internals to do that.

I don't think this is a good use of the core project's time as we're ostensibly then building a distributed scheduler to deal with how you binpack applications (kubernetes and nomad exist). If we _don't_ do that, then this is also not an interesting use of the core project's time, as it actually makes it easier to reason about all your servers (you gain nothing from having several boxes to connect to in order to run the individual Dokku commands).

Happy to discuss further in slack/irc, but I hope the above makes sense.

**Comment by tucnak** [comment]
Thank you for the quick response!

Yes it does make a lot of sense. I've never heard of Nomad, it looks very interesting. I've realised Kubernetes was probably too complicated for my usecases, but now that you've suggested Nomad, I'll pay it a closer look and this will probably be more than enough for what I'm doing.

Cheers,
Ian

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by josegonzalez** [comment]
Why would kubernetes be too complicated for your use case?

**Comment by tucnak** [comment]
I've tried a simplified version of Kubernetes that is k3s, minikube; after fiddling around with it for a while I've come to realise I can't make it work intuitively and for anything I can make it work—the mental overhead is just too much. I've had great success with tools like Terraform before, but there are limitations as to how deep it can be involved in the application logic, maybe I'll have a better luck with Nomad.

Wrt. mental overhead, Dokku is a blessing.
