### ISSUE TITLE
Docker options documentation doesn't mention rebuild required

### ISSUE THREAD

**Issue by ypadlyak** [dokku/dokku#4101]
--sysctl net.ipv4.ip_local_port_range="15000 65000"  in DOKKU_OPTIONS_RUN doesn't apply inside running container

**Comment by ypadlyak** [comment]
It is more of a question if it is possible to modify kernel parameters in dokku app containers:  https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

**Comment by josegonzalez** [comment]
Did you perform a `ps:rebuild` of the app?

**Comment by ypadlyak** [comment]
@josegonzalez hm, no. I thought it not needed since it is docker run command options. Or, do I? I will try now..

**Comment by josegonzalez** [comment]
Ah thats not clear in the docs, I'll rename this ticket to make it clear.

**Comment by ypadlyak** [comment]
It works! Thanks!
Could you please explain why rebuild is needed here?

**Comment by josegonzalez** [comment]
For many actions in Dokku, we only set options, but don't rebuild containers. I would love to make it so that the only thing that rebuilds a container is a forced `ps:rebuild`. My idea here is that you may wish to execute a ton of configuration commands at once before finally executing a rebuild, which is slow.
