### ISSUE TITLE
worker restart strategies

### ISSUE THREAD

**Issue by benjamin-thomas** [dokku/dokku#4132]
dokku version 0.21.4

Hello, I've hit this bug on my server, which I was quite confused about:

- https://github.com/dokku/dokku/issues/3794
- https://github.com/dokku/dokku/issues/3803

Anyways, killing the hanging (and running) containers did the trick but that's quite a gotcha.

But this triggered a question. In the docs related to [process management](http://dokku.viewdocs.io/dokku/deployment/process-management/), it's advised to scale workers this way:

    dokku ps:scale node-js-app web=1 worker=1

However the previously running container hangs around for 60 seconds upon app restart or deploy.

That makes perfect sense for the web container, but I don't  want that for my worker which should run only once at any time.

Is this possible at all?

**Comment by josegonzalez** [comment]
At the moment, having different process restart strategies isn't possible. It _may_ be possible after I refactor app building/releasing to be in Golang, but even then, this would be the default.

Regarding having multiple workers, thats tough. What happens if we stop all the old workers and attempt to start new ones, but the new ones fail to boot? Does that fail the deploy? Should we start the old workers? What happens when you scale past 1? Do we stop 1-by-1 still? I think when you get to this level of process management, we should switch out the scheduler from docker-local to nomad or kubernetes (both of which have Dokku plugins and should be able to run in single-server mode).

Re: those issues, the ps refactor should let me actually resolve them, and I hope to have that out this week.

**Comment by josegonzalez** [comment]
Going to close this for now as I likely won't implement anything here, but definitely interesting to discuss and could be an area for improvement in the future.

**Comment by benjamin-thomas** [comment]
To be honest, I don't think I have really thought about all those questions myself ;)

Dokku allows me to not have to dip my toes into kubernetes, I like it's simple design (or so it seems).

Anyways my though is that the "plug" should be pulled beneath an underlying process, and by a configurable amount. If it's configurable, then I'll deal with the consequences.

So in a sense, it'd be great to be able to inject something like this (those would be env vars):

    DOKKU_WAIT_TO_RETIRE[web]=60
    DOKKU_WAIT_TO_RETIRE[background_job]=0
    
And maybe be allowed to have a check file for a given process, something like:

    CHECK.web
    CHECK.background_job

Anyways, food for thought maybe. I'd love to contribute but I don't have the time at the moment unfortunately.

Great job though!

**Comment by josegonzalez** [comment]
Env vars don't have bracket characters, but more ideally I'd like to move away from env vars to properties.

Adding this feature will definitely make things more complicated. I think adding knobs isnt the best way to develop Dokku, and we should instead have as many sane defaults first before adding a knob. I think what we have now is easy to reason about :)

re: alternative schedulers, hopefully dokku makes the setup easy enough that it can hide the complexity of the scheduler and only shows you the power.

**Comment by benjamin-thomas** [comment]
Doh, I didn't think about that :)

Yeah I understand your view point. I'm just having a basic use case where I have a web app + 1 worker, and wouldn't want concurrent db access from the worker (to keep things simpler for now).

Meanwhile, I've just put my worker to sleep for 2 minutes before actually starting and that's kinda fine for my use case.

I'll probably have to look into a better scheduler then ;)

Have a great day
