### ISSUE TITLE
Provide official GitHub action to deploy from GitHub releases

### ISSUE THREAD

**Issue by jezdez** [dokku/dokku#4151]
## Description of problem

I noticed that there are quite a few [GitHub actions for Dokku on the GitHub marketplace](https://github.com/marketplace?query=dokku) which indicates to me that there is a need in the community. I would suggest to offer an official GitHub action for security and documentation reasons.

**Comment by josegonzalez** [comment]
This makes sense. What features should the push action have? Is there a community one we can just adopt/make official (with the consent of the maintainer of course)?

**Comment by jezdez** [comment]
I'm not completely sure, there are a few differences in their approaches, but I would say whatever you chose it should be using native workflow arguments instead relying on environment variable to pass configuration parameters. I would also lean towards providing a high-level approach instead of exposing all kinds of SSH options so that regular users don't accidentally misconfigure it. E.g. using SSH passwords for deployment should be not possible.

**Comment by julienma** [comment]
I too would prefer an "official" action.

I've been using https://github.com/obrassard/action-dokku-push with success. There are multiple plugins, but this one seems the most straightforward to me (only required options, uses a standard git repo URL in ssh format—the same that I use to create my git remotes—instead of splitting this in multiple params), have the ability to cancel previous runs.
Could be a good starting point?

**Comment by jsuchal** [comment]
We use this one https://github.com/marketplace/actions/dokku-deploy-action and seems to do its job good.

**Comment by josegonzalez** [comment]
@obrassard would you be fine with me making your action the official one? I have a few (small) changes to make to it, but we'd republish it under the Dokku org and I would give you commit bit.

If not, I'll write one from scratch, but I'd rather save myself some time and effort in the long-run :)

**Comment by obrassard** [comment]
Hi @josegonzalez I am fine with that, you can go ahead! 👍

**Comment by josegonzalez** [comment]
@obrassard mind adding me as a repo-admin on your repo? I'll grant you commit bit and everything once the repo has been moved.

**Comment by josegonzalez** [comment]
@obrassard what is the Dockerfile for `obrassard/alpine-git-ssh` ? That is currently in use by that github action.

**Comment by obrassard** [comment]
Here it is : https://github.com/obrassard/dockerfiles/blob/master/alpine-git-ssh/Dockerfile

**Comment by josegonzalez** [comment]
I went through @obrassard's github action as well as others and did a few things:

- created a new action based on @obrassard's work. I also kept your copyright, though added myself due to the extra work
- general file and variable refactor
- added support for review apps, pre-specified host, custom push flags
- added example workflow files for common tasks
- added lint tests so we can work on this and at least have confidence that the files are valid

The action is labeled as a [pre-release on the Github Marketplace](https://github.com/marketplace/actions/dokku), but I'd like to see if folks can play around with it and verify that each of the workflows I've documented works as expected.

**Comment by josegonzalez** [comment]
Next steps:

- Add to some simple documentation under a new `CI/CD` section
- Get some enterprising individuals to try out the new action
- Close this issue

**Comment by jezdez** [comment]
@josegonzalez @obrassard Thank you!

**Comment by jezdez** [comment]
Woah, that's so cool to see the support for other CI services in ci-docker-image! Thank you  again, @josegonzalez!
