### ISSUE TITLE
Deploy fails after Releasing app with [remote rejected] pre-received hook declined

### ISSUE THREAD

**Issue by tdak** [dokku/dokku#4162]
After updating security patches my Ubuntu 18.04, I wasn't able to deploy the app, which prior to this deployed just fine. 
I installed Dokku fresh, and still getting the same error. 

It does the release without issues and after it says Deploying and it fails with the pre-received hook declined.  Here's the trace: 
[https://gist.github.com/tdak/98b4cb252fef4124f8cf79d93ef1bf8d](Gist)

**Comment by tdak** [comment]
After a lot of testing. I finally got to the point where I decided to remove the Procfile and see what happens. 

Well, it worked. Everything deployed. Why? I started removing lines from the procfile, and only the web one worked. 

What I realized was that my process names had underscores. i.e.  dj_worker, schedule_worker After I renamed htem to worker and scheduler, app deployed. 

Funny thing, everything deployed properly until I did an update yesterday.  

Heroku says that process names should be alphanumeric, so probably underscores aren't allowed. Didn't know that, maybe that's new. 

But worth pointing out.

**Comment by josegonzalez** [comment]
There was a change recently in go-procfile-util that made Procfile parsing stricter (the process type has to be a valid dns label name). This was done before the corresponding change to output errors in Dokku was merged/released. I've made a subsequent change to go-procfile-util to make strict parsing opt-in - and released that! - and that will go out in the next minor release of Dokku.

Note that the reason I made the change was because the process type names are used in Kubernetes service names and Dokku network aliases, so not including it would potentially cause errors.
