### ISSUE TITLE
Express and dokku - Serving Static files

### ISSUE THREAD

**Issue by skokonxd** [dokku/dokku#4164]
Hello, I have nodejs bower application, im trying to deploy it to digitalocean ubuntu vps using dokku image
The problem i have is that express doesnt serve the static files, because dokku saves source as container not in directory that you can access which is a huge problem, I wasted more than 10 hours trying to figure it out but i failed
Im pretty sure the problem is because of the directory
express serve static files in localhost without any problems

Im using lastest dokku version, ubuntu

I will really appreciate any help.

**Comment by josegonzalez** [comment]
Your app runs inside of a container, and nginx does not have direct access to that container (the container changes on every deploy, so not sure how that would work regardless).

Express should be setup to serve the static assets - you can place a CDN in front of the static asset path requests if response time is a major concern. Express certainly has this capability, as otherwise Express apps would not be able to be deployed on Heroku, where the situation is similar.

If you're having further issues with the buildpack,  please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels).
