### ISSUE TITLE
Add Cron support as part of app.json

### ISSUE THREAD

**Issue by fkrauthan** [dokku/dokku#4199]
## Description of feature
Most of the apps I work with have the requirement to run some sort of async/cron task. Examples are

- Sending Emails in the background
- Cleaning up the database
- Generating some sort of reports

#### Expected Results

There should be an easy way to configure multiple cron jobs as part of my application. Dokku should then be able to pick it up and ether internally (or using the system cron daemon) ensure that the jobs are registered (and deregistered).

To make it a flexible system the following methods of executing a cron could be interesting:

- Define a image and run default command
- Define a image and run specified command
- Use the app image and run specified command

**Comment by josegonzalez** [comment]
Couple thoughts:

---

I think it should be a new stanza in the `app.json` file. Heroku has largely abandoned it, so at this point I feel comfortable just adding things there directly.

I'm thinking either `cron` or `scheduled-commands` as the top-level key, but this is up for debate.

```json
{
  "cron": [
      {
        "command": "cron-cmd",
        "schedule": "@daily"
      },
      {
        "command": "another-cron-cmd",
        "schedule": "* * * * *"
      }
  ]
}
```

Why a list of dictionaries? Because the same command might be run on different schedules.

---

The schedule would be [cron-compatible syntax](https://en.wikipedia.org/wiki/Cron), which would be supported by the scheduler plugins via the following methods:

- `docker-local`: Would use distinct crontab files per app.
- `kubernetes`: Supported via [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
- `nomad`: Supported via [Periodic Jobs](https://www.nomadproject.io/docs/job-specification/periodic)

---

The `app.json` file would be extracted during the `pre-deploy` trigger  (allowing folks to generate this during a build) and each schedule would be validated via the [cron](https://github.com/robfig/cron/blob/6a8421bcff44c2a9889075724070baaebf8dcd72/parser.go#L88) golang library. If it fails to parse, we'll bail with the error(s) so that folks can debug them. 

The `post-deploy` step would actually generate the updated cronfile (or whatever, its up to each scheduler plugin to decide what to do here) and push it out.

---

Cron tasks should have the `DYNO` value set to `scheduler.X`, where `X` is a randomly generated ID. Not sure how this might work for Kubernetes/Nomad where we cannot have a dynamic env var without having a daemon that manually submits jobs (ew gross).

---

Should be easy enough to enable or disable a command without a deploy. To do this without requiring an ID, we can generate one based on the combination of the command and the schedule.

- `:logs`: Get the logs for a given task by DYNO value.
- `:list`: Show a list of currently running tasks by ID
- `:report`: Show a report of all tasks associated with an ID
- `:enable`: Disable a given task for an app by the aforementioned ID
- `:disable`: Enable a given task for an app by the aforementioned ID

---

I wonder if we should force the commands to be defined in the `Procfile`. One thing I've always liked about the `Procfile` is that the tooling that exists makes it easy for folks to run those commands locally on virtually any machine, and it also gives a simple entrypoint into all commands that _could_ be run on the server. I don't think we should support both `Procfile` commands _and_ general commands though, as that will make the parsing too annoying.

**Comment by fkrauthan** [comment]
I think a `:run` command can be useful to to simple trigger a one off command (or maybe trigger a cron job more often then usual). Adding it to the Procfile sounds like an interesting idea. I still wonder if in some cases specifying a complete different docker image can be useful (e.g. a image with just `curl` to trigger a private API or some S3 Backup container that just needs access to the DB and env vars but not the app container itself or something like that).

**Comment by josegonzalez** [comment]
I think being able to specify a docker image complicates things:

- What if the image is misspelled and you pull something else?
- What if it isn't tagged and suddenly a dependency disappears?
- If its a cron related to your app, shouldn't your app be able to do the thing? Seems like it would go against 12-factor app
- What if you're on an airgapped network?

I feel as though the utility of an arbitrary image isn't very high, and makes the system more complicated for debugging. I think that any task that can be performed within an app should be tracked in code. I _really_ dislike the idea.

That said, a `:run` command could be nice to do one-off triggers.

**Comment by fkrauthan** [comment]
I agree with it can make things more difficult. But I don't think it goes against 12-factor app. Especially if we are talking about backup or log collection to a remote server (regardless if that potentially can be provided by dokku). This are tasks that my actual app doesn't need to know (therefore I would not add the heavy dependencies for it) but instead would leverage a specialized container that only contains that dependency (which actually is exactly what docker proposes with container separation of concern).

It should be just an optional feature (to eliminate the potential problem with airgapped networks) and a simple cron log or status command could show me if the cron system was not able to pull or run the image I've specified for my cron task. At the end of the day if I really want to use custom containers it would be my responsibility.

In a way like when I submit a custom Dockerfile to dokku I need to ensure that the base image exists etc.

**Comment by josegonzalez** [comment]
If you want to run a command but dont think the code for that command should live in your app, maybe thats a separate app. Allowing alternative images is just not something I want to support by default (though I can probably add a plugin trigger to allow someone to build a plugin that would swap the image out). To me, it just seems like extra code for us to handle without much benefit to the 80% use case.

Regarding whether you should have a specialized container or not, my interpretation of [factor 2](https://12factor.net/dependencies) is that if you need a tool, you need to vendor it.

**Comment by josegonzalez** [comment]
I slimmed down the original work plan to something I could get out of the door for 0.23.0. There are certainly going to be rough edges and system improvements, but I think what is there is good for the 80% use case.
