### ISSUE TITLE
RestApi Accessible from Apps

### ISSUE THREAD

**Issue by litch0** [dokku/dokku#4298]
## Description of problem
I am trying to make an app that will scale my vps based on how many apps I have on dokku, is there any api for this?
Also, Is there any accessible change of configuration that apps can do on dokku like, uploading images, altering user, etc?
Or is this just available trough the command line interface?

**Comment by josegonzalez** [comment]
The closest official thing to that is this: https://github.com/dokku/dokku-api . It isn't maintained by me, but pull requests are welcome.

There is also the [dokku-daemon](https://github.com/dokku/dokku-daemon) project, which is similarly unmaintained by me (pull requests also welcome).

Finally, there are more than a few web ui projects by the community in various states of maintenance located on github - I don't have links available to them at this time.

I'm personally working on an official combination API/UI/Git HTTPS Server/Webhook service, but that won't be open source and will be a paid product. There are no plans to build and maintain an official tool in this capacity.

Hope that helps.

**Comment by litch0** [comment]
It pains me that you won't make it open source, but it is your choice, other than that thank you for the links

**Comment by josegonzalez** [comment]
Really the biggest reason it won't be open source is because it is a support burden. On top of my day job and general life stuff, the Dokku project encompasses a very large surface area. I already have a tough time managing just the core project, and it shows in how the datastore plugins pile issues on until I get bored and take a look.

Adding a UI will increase that burden, and I can only imagine the kinds of issues that will be filed to support specific use cases or workflows. Rather than do that, having it as a closed product that where the folks using it are also supporting it's development will make it worthwhile for me to work on.

**Comment by litch0** [comment]
then would t be better to make a license that doesn't allow redistribution or modification but stills allows user to contribute to your code base, just don't allow then to use without paying?

**Comment by litch0** [comment]
ok
