### ISSUE TITLE
Configuration variables with dots in the key name can not be set

### ISSUE THREAD

**Issue by millsaj** [dokku/dokku#4304]
## Description of problem

We can not set config variables with `config:set` that have a dot (`.`) in the key name. Key names with dots in do seem to be common enough based on the results I got trying to find a similar issue and are legal key names (in bash at least).

### Steps to Reproduce

Assuming you have created an dokku application called `myapp` you can replicate this with any of the following lines.

```
dokku config:set myapp A.Test.Key=Foo
dokku config:set myapp "A.Test.Key=Foo"
dokku config:set myapp "A.Test.Key"=Foo
```

I have been running these on the server - not using one of the clients.
 
#### Actual Results

```
dokku config:set myapp "A.Test.Key=Foo"
 !     Invalid key name: 'A.Test.Key'
```

#### Expected Results

The config variable being set and the application redeploying.

### Additional information

Its seems to be because of the regex in [validateKey in config.go](https://github.com/dokku/dokku/blob/acc206fca7678327b5e4efd6331f675f79f35251/plugins/config/config.go#L166).

**Comment by josegonzalez** [comment]
Dokku only allow keys that are valid Bash environment variables, which can only have ASCII characters, underscores, and cannot begin with a digit.

What is your use case for having a dotted environment variable? I've personally never dealt with an app that had such environment variables.

**Comment by millsaj** [comment]
You are right - it is an invalid bash variable - my bad. 

Despite this it doesn't seem that uncommon in C# to do it this way. This [appsettings](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#appsettingsjson) from microsoft uses one for example. What's weird is that they realised having a `:` in the variable would cause issues and have a [solution](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables) for it - but nothing to help with the dots.

FYI it does seem like its [possible](https://unix.stackexchange.com/a/93533) to set it using `env`.

I'll figure out a way to override this on my end or else raise a PR with the library that wants me to do this then. Thanks for the help!

**Comment by josegonzalez** [comment]
Seems like appsettings actually acknowledges that special characters aren't always allowed, and actually says to [use double-underscore](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables though.

Regardless, I think not supporting these for now is fine, though if enough people ask for the functionality, I could be convinced otherwise.

**Comment by millsaj** [comment]
The double underscore works for when the key requires a `:`. 

A hierarchical scenario like this would translate to the environment variable key name as `An:Example.Key.Name` or as you say `An__Example.Key.Name`.
 
```json
{
  "An": {
    "Example.Key.Name": 12345
  }
}
```

It doesn't seem like I can get away with `An__Example__Key__Name` or `An__Example_Key_Name` by default though.

But yeah not supporting it for now seems like the right call - this isn't dokku's problem to fix.

**Comment by bfontaine** [comment]
> Dokku only allow keys that are valid Bash environment variables

The limit in Bash is due to the fast that it conflates its own variable identifiers and environment variables, but otherwise there’s no technical reason to prevent dots: `env foo.bar=1` works fine, and there are shells that support them.

We are trying to run [this image](https://hub.docker.com/r/exoplatform/elasticsearch) with Dokku and it requires dotted environment variables, such as `node.name=es-1` or `cluster.initial_master_nodes=es-1`. Since I can’t modify the original image and wrapping it would be overkill, I guess there’s no way to run it with Dokku?

**Comment by josegonzalez** [comment]
Dokku isn't a shell, so I think it's fine for us to have arbitrary limits on what is and isn't allowed.

For elasticsearch, IIRC all config can be set via environment variables without dots. See the "Configuring Elasticsearch with Docker" section on this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
