### ISSUE TITLE
dokku git:set APP_NAME keep-git-dir true doesn't keep the git directory

### ISSUE THREAD

**Issue by MattiasOlla** [dokku/dokku#4415]
## Description of problem
I'm deploying an app where it is crucial to track the git information (specifically the git tag or distance to the last tag), so I ran
`dokku git:set APP_NAME keep-git-dir true`
When I then deploy my application (Dockerfile deploy) and exec into the docker container, there is a .git file containing
"gitdir: /home/dokku/APP_NAME/worktrees/dokku-2287-git_build_app_repo.eOJAw2"

This worktree link is obviously outside the container, and thus not accessible to my app. Is there any way to keep the actual .git directory in the app container? Or at least have it accessible in the Dockerfile build step, so the necessary info can be written to a file/environment variable?

**Comment by josegonzalez** [comment]
Interesting, sounds like a bug but we'll need to take a look...

**Comment by josegonzalez** [comment]
I've been looking into this, and it seems that at least internally, git worktree is used mostly for branching. It references the single main git directory as it's normal, and what we are doing doesn't quite allow us to export the git directory.

That said, I managed to cobble together some shell from gitlab documentation that will let us actually rebuild the repository even in quarantine mode. This gives the full git history, including the commit we wish to use, which seems like what we want. I'm going to special case it so that this code path only occurs for worktree-enabled installs when `keep-git-dir=true` in case this somehow impacts other workflows.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. Thanks for reporting.
