### ISSUE TITLE
Support docker swarm as a scheduler

### ISSUE THREAD

**Issue by tdak** [dokku/dokku#4486]
## High level plan

Using a scheduler such as Kubernetes or Nomad is more complex than it needs to be:

- requires separate server entities
- sometimes needs more services installed on top to work properly (consul, vault, metrics server)
- more expensive due to server requirements
- initial setup can be complicated on certain hosting providers

A lightweight cluster method would be great to help avoid these issues. Docker Swarm is built into Docker, and as such is the lightest thing we can do.

What does it need?

- [x] Registry plugin (see #4460 for progress)
  - A future addition could be a way to initialize the registry on a specified scheduler, but we can depend on an external registry for now
- [x] Scheduler plugin (see #4739 for progress)
- [ ] A new scheduler-swarm plugin
  - [ ] An `:init` command that initializes docker swarm
  - [ ] An `:join` command that outputs the command to run to join a node to the cluster
  - [ ] An `:attach-node <node>` command that will ssh-connect to a remote server and run the join command directly
    - [ ] This should take the `node` in the format `ssh://user@host:port`
    - [ ] This should error out with a message when the ssh fails to connect to the remote
  - [ ] An `:init-proxy` command that will initialize the specified proxy service
- [x] The nginx plugin should allow itself to take an arbitrary value for the upstreams.
  - Not sure how we'd call it, but we'd need to allow the scheduler plugin to specify _how_ it should fetch upstreams. Maybe we can allow schedulers to specify a plugin trigger to call?
- [ ] A new nginx docker image that we can use to handle proxying, and then start that in the swarm when `init-proxy` is called with the app configs for apps that are proxied by the swarm scheduler?

Desired workflow:

```shell
# setup the docker registry to point at docker hub (plugin coming in a new dokku version)
dokku registry:set --global server docker.io

# enable pushes
dokku registry:set --global push true

# login to the registry
dokku registry:login registry username password

# set the scheduler (currently its an env var but we'd turn it into a property probably)
dokku scheduler:set --global swarm

# initialize the swarm on your primary dokku instance
dokku scheduler-swarm:init

# initialize the proxy for swarm
# this can use nginx if we follow the plan, but alternative plugins might also implement a swarm-proxy
dokku scheduler-swarm:init-proxy

# attach nodes to the cluster. requires ssh access
dokku scheduler-swarm:attach-node ssh://user@host:port
```

Some random links:

- https://training.play-with-docker.com/swarm-service-discovery/
- https://docs.docker.com/engine/swarm/configs/

## Original Post

Could it be possible to enhance DOKKU_SCALE file to include app names with container types. For example, you could have this:

webserver-1.web=10
webserver-2.web=5

worker-1.worker=5
worker-2.worker=5

So webserver-1 and webserver-2 are app names and so are worker-1 and worker-2. But they are actually four different VMs with Dokku setup on each. 

When you push to each machine,  Dokku could read the dokku_scale file and determine if it should start any containers based on the existence of the matching app name. 

This would make it easy to deploy the same code to different Dokku servers.

**Comment by josegonzalez** [comment]
@tdak would official, core support for any of the following make this request irrelevant?

- Kubernetes (official plugin available)
- Nomad (officiail plugin available)
- ECS
- Swarm

**Comment by tdak** [comment]
I was thinking about it before, but while kubernetes and nomad support are good for those who already use them, for many people all of these tools are overkill.  

I think the beauty of Dokku is its simplicity.  Here's my scenario:

I provision 5 Servers with ansible:  
3 Dokku Instances, 1 Redis and 1 MySQL server

It setups everything I need, all the hosts and all of the connections between. I can even throw in a load balancer, though I have Linode do that for me. 

Then I do the deploy.  Right now, I have a script that does something like this: 

For Each Dokku Server (web1, web2 and worker):
1. Clone my repo into a new folder
2. Copy DOKKU_SCALE_(SERVERNAME) to DOKKU_SCALE 
3. Commit changes
4. Add Dokku Remote URL
5. git push dokku

This allows me to deploy my app to three dokku servers that do different things (two web and worker). 

It works, but it's a bit of a hack. 

If Dokku could be smart about deciding which apps to spawn based on DOKKU_SCALE, then that whole process could be reduced to:

git push dokku-web1
git push dokku-web2
git push dokku-worker

This could make it super easy to deploy stuff not just to production but to QA or deploy a set of features to a particular user set, etc. 

I think this is much easier than kubenertes or nomad.  And I suspect for the majority of people this is a better solution.

**Comment by josegonzalez** [comment]
That seems like a ton of work for me to handle on a scheduler level:

- would need a way to map those scale entry prefixes to a given server
- would still need an external registry
- would not handle a server dying

The alternative is docker swarm, which only requires swarm init (single command) and swarm join (another command), both of which can be shown on the cli for usage. This is probably the easiest scheduler to integrate with (it comes with Docker, and is a single command), is still opt-in (existing users won't see any changes in behavior), and would not require me to write an entire scheduler in shell/golang.

I think swarm might be the right path here as a new scheduler, and I'm imagining something like this to set it up:

```shell
# setup the docker registry to point at docker hub (plugin coming in a new dokku version)
dokku registry:set --global server docker.io

# enable pushes
dokku registry:set --global push true

# login to the registry
dokku registry:login registry username password

# set the scheduler (currently its an env var but we'd turn it into a property probably)
dokku scheduler:set --global swarm

# initialize the swarm on your primary dokku instance
dokku scheduler-swarm:init
```

Then we'd create a single service for each app/process-type combination. Proxying _could_ still be done via nginx, though we'd probably want to do something special for upstreams to work against, and we'd probably want the nginx servers running within the swarm. I say that we should do the same as we do for the kubernetes plugin, and let the plugin handle routing. For kubernetes, that means it does deep integration with `nginx-ingress`, whereas I think for swarm, that could mean just usage of traefik with a command like `dokku scheduler-swarm:init-traefik` or something.

Once you need to add/remove servers, you can use:

```
# attach nodes to the cluster
dokku scheduler-swarm:attach-node $NODE_IP
```

Users wouldn't need to push multiple times, coordinate pushes, or install anything other than docker on new nodes. Users can still run specific services (mysql/postgres) on specific nodes, or drop down to swarm to handle them (if they really want).

I think this is a better plan than having me try to reimplement a scheduler while still keeping BC support for the DOKKU_SCALE file (that file is going away anyhow in favor of formations in `app.json`).

Would the above plan work for you in terms of getting things going?

**Comment by tdak** [comment]
I am going to give swarm a shot.  It's not what I had in mind, though. I think Dokku's setup is perfect as a standalone container manager and scheduler.  For small-to-medium sized applications. 
In my case as in many others, I'd guess, central management of containers is not really need. The complexity doesn't add much value if any.  That's why I love dokku so much. It's almost perfect. :)

**Comment by josegonzalez** [comment]
Yeah the thing is that scheduler complexity has to live somewhere. I can already see the issues with me writing my own and Swarm is fairly close to what you want (true autoscaling) with a small amount of work to add a new node.

let me work on the registry and other plugins this weekend to play around with and see how much easier we can make it since this is definitely an area of interest.

**Comment by johnwilson** [comment]
Hello @josegonzalez. Any progress on this. I'm a novice with docker and swarm but I'm prepared to lend a hand. Also I don't see any sponsorship link for this feature to be added.

**Comment by nickhammond** [comment]
I didn't see this mentioned anywhere in the Dokku issues but I just noticed someone's working on [Swarmlet](https://swarmlet.dev/) which I haven't used but looks intriguing. Says it's heavily inspired by Dokku, I haven't looked around the internals or anything but might be a good collaboration point.

**Comment by josegonzalez** [comment]
For better or worse, having previously looked at it, I don't think there is much to "collaborate" on. When they say inspired, they mean that the general idea of how interactions work for an end user are inspired by dokku, and that they took some ideas (sshcommand, plugn) and rewrote them to fit their needs. There isn't really any common source or anything. It also doesn't look maintained at this time.

If folks want to see this happen, there are two things you can do:

- *Donate to the project:* The monthly contribution goal on [Github Sponsors](https://github.com/sponsors/dokku) has been set to a number that will allow me to both learn about the scheduler and integrate it into Dokku as much as possible, while ensuring I can continue to maintain it into the future.
- *Write the code:* On the off-chance you cannot contribute financially, contributing the `scheduler-swarm` plugin as documented above will help get us off the ground, and then new features can be added as time goes on.

At this time, the only schedulers I'm somewhat interested in are [Kubernetes](https://github.com/dokku/dokku-scheduler-kubernetes) and [Nomad](https://github.com/dokku/dokku-scheduler-nomad) (the former because the plugin is mostly complete, the latter because I am running Nomad locally and use it at my dayjob). The sponsorship goal is there because there is a _ton_ of stuff I'd need to learn about Swarm to do this properly and then an equally large amount I'd need to work on to continue to maintain it going forward.

**Comment by fishnux** [comment]
I would be very careful when it comes to Docker Swarm and nginx. I came away from Caprover precisely due to issues with Swarm's routing mesh and nginx, particularly a hard-timeout of 30 seconds of inactive TCP connections (e.g.: imagine you have a page that does something for 40 seconds, the request would be killed at 30 seconds)

I think Traefik handles this better, but I'm not sure - someone would need to confirm. I think Traefik connects directly to the container's IP addresses rather than using Docker service's virtual IP address, so it bypasses IPVS / routing mesh. Easiest way to confirm is to have a page that answers in 40 seconds:
```php
<?php
sleep(40);
echo "I'm still alive!"
```

**Comment by josegonzalez** [comment]
@fishnux do you have a reference to that 30 second timeout? I wonder if we can build a small dns server - something I've been thinking about with Dokku - to handle resolving dns on ingress for us...

**Comment by fishnux** [comment]
> @fishnux do you have a reference to that 30 second timeout? I wonder if we can build a small dns server - something I've been thinking about with Dokku - to handle resolving dns on ingress for us...

The page that detailed the issue vanished:
https://success.mirantis.com/article/ipvs-connection-timeout-issue

The issue also happens with inactive database connections (e.g.: idle website with PostgreSQL):
https://caprover.com/docs/troubleshooting.html#connection-timeouts

So, Swarm could be used as an orchestrator, but we would not use the routing mesh at all - it's too risky to rely on it.

Good idea on the DNS thing. Actually, Docker Swarm already has a DNS that returns the container's IP addresses, but I believe the services have to be started in a specific way:
> To bypass the routing mesh, you can start a service using DNS Round Robin (DNSRR) mode, by setting the --endpoint-mode flag to dnsrr. You must run your own load balancer in front of the service. A DNS query for the service name on the Docker host returns a list of IP addresses for the nodes running the service. Configure your load balancer to consume this list and balance the traffic across the nodes.

https://docs.docker.com/network/overlay/#bypass-the-routing-mesh-for-a-swarm-service

**Comment by rsyring** [comment]
FWIW, I evaluated Docker Swarm for a short time last year.  For my use case of a handful of servers with relatively minimal complexity, it seemed like it would be a sweet spot.  But, I ran into a few issues when evaluating it and as I looked into the issue history (the public history anyway) I was pretty concerned by what I saw:

![image](https://user-images.githubusercontent.com/109467/158512512-0bd6f57b-82d3-4da8-8a1a-aa623bc33449.png)

So, they've closed 13 issues in 2 years!  And if you look at the open issues, you get the sense that it's kind of a graveyard.  Lots of bug reports for basic functionality failing and very little communication.  The commit history is, similarly, pretty scant for something that people are running production workloads on.  IMO, [the purchase of Docker by Mirantis put a nail in the coffin of Docker Swarm](https://www.reddit.com/r/docker/comments/ituysl/why_people_are_saying_docker_swarm_is_in_life/).

I'm not complaining, they've provided a lot of functionality gratis and that's commendable.  Just thought it might be worth considering whether or not Docker Swarm has the longevity and reliability to justify putting effort into integrating it.

**Comment by dirkzado** [comment]
Are there any news regarding that docker swarm topic? Will it be continued?

https://github.com/moby/swarmkit

https://dockerlabs.collabnix.com/intermediate/swarm/difference-between-docker-swarm-vs-swarm-mode-vs-swarmkit.html

**Comment by josegonzalez** [comment]
I’m going to close this. The work to support this would be significant and Swarm hasn’t really seen any development over the past few years.

With the release of Dolly 0.33.x - with [k3s](https://dokku.com/blog/2024/dokku-0.33.0/) support - I think Dokku now provides a great multi-server experience that is at least as good (if not better) than what Swarm support would have provided.

If anyone is interested in sponsoring this functionality, please reach out. Otherwise, going to close this for now.

**Comment by rsyring** [comment]
> With the release of Dolly 0.33.x

I assume that's a typo and you meant Dokku 0.33.x.

**Comment by josegonzalez** [comment]
You'd think my phone would learn the word at this point 😂
