### ISSUE TITLE
How to cleanly uninstall dokku?

### ISSUE THREAD

**Issue by saidimu** [dokku/dokku#449]
Aside from manually undoing the [`Makefile`](https://github.com/progrium/dokku/blob/master/Makefile)?

**Comment by marothstein** [comment]
@josegonzalez Just curious if there's been any progress toward an uninstaller?

**Comment by josegonzalez** [comment]
If you are using the official digital ocean image, you can just `apt-get remove dokku`. A future release will make this the norm.

It's almost certainly easier to just build a new vm - your infrastructure should be replaceable or you're doing it wrong. While you may be upset at the above answer, them's the breaks I guess. I'd be happy to help users automate their infrastructure setup if they are at the point where playing with dokku can't be done on a server that can be thrown away.

**Comment by marothstein** [comment]
@josegonzalez I figured as much, but thought I might as well ask. 

Thanks you for the response!

**Comment by kavefish** [comment]
> It's almost certainly easier to just build a new vm - your infrastructure should be replaceable or you're doing it wrong.

Wow. I guess that rules out dokku for use in anywhere but a VM. So much for using it to test on my dev box. :(

**Comment by josegonzalez** [comment]
If you wish to uninstall dokku and have installed it via the debian packages, just `apt-get remove dokku`. This is the default method of installation - the `bootstrap.sh` script simply adds the required apt repos and calls the correct `apt-get install` commands.

If you install from source, you're going to have to manually uninstall it - and thus you should only be using that method in a vm or a throw-away server. That method is now non-default and you have to do extra work to do this. I think it's reasonable for us to not provide a way to clean this up, since it's meant for testing/development purposes.

**Comment by paulwalker** [comment]
@josegonzalez understood, but it would be at least nice to document the commands needed to manually uninstall. Thanks.

**Comment by josegonzalez** [comment]
@paulwalker what do you mean by "manually uninstall"?

**Comment by paulwalker** [comment]
lol, i don't know...I was quoting you ;-)...`If you install from source, you're going to have to manually uninstall it`

**Comment by josegonzalez** [comment]
Yeah, I'm saying that if you manually install it, you're on your own. That's not the recommended way of installation.

It's kinda like asking me how to install it on freebsd. I'm sure it'll work - they have docker there, right? - but as that's not documented by us, I'm not going to support anything about it.

In this case, if you install dokku, the `bootstrap.sh` script will default to using a package *unless* you specify a specific branch, in which case it'll do "some stuff" to your system. You have to go out of your way to install from source, and as such, you're going to have to go out of your way to uninstall from source.

You can always upgrade to a package-based installation, at which point you can them `apt-get remove` stuff like normal.

**Comment by paulwalker** [comment]
ok, i was confusing manually installation with using bootstrap.sh, but didn't read carefully enough that it is just using package installation. i used `apt-get remove dokku` but still had nginx listening on certain ports, etc...

**Comment by josegonzalez** [comment]
As well, like I said before, there is a lot of random bash going on in the `Makefile`-based installation stuff. I don't know of a method to do `make install | reverse`, so I legitimately cannot offer you a method of uninstallation here. Hence why we offer packages.

Regarding this nginx thing, `apt-get remove dokku` only removes dokku. You'll still have the packages dokku depends on running, and removing dokku won't remove user data - that's not the debian way, you need to purge for that - so you may need to do extra work to get it nice and tidy.

If you'd like to contribute docs on completely removing dokku, I'd be happy to merge them.

For anyone complaining about not being able to try it out on a test box, we supply a `Vagrantfile` with this repository and instructions on it's usage. You can then test it out on a throwaway VM before committing to using it. Or if you want to try it out on a cloud provider, we provide images/integrations where possible and point them out in our [documentation](http://dokku.viewdocs.io/dokku/). I highly suggest one of these two routes if you're just fucking about with dokku.

**Comment by paulwalker** [comment]
Thanks @josegonzalez, my initial suggestion was based on my false reading. The nice thing with open source is...that we are adding documentation here ;-). I'm testing the viability on Linode right now and look forward to collaborating with anyone else working w/ the Linode/Dokku combo :-).

**Comment by rwatts3** [comment]
Interesting. 

I was shocked at the response from @josegonzalez 

> If you install from source, you're going to have to manually uninstall it - and thus you should only be using that method in a vm or a throw-away server. That method is now non-default and you have to do extra work to do this. I think it's reasonable for us to not provide a way to clean this up, since it's meant for testing/development purposes.

I'm curious as to how you came to that conclusion with it not being reasonable for you to clean up since it's for testing/development purposes.

When writing software no matter testing, beta, production you should always have a clear path and a clear way out of that path. This sounds to me like cowboy code. Just write code into the wind and see where it takes you. Certainly not a priority as we are less than half a year away from 3 years. 

Also I must say i'm not too impressed with the lack of professionalism in the language from a core contributor. I was actually looking into assisting with the development of this project until I came across this thread. I'm sure a great deal of other developers in the community probably felt the same. Developers typically don't look for software to ***** about, and destroy their systems. They generally look for software that works and have a supportive core team. Hence the difference between dokku and heroku.

**Comment by michaelshobbs** [comment]
@rwatts3 While we appreciate you input on a 3 year old issue, what might be more useful is a PR helping to solve the problem. We are always looking for solid contributions.

**Comment by webknjaz** [comment]
Smth like:
```shell
sudo apt-get purge -yf dokku nginx nginx-common docker-engine herokuish && sudo apt autoremove -yf && sudo rm -rf /var/lib/dokku/ /home/dokku/ /usr/bin/dokku /var/www/html/
```

**Comment by josegonzalez** [comment]
This is already documented on our docs site.
