### ISSUE TITLE
Dokku and cron jobs

### ISSUE THREAD

**Issue by vladimirnani** [dokku/dokku#450]
Is there a possibility to manage a cron jobs using dokku?

**Comment by Zren** [comment]
# NOTICE

If you use `dokku run <app> <command>` inside cron, make sure to use the `--rm-container` (or `--rm`) flag to automatically remove the container afterwards (like so `dokku --rm run <app> <command>`. Otherwise you'll find yourself running out of disk space.

**Comment by henrik** [comment]
Thank you, @Zren. Other things that are good to know (I just set this up):

**You [may need to specify the full path](http://askubuntu.com/a/47801/443378) to dokku.** I did `which dokku` to find out mine is at `/usr/local/bin/dokku`. Thus, my crontab entry has `/usr/local/bin/dokku --rm run my-app my-command`.

**If it still doesn't work, [make sure cron mails you](http://askubuntu.com/a/646831/443378) any STDOUT or STDERR output.** It doesn't need to go to a "real" email address. I did `sudo apt-get install postfix`, chose "Local" during setup, then `sudo tail -f /var/mail/root` to read it (replace "root" with another username if applicable).

**Comment by josegonzalez** [comment]
@henrik would be great if you could contribute some docs on getting cronjobs running. I'm sure other users would benefit from doing so :)

**Comment by henrik** [comment]
@josegonzalez That's a good idea! I'll consider it. Would be nice to contribute back :)

**Comment by felixyz** [comment]
@henrik Alternatively (?), one can put this at the top of ones crontab file:

`````
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
`````

**Comment by felixyz** [comment]
Mostly for the sake of documentation for others looking to do this, here is some notes about my setup:
* Like @henrik, I configured cron to email me with output from jobs (in my case, I want actual emails sent so I get warnings if anything fails)
* However, since I only want to hear from cron if something goes wrong, I installed [cronic](http://habilis.net/cronic/) and run my (Ruby rake) jobs like this:
`*/10 * * * * cronic dokku --rm run my-app bundle exec rake schedule_stuff`
I now get emails if the job fails, but not otherwise.
* Another point discussed above is whether you need to invoke dokku with a full path. In my experience, setting up the cron jobs as the dokku user, I needed a fully qualified path, but as root (and extending the path as described in my previous comment) I didn't. Not sure what is recommended?

Nothing fancy, but might save someone else a bit of experimentation.

**Comment by josegonzalez** [comment]
Note: while dokku currently *does not* manage cron, we *do* have official documentation on how to use dokku in conjunction with cron [here](http://dokku.viewdocs.io/dokku/deployment/one-off-processes/).

**Comment by Phunky** [comment]
*cough* which has move [here](http://dokku.viewdocs.io/dokku/processes/one-off-tasks/) 

_For those that stumble on this thread via google_

**Comment by josegonzalez** [comment]
Wow ancient thread.

we now support managing cron tasks: http://dokku.viewdocs.io/dokku/processes/scheduled-cron-tasks/

**Comment by Phunky** [comment]
Sorry for the necro, but thought best to update it as Google led me this way.

**Comment by OpticNectar** [comment]
Can someone please clarify how the Scheduled Cron Tasks work? I'm trying to run a rails rake task via the cron, but it doesn't run. The examples don't really show if you're supposed to use `dokku` in the command or how exactly that works. I also couldn't find any examples online.

My app.json

```
{
    "cron": [{
        "command": "rake my_task:import",
        "schedule": "@daily"
    }]
}
```

**Comment by josegonzalez** [comment]
@OpticNectar mind filing a new issue for this? I can help there :)
