### ISSUE TITLE
Global cron commands

### ISSUE THREAD

**Issue by safeforge** [dokku/dokku#4518]
Actually seems to be impossible to manage custom jobs in the dokku's cron file, would be great to have a global support which permits to handle custom global configuration. As suggested by @josegonzalez on slack channel a potential syntax could be 

```sh
# add a command to the global list
dokku cron:add "@daily:/home/dokku/.bin/cleanup-job"

# show the global commands, which shows the cron task ID
dokku cron:list --global

# remove a global task
dokku cron:remove CRON_ID
```

**Comment by josegonzalez** [comment]
Thinking about this more, I feel like this is a good candidate for a non-core plugin. The reason being is that core plugins should be a "safe" porcelain over system commands, and this could expose the ability basically run anything on the system by users (trusted or otherwise).

Such a plugin could:

- track commands via the `properties` system (as a list of entries)
- expose the list via the `cron-entries` plugin trigger (which has a format of `$SCHEDULE;$FULL_COMMAND;$ARBITRARY_DATA`)
- execute the `cron-write` trigger whenever the list of commands is added or removed

I'm going to close this for now given that I don't think it's the "safe" way to do things at this time, but if anyone wants to work on such a plugin, please feel free to reach out, as I am more than happy to guide you through it (also feel free to [sponsor the work](https://github.com/dokku/.github/blob/master/SPONSORING.md)).
