### ISSUE TITLE
Dokku redirects to the wrong domain when server is not ready

### ISSUE THREAD

**Issue by jamesst20** [dokku/dokku#4529]
## Description of problem

I have multiple apps (6) on my Dokku machine. When I reboot it, it seems that some domains starts rendering other domain that might just be faster to start up. After a minute or 2, all domains render their associated application.

Example

```
# dokku domains:report
# Please note I renamed domains, but some domain name were repetitive and I made the effort to reuse the same
# replacement name where necessary in case it matters.
=====> something domains information
       Domains app enabled:           true
       Domains app vhosts:            something.abc.com
       Domains global enabled:        true
       Domains global vhosts:         server-name
=====> errbit domains information
       Domains app enabled:           true
       Domains app vhosts:            errbit.server-name errbit.something.net
       Domains global enabled:        true
       Domains global vhosts:         server-name
=====> myapp domains information
       Domains app enabled:           true
       Domains app vhosts:            myapp.demo myapp.mydomain.com
       Domains global enabled:        true
       Domains global vhosts:         server-name
=====> something domains information
       Domains app enabled:           true
       Domains app vhosts:            something.net
       Domains global enabled:        true
       Domains global vhosts:         server-name
=====> mydomain-backend domains information
       Domains app enabled:           true
       Domains app vhosts:            server.mydomain.com
       Domains global enabled:        true
       Domains global vhosts:         server-name
=====> mydomain-frontend domains information
       Domains app enabled:           true
       Domains app vhosts:            mydomain.com
       Domains global enabled:        true
       Domains global vhosts:         server-name
```

### How reproducible

1. Visit something.abc.com and something.net. They both render their associated app.
2. Reboot
3. Visit something.abc.com and refresh until something.abc.com renders. Then try something.net and I notice it renders the same content as something.abc.com
4. I wait 1-2 minutes
5. Visit something.abc.com and something.net. They both render their associated app again.

#### Actual Results

something.net rendered something.abc.com (note: it doesn't make any url redirect).

#### Expected Results

I would expect to render nothing or an error until the server is up and running.

<-- Please replace APP_NAME with the name of your app -->

### Versions
dokku version 0.24.3

### Extra informations

1. My domains are behind cloudflare.
2. I did not customize any nginx settings.
3. Everything is deployed as-is using 'git push dokku master'. No extra settings changed except linking to Postgres/Redis
4. I did `dokku certs:generate app_name` for all my apps to use full SSL encryption with cloudflare
5. Most of my applications are Ruby On Rails app deployed with default ruby build pack

**Comment by josegonzalez** [comment]
Unfortunately there isn't much we can do here. Docker containers don't retain ip addresses across boots (if they do, its by chance). Restarting docker has the same effect. They made this change a long time ago.

We built the `docker-event-listener` to try and combat this - it rebuilds apps when the containers get out of sync with the ip addresses we expect. On boot, we also call `ps:restore`, which detects changes and attempts to rebuild nginx configs. Unfortunately, we sometimes need to rebuild apps on boot as well, so this may take a few minutes.

Finally, the real turd here is that nginx just decides to serve all requests from the first domain in lexigraphical if there is no matching virtual host. You could set a "default" for port 80, but not for SSL...

The only "fix" would be to switch to another proxy, but thats kinda untenable for Dokku Core (also, nginx is fine otherwise). That said, I've always wanted to make an "appliance" vhost plugin, so you could in theory configure it via docker labels but also swap out nginx for like... caddy or traefik. Would be great to have some sponsorship to work on, probably ~5 hours of work total tbh.

Regardless, there isn't much we can do here, it's kinda just a byproduct of how nginx and docker work :(

Hope this explains things.
