### ISSUE TITLE
git:from-image no changes detected

### ISSUE THREAD

**Issue by cpanderson** [dokku/dokku#4620]
Trying to understand the new git:from-image. The docs don't go into much detail with this. When I pull down changes to an existing image and attempt to deploy it dokku says "no changes detected".  Here's my procedure...

`docker pull <image name from remote registry>`
`dokku git:from-image <app> <image name from remote registry>`

-----> Generating build context
       Setting Dockerfile
-----> Updating git repository with specified build context
 !     No changes detected, skipping git commit
 !     Call 'ps:rebuild' on app to rebuild the app from existing source

If I do ps:rebuild that works fine. If I delete the image and pull down a fresh company that works as well. Am I not understanding the procedure correctly or ?

I am not comfortable putting all the details of the dokku report in this public space without redacting it. I can provide redacted snippets if required. Thanks for your help. Loving Dokku!

**Comment by cpanderson** [comment]
Oh geez...I didn't see the discussions area...is that something new on Github? I will start there.

**Comment by josegonzalez** [comment]
From the docs:

> Triggering a build with the same arguments multiple times will result in Dokku exiting 0 early as there will be no changes detected.

That means if the image tag doesn't change, it is detected as the same image. I'm assuming that is what you are doing. In that case, you can add the `--pull` flag to the app via the docker-options plugin and then always deploy via `ps:rebuild`.

**Comment by cpanderson** [comment]
So it's based on the tag? I thought it should do a SHA check or something. Ok thank you for responding and so quickly!

**Comment by josegonzalez** [comment]
No, it has no way of knowing that the image tag changed upstream without pre-pulling it and comparing with an existing (which might be nice but potentially a waste of bandwidth if the image is the same).

Your alternative is to use the sha256 digest of the image as the tag, which will always change if the underlying image changes: https://rockbag.medium.com/why-you-should-pin-your-docker-images-with-sha-instead-of-tags-fd132443b8a6

**Comment by cpanderson** [comment]
Perhaps that could be an option? Does it look for a local image first? Anyways, this doesn't need to be discussed here. Thanks again!

**Comment by josegonzalez** [comment]
It looks to see if there will be anything from the commit of the dockerfile resulting from the call. If there is no change, then there will be no commit, and therefore nothing to build.

If anything, maybe:

- Get the current 256 digest via `docker inspect`
- Get the updated via [curl request](https://stackoverflow.com/a/39376254/1515875) - Could we use skopeo or something to do this? How do we get the creds?
- Switch the sha256 digest in instead of the tag

But that results in not what the user specified when running `git:from-image`, so it'll be surprising at minimum when they inspect what got built.

We could alternatively inject the `--pull` flag when running `git:from-image`, but that doesn't fix the repo commit issue. Injecting the current timestamp might help with the commit issue, but now we're effectively never caching anything.

I think that the better choice here is to just use a digest and not attempt to work around this.
