### ISSUE TITLE
Feature suggestion: `ssh` proxy mode

### ISSUE THREAD

**Issue by radiospiel** [dokku/dokku#4795]
When managing Docker-based applications it could be handy to allow ssh proxies to automatically tunnel SSH connections to the respective service. This would have to

1. expose a container's SSH port on the host's `localhost` interface; 
2. (create and) use a user account on the host machine per proxied container, which would then always tunnel to the exposed SSH port.
3. somehow synchronize access keys between container(s) and host. A key allowing access in the container must be known to the host SSH demon and probably also vice versa. 
 
I don't know how feasible this is, what corner cases exist, and also how useful this is generally. It strides away quite a bit from dokku being a pure hosting service for HTTP applications. However, it could be useful in the context of managing docker-based applications; I just set up a `gitea` application, and went for the easier option of directly exposing gitea`s SSH port on the host machine at port 2222 or so. gitea has some hints on their "installation with dokku" guide: https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough

**Comment by josegonzalez** [comment]
This would require having tcp proxying. While [it is possible with nginx](https://www.howtoforge.com/reverse-proxy-for-https-ssh-and-mysql-mariadb-using-nginx/)  - and there is a plugin [here](https://github.com/rvanlaar/dokku-nginx-stream) that handles streaming proxies - I'm personally not interested in the work required to get this into the core.

If you or others would like to make a PR for this, I would definitely take a look and merge (assuming it works and has tests) but otherwise I'm going to close this as I'm not interested in working on this myself.

**Comment by radiospiel** [comment]
fair enough - thanks for looking at this :+1:
