### ISSUE TITLE
Dokku stop apps and server after every 14-15 days and it automatically restarts after having downtime of 20-25 minutes

### ISSUE THREAD

**Issue by RohitVenturit** [dokku/dokku#4925]
I am using dokku version 0.19.7, I am having a strange issue. Dokku is installed on Ubuntu  16.04.6 LTS (GNU/Linux 4.4.0-1128-aws x86_64) . All apps gets down after some every 14-15 days and it automatically restarts after having downtime of 20-25 minutes. It is observed at RAM utilization get keeping down with every deployment. How to know whats the exact reason for such down?
I am using 32 GB RAM, 108 GB free storage, total 5 apps running, out of them 4 apps using dokku elasticsearch and dokku redis services.
Please help to know whats the exact reason for such a down?

**Comment by josegonzalez** [comment]
A few things:

- The only background thing we have that restarts processes is the `dokku-event-listener` process. Older versions of this would restart an app if any process in the app failed, but if that is upgraded to 0.10.1, it only does a restart if the web process dies. However, none of this is related to any number of days, but only when an app dies.
- If your memory is decreasing all the time, you probably have a memory leak and your apps are being oomkilled. Dokku then restarts them via dokku-restore. You can check this in your `/var/log/syslog` file.
- We no longer support Ubuntu 16.04, but it should work the same way as latest Dokku. That said, I don't think you can even upgrade to a newer version since we've removed it from our package repositories.

I'm going to close this. Your best bet is to get everything updated by:

- changing the word `xenial` in `/etc/apt/sources.list.d/dokku.list` to `focal`
- running `sudo apt-get update`
- running `sudo apt-install dokku-update`
- running `sudo dokku-update run`

And then checking your syslog for oomkills after the fact.

**Comment by RohitVenturit** [comment]
@josegonzalez I have checked /var/log/syslog and I can see this:
### **_dockerd[1299]: time="2021-11-16T05:28:09.654237987Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
 docker0: port 7(veth94f49b2) entered disabled state
 vethc7b44b3: renamed from eth0
 docker0: port 7(veth94f49b2) entered disabled state
 device veth94f49b2 left promiscuous mode
 docker0: port 7(veth94f49b2) entered disabled state
 dockerd[1299]: time="2021-11-16T05:28:09.754865127Z" level=warning msg="f8efeb109fd933c5b4f28d28bcbd71e5c8822fb09469bccd5a5f18a88d431db3 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/f8efeb109fd933c5b4f28d28bcbd71e5c8822fb09469bccd5a5f18a88d431db3/mounts/shm, flags: 0x2: no such file or directory"
CRON[22570]: (CRON) info (No MTA installed, discarding output)_**

same issue someone reported here https://forums.docker.com/t/failed-to-unmount-ipc/86104. This error is getting logged every 2 minutes along with cronjob. Is this causing app and server to down?

**Comment by josegonzalez** [comment]
Maybe it is a docker bug. I don't even know what version of docker you are running because you didn't fill out the issue template.

At this point, it definitely doesn't sound like something to do with Dokku, but rather Docker (or maybe your OS). I'd try updating both and see if that gets rid of the issue.

**Comment by RohitVenturit** [comment]
thanks @josegonzalez for you reply,
so to update these 3 commands would be enough?
sudo apt-get update
sudo apt-install dokku-update
sudo dokku-update run

**Comment by josegonzalez** [comment]
That will only update Dokku, it doesn't do anything about docker or your system OS. You'll need to update those two to get things going again.

**Comment by RohitVenturit** [comment]
ok @josegonzalez how do I update docker ?

**Comment by josegonzalez** [comment]
I would try updating docker (which again, because you havent provided any of the information in the issue template, I can't really advise on) first.

Checkout the docker.com website for more information on that.

**Comment by josegonzalez** [comment]
Maybe useful: https://docs.docker.com/engine/install/ubuntu/

**Comment by RohitVenturit** [comment]
ok and to update OS , do-release-upgrade will do?

**Comment by josegonzalez** [comment]
Try just updating docker and see if that works.

**Comment by RohitVenturit** [comment]
ok sure BTW you mentioned I have not provided any of the information in the issue template.  What is expected here?

**Comment by josegonzalez** [comment]
When you opened up a ticket, there was a bunch of text that asked you to fill out info. You deleted all of that and put in what you thought was necessary to investigate.

Here is the link to the issue template: https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md

As I said before, this sounds like a docker bug, not Dokku, so if upgrading Docker does not resolve it, I would recommend filing a ticket with them and seeing if they can help you figure out what is going on.
