### ISSUE TITLE
Bug clearing cache after setting the stack globally

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#4990]
```
root@server:~# dokku buildpacks:set-property --global stack gliderlabs/herokuish:latest-18
=====> Setting stack to gliderlabs/herokuish:latest-18
flag provided but not defined: -global
Usage of /var/lib/dokku/plugins/enabled/repo/post-stack-set:
2022/01/05 15:55:21 exit status 2
 !     exit status 1
```

We should iterate over all apps if the `--global` flag is set here: https://github.com/dokku/dokku/blob/be01d2f7ec9903b6d0a96b1a0693c23cb82cb4ad/plugins/buildpacks/subcommands.go#L150

**Comment by elhu** [comment]
I'm interested in providing a PR for that one if you are looking for contributions!

**Comment by josegonzalez** [comment]
Always looking for contributions!

**Comment by elhu** [comment]
So... I've created a [PR](https://github.com/elhu/dokku/pull/1) that I think might work, but I'm stuck when it comes to testing it.
I was following the instructions here https://dokku.com/docs/getting-started/install/vagrant/, but turns out VirtualBox doesn't support the new ARM Apple CPUs.

Is it possible to setup Circle CI on a fork? From what I can tell, the config in `.circleci/config.yml` only contains a dummy config.

**Comment by josegonzalez** [comment]
Ah I see what happened. @elhu can you open your MR against our repo, not your own?
