### ISSUE TITLE
Add `DOKKU_APP_DOMAIN` variable to app environment

### ISSUE THREAD

**Issue by gridsystem** [dokku/dokku#5135]
### Description of feature

Add `DOKKU_APP_DOMAIN` environment variable for apps to use, similar to the existing `DOKKU_APP_NAME`.

This would be the full URL of the app, either `myapp.dokku.me` or `myapp.com`.

This would be useful for code which isn't able to find out it's own domain, for instance Strapi CMS needs a specific config variable for its email templates to work.

This can obviously be set manually, but to have it automatically set by Dokku would be very cool.

**Comment by josegonzalez** [comment]
I don't think we can/should do this. Some apps have multiple domains, and I'd rather not inject more environment variables into the defaults that aren't portable (we're moving away from using env vars for Dokku config).

The other thing is that domain changes would then necessitate an app rebuild, which isn't great because now the process takes a lot longer.

**Comment by gridsystem** [comment]
All makes perfect sense.

**Comment by josegonzalez** [comment]
Going to close this for now, but thanks for filing the issue and getting some conversation going on it :)
