### ISSUE TITLE
Nested storage directories do not work

### ISSUE THREAD

**Issue by AxelTheGerman** [dokku/dokku#5182]
### Description of problem

The storage plugin provides `dokku storage:ensure-directory folder-name` which is awesome!

But I need to mount 2 different folders into my app - one for the database (playing around with sqlite) and one for other storage.

I was planning to have `path/to/storage/app-name/db` and `path/to/storage/app-name/media` or something like that.

Unfortunately `dokku storage:ensure-directory app-name/db` gives an error `Directory can only contain the following set of characters: [A-Za-z0-9_-]` coming from https://github.com/dokku/dokku/blob/af88aabfb63e45784813d0c505be7f2d6b55c01f/plugins/storage/internal-functions#L38

What would be the best way around this?

- create `app-name--db` and `app-name--media` and relying on not having another app with that name (unlikely I know)
- add an optional second parameter to the command to allow one level of nesting
- open up the command to include a `/` and allow any kind of nesting

Thank you for all your work on Dokku!

### Steps to reproduce

`dokku storage:ensure-directory a/b`

> Directory can only contain the following set of characters: [A-Za-z0-9_-]

### dokku report $APP_NAME

n/a

### Other

PS: I also wonder if a plugin I am writing can autoamtically create storage directories and mounts for an app - I see that this function is in `internal-functions` (but storage:mount seems to be just a wrapper around adding docker options)

**Comment by josegonzalez** [comment]
You can manually create the directory via `mkdir`. The `storage;ensure-directory` subcommand is a helper command that takes a single subpath. It's effectively used for cases where your app only has a single storage mount necessary, so the directory you are ensuring would be the app name. If you need two, you'll need to name them differently.

I don't want to expand the argument to include `/` because it'll cause issues if someone tries to call ensure-directory with `app-name` and `app-name/subpath` with diffferent chown arguments (I'd hope it won't but it'll definitely happen!).

It might make sense to align the regex for the directory and app names in that case.

**Comment by AxelTheGerman** [comment]
Thank you Jose I really appreciate your input on this.

I definitely created directories myself before this helper existed and I understand the hesitance of relaxing the regex. Nesting might lead to weird scenarios as well.

I guess I'm gonna go with `--suffix` as I guess most people don't use `--` in their app names and folders for each app are still listed together. Or with a `plugin-name--` prefix.

Closing this for now
