### ISSUE TITLE
Allow apps to expose ports internally

### ISSUE THREAD

**Issue by thomasfedb** [dokku/dokku#5253]
### Description of feature

I have deployed a group of services, and am looking for a way to allow connects between services. Would be excellent to be able to access other containers using `<PROC>.<APP>.dokku.internal` or similar, for example `web.wordpress.dokku.internal`. There would probably also need to be a way to expose particular ports.

**Comment by thomasfedb** [comment]
Hey @josegonzalez, I've read that page and to be honest find it fairly confusing.

What's not clear to me is if attaching my app to a network that I create will have an effect on how that app is proxied? That is to say, is there a 'default' network that needs to be attached for NGINX to proxy requests to my app?

The way that apps are attached to a network by 'setting' various properties seems unlike how other resources are 'linked' to apps. Does this mean an app can only be attached to one network?

**Comment by josegonzalez** [comment]
The impact on any linked containers depends on the network you use.

- Setting the `initial` network will break all linking to all service plugins, as the plugins depend on the default `bridge` network.
    - I believe it also breaks nginx routing if you don't allow requests from the host to your initial network (which is basically only bridge networks). I vaguely recall this from someone asking in chat about it.
    - The use case here is if you need internal-only services and are happy using custom docker networks.
- If you use any of the other network settings (`attach-post-create` and `attach-post-deploy`), network requests from nginx will be fine.
- Usually the network folks want is `attach-post-deploy` (for web processes, this makes it so they have to start successffully first in order to be available on the network).
- Apps can only be attached to one network per setting. Do you have a use-case requiring multiple networks?
