### ISSUE TITLE
Attach multiple networks to container

### ISSUE THREAD

**Issue by byrnedo** [dokku/dokku#5314]
### Description of feature

I might be missing how to do this but I couldn't figure it out.

I want to be able to attach multiple networks to a container.

AFAICT `dokku network:set <APP> <NETWORK>` replaces the attached network every time.

**Comment by josegonzalez** [comment]
What is the use case for multiple network attachments?

**Comment by byrnedo** [comment]
I have an nginx container that I want to be able to talk to 2 other containers, each in their own network.

**Comment by josegonzalez** [comment]
What is the nginx container doing in your case that you can't use the existing nginx frontend, and why are each of the apps in separate networks?

**Comment by josegonzalez** [comment]
@byrnedo if you can provide some justification on your end, I'm happy to work on this sort of functionality :)

**Comment by josegonzalez** [comment]
Hmmm I wonder what the correct way to do this would be. Maybe `networks:set` should take a comma-separated list of networks? Or maybe we also support `networks:add` and `networks:remove`?

**Comment by josegonzalez** [comment]
Yeah okay I think this is what we want:

```shell
# add one or more networks
dokku networks:add <app> <key> <network> [<network> ...]

# clear out all networks
dokku networks:clear <app> <key>

# remove one or more networks
dokku networks:remove <app> <key> <network> [<network> ...]

# set one or more networks
dokku networks:set <app> <key> <network> [<network> ...]
```

Note that all the networks must exist prior to being added/removed.

**Comment by hiepxanh** [comment]
my case is, I have 3 container stacks, each stack will create a new network:
- stack network 1: database app 1
- stack network 2:  database app 2 
- stack network 3:  common stack (which includes: redis, mail and some other container)

so dokku app 1 need join 2 stack networks: 
- connect to network 1: get data from database app 1
- connect to network 2: get data form common stack (redis stack)

dokku app 2 join database 2 and common stack (redis stack)

this use will be more effect since we can reduce duplicate container.

- Why I do not use dokku service instead? it great, but I prefer using stack, since I have more control and easy to work with other application build from docker compose


![image](https://user-images.githubusercontent.com/16970990/227476511-b8af7836-72a5-4406-a21a-3ab7c82a5570.png)

**Comment by byrnedo** [comment]
@josegonzalez sorry for not getting back to you.

My nginx container is a modded openresty proxy that I like to use since it's platform agnostic, as in, if I host this on bare metal or just using docker-compose or swarm then it'll just work.

I guess the justification would be that having containers on serveral networks would be common enough. In my case I'm reverse proxying several different apps that are isolated from each other, and I want to avoid ability to cross-talk.

I think your proposal looks good with having a vararg list of networks :+1:

Appreciate the effort you put in to Dokku and thanks for being patient on getting feedback, a lot of people would have just closed this PR 😛

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
