### ISSUE TITLE
Disable remote logs on git push dokku

### ISSUE THREAD

**Issue by nomanbiniqbal** [dokku/dokku#5330]
### Description of feature

Problem is my app take too much time on building and CI pipelines have limited build time available.
I really wish that feature already available as one is push the code it dont show me any remote process and just leave the connection. 
so i can connect @https://github.com/ribot/dokku-slack to get notifications on deployment status and can store logs some place or something like that.

**Comment by josegonzalez** [comment]
I don't think I'm going to implement this, as any changes to a git repository need to have the connection open. It's basically impossible to build without a daemon on the Dokku host that gets some sort of webhook notification and builds the app in the background.

That sort of functionality - event-based builds - will be a feature of Dokku Pro, but due to how Dokku OSS works, will not be a feature of the project here.
