### ISSUE TITLE
Configure an app with a file in version control

### ISSUE THREAD

**Issue by tadamcz** [dokku/dokku#5375]
### Description of feature

If I understand correctly, some configurations can currently only be set using the Dokku CLI on the host machine (e.g. `dokku domains:set example-app example.com`). It would be nice to be able to set these using a file committed to git as well (for "infrastructure as code"). The file could be `.dokku` in the root of the project, for example. Or is this already possible, and I missed it in the docs? 

For an example of how this should work, the aim would be that projects could be re-deployed identically on a new server by in approximately three steps: 

1. installing Dokku on the new server
2. adding the new server as a remote (called `dokku`, say) and doing `git push dokku`
3. pointing any DNS records to the new server

Right now this is a much more manual process, plus I have to remember, or manually check, or manually document, the configuration for each app. 

You'd have to think about how to handle conflicts. I think a decent choice to keep things simple would be to disallow the CLI from making any changes to settings that are set by the `.dokku` file, while informing the user of this with an appropriate error message.

**Comment by odscjames** [comment]
I'm also interested in this - and I'm also interested in being able to attach resources like databases and storage this way.

However I do wonder if different people's use cases and work flows are going to be different enough that it will be hard to write something complete enough here - I think lots of user needs need to be gathered before considering this more. Given that, I wonder if plugins are the way to go for a bit, as then we can check the requirements have been correctly worked out.  

(For instance, I have slightly different use cases when I'm wanting my main branch to deploy to my live server, and any work branch to deploy to a dev server. simple example - I sometimes want a HTTP username/password combo put on any dev apps using the http-auth plugin)

Have you seen https://github.com/crisward/dokku-require ?

(This should maybe be a discussion?)

**Comment by tadamcz** [comment]
Heroku's `app.json` ([spec](https://devcenter.heroku.com/articles/app-json-schema#schema-reference)) looks like it supports many of these features. 

And Dokku has its own `app.json`, that behaves similarly to what I suggested, e.g. for the `formation` key, the docs say this:

> Using a formation key in an app.json file with any quantity specified disables the ability to use ps:scale for scaling.


To begin with, it would be good to get confirmation of which keys are and are not supported for Dokku's `app.json`. Perhaps @josegonzalez can help?

**Comment by josegonzalez** [comment]
We support the formations key - with additions - and scripts. We also additionally support a new `cron` key for our cron management.

I'm happy to support other features of the spec, but I don't really want to add too much more.

I personally don't think that allowing blanket access via a file is the correct method. As the initial comment mentioned, its sometimes difficult/impossible to keep that file in sync with actual app settings, and trying to do so - either via drift detection or some other means - is not something I am looking forward to. I also don't want to necessarily build something like this into Dokku itself - at least as part of the deploy process - without some serious consideration.

---

For anyone that is looking to control dokku via CI/CD, I strongly encourage looking into our [ansible modules](https://github.com/dokku/ansible-dokku). That will allow you to enforce all sorts of configuration before/after deployments, and is I think a bit safer, since you can reference secrets in CI that you wouldn't necessarily want to commit to your repository.

I spent a few hours just now building a small plugin that provides the ability to use ansible in the deploy process, and it is available [here](https://github.com/dokku/dokku-ansible). This has a few caveats (listed in the plugin) but should provide most of what folks are looking for in this ticket.

If you like this sort of thing, [please consider sponsoring the project](https://github.com/sponsors/dokku). It allows me to justify spending more time on stuff like this :)

**Comment by tadamcz** [comment]
> I'm happy to support other features of the spec, but I don't really want to add too much more.

Just to be clear, you're happy to support features of the [Heroku spec](https://devcenter.heroku.com/articles/app-json-schema) for `app.json` ?

It has the `website` key, which I think is currently not supported in Dokku. Being able to set the domain (and letsencrypt SSL) from a file, without using Ansible, would be great.

---

Regarding Ansible: Thanks for the plugin! I don't know much about Ansible. Is it correct that using a playbook like [this one](https://github.com/dokku/ansible-dokku#setting-up-a-small-vps-with-a-dokku-app) would not actually re-deploy the app on `git push dokku`? And you developed the plugin for that purpose? Thanks!

**Comment by josegonzalez** [comment]
I would be willing to support specific keys already in that spec, though I don't think I'll actively implement anything given time constraints, so if you want to sponsor something specific, please reach out.

The website key there is for a documentation link, not associated domains.

**Comment by josegonzalez** [comment]
Re: ansible, as long as you don't use the git libraries from that ansible role, you can manipulate most configuration for your nomad app just prior to it being built/deployed. The example in the readme for the plug-in shows a trivial change of a property for the app.
