### ISSUE TITLE
Show check output on fail

### ISSUE THREAD

**Issue by boxed** [dokku/dokku#5461]
### Description of feature

If a check fails, it would be nice to show more details. Just dumping the HTTP response, maybe with the status code would be nice.

**Comment by josegonzalez** [comment]
Should we log it in every attempt? I feel like that would be annoying.

Note that most other healthcheck frameworks simply check that an endpoint returns, and not for custom content (kubernetes/nomad).

**Comment by boxed** [comment]
Well no, not every attempt, just when it fails. When your deploy fails because a check failed, it would be nice with more information than just "failed". Like.. you want to know if it's connection refused, reset by peer, bad status code, content didn't match expected... I think those are all failure cases?

**Comment by josegonzalez** [comment]
We currently display curl errors but don't show when the content doesn't match.

My question re: content matching is for when we check a container multiple times. Should we show the output only for the last check, or each one?

I almost feel like dropping the content matching since no other system supports content matching, just 200 ok or similar.

**Comment by josegonzalez** [comment]
Related is #2760. I have a spec [here](https://github.com/dokku/dokku/issues/2760#issuecomment-490674563) for checks. I wonder if we should just implement that spec? I would probably completely drop the content checks.

Are content checks useful?

**Comment by boxed** [comment]
Content checks are very useful I think. I can very easily check that my build process didn't just spit out an empty file for compiled js for example.

**Comment by josegonzalez** [comment]
Shouldn't that be part of your build process though?

Lets say you moved to ECS, Kubernetes, or Nomad, where a content check isn't possible. How would that change your behavior?

**Comment by boxed** [comment]
I guess it could be. But then I'd still want a content check to see that static file serving is set up correctly. The way it works now I have one check that will validate both in one simple to understand check.

**Comment by josegonzalez** [comment]
What would happen if you moved schedulers from docker-local to anything else? All the other schedulers I'm aware of do not support content checks.

**Comment by boxed** [comment]
What does "scheduler" mean in this context? To me that means "program that runs stuff on a schedule" but clearly that's not what you're talking about.

**Comment by josegonzalez** [comment]
So by default, Dokku uses docker as it's scheduler (via the `scheduler-docker-local` plugin). It will orchestrate a bunch of containers based on your app's settings (scale settings, resources, etc.) and keep them alive as possible (even restarting the app in the background if you hit your restart limit).

You can also switch to another scheduler plugin, such as scheduler-kubernetes or scheduler-nomad. Dokku will interpret your app settings and then run a manifest against those external container scheduling systems that will run your app, and then the scheduler will keep your app alive as possible (potentially even running containers on different servers or autoscaling if you have the correct settings).

**Comment by boxed** [comment]
That... didn't really answer my question :P

Reading between the lines though, a "scheduler" in this context is more like what I would call a "runner", something that keeps stuff running. Like systemd?

Anyway, I don't really see the point of arguing what other systems don't do. Either a feature is useful or it's not. If other similar systems don't have a useful feature, that just means your system is better, not that you should delete that feature.

**Comment by josegonzalez** [comment]
Yeah its something like systemd in this case.

I guess what I'm getting at is that this is functionality that doesn't map to other systems - I'm also not aware of any hosted PaaS that does similar - and it seems to be causing issues. Other than testing that files are being served properly - which can be done by a check for `200 OK`, I think there are better ways of doing this sort of testing.

As an example, the alternative to this in Kubernetes or Nomad would be to use a script check. The script is run in the app's environment, so you might have a script that simulates checking that the http process returns the content you expect. Dokku would expose a script check instead of a content check, and that would be supported elsewhere.

---

So going back to the original issue, if you used a script check instead of our current content check, you could do something like:

```shell
#!/usr/bin/env bash

OUTPUT="$(curl http://localhost:$PORT/some-file.js)"
if ! grep jQuery <<< "$OUTPUT"; then
  echo "Expected: jQuery"
  echo "Output: $output"
  exit 1
fi
```

Add that to a file like `bin/web-healthcheck` and then add the following to your `app.json`:

```json
{
  "healthchecks": {
    "web": [
        {
          "type": "readiness",
          "command": ["bin/web-healthcheck"]
          "attempts": 5,
          "wait": 5
        }
    ]
  }
}
```

Dokku would then execute your healthcheck like normal, only swallowing the output for the first few attempts, showing the entire output on the last attempt (though we could set a property that makes it so we never swallow output).

---

I think what I'm getting at is... should I somehow try to fix this issue, or just refactor the entire checks plugin and ensure we handle the output swallowing as I mentioned?

**Comment by boxed** [comment]
Seems like we spent more time discussing this than it would have taken to just print the output on the failure at the end :P

I didn't know about healthchecks in app.json though. That does seem like a more flexible and general purpose system, but I still think the checks thing should print some debugging output. Either that or just deprecate and remove the CHECKS file entirely.

**Comment by josegonzalez** [comment]
Yeah I'm thinking of just removing CHECKS support completely in favor of the new `healthchecks` thing.

**Comment by josegonzalez** [comment]
Okay I'm going to close this. I feel like the new checks support will better support this sort of functionality, and I've already started work on that in #2760.
