### ISSUE TITLE
Podman installation method and scheduler support

### ISSUE THREAD

**Issue by almereyda** [dokku/dokku#5515]
### Description of feature

As I was unable to find a preliminary request neither in the issues nor discussions, why it might be useful to add the following:

If Dokku were able to run natively on Podman, it could also support Podman pods via Kube plays. These are the same as the YAML deployment manifests generated by the [Kubernetes Scheduler](https://dokku.com/docs/deployment/schedulers/kubernetes/).

Leaving a note here for reference at a later point in time, because the use case of pods is very similar to what Compose https://github.com/dokku/dokku/issues/5102 does, and might become even more relevant, when people choose to run the Dokku, Docker + Compose (e.g. in containers that have the socket mounted, and use `docker compose`, `docker-compose` or `podman-compose`?) CLIs against their (rootless) Podman socket.

Was it previously considered about how Dokku should relate to Podman, what are your current opinions?

<details>

<summary>References</summary>

Dokku installation methods do not mention Podman:

- https://dokku.com/docs/getting-started/advanced-installation/

There is also no Podman scheduler:

- https://dokku.com/docs/deployment/schedulers/scheduler-management/

Podman not mentioned in any title here:

- https://github.com/dokku/dokku/issues?q=is%3Aissue+podman
- https://github.com/dokku/dokku/discussions?discussions_q=podman

</details>

**Comment by josegonzalez** [comment]
In dokku, every reference to the `docker` binary should use the env var `DOCKER_BIN`. This defaults to `docker` in the root `dokku` binary, but could be overriden via `/etc/default/dokku` or `$DOKKU_ROOT/dokkurc` files. This change was introduced so folks could swap the `docker` binary with `podman`, which is _mostly_ equivalent.

The only outstanding thing is that I don't think you can update containers to either rename them or disable the restart policy with Podman. The former is a mostly cosmetic thing Dokku does (I don't think there is any actual real value to this tbh) and the latter is used by the local scheduler to ensure docker doesn't try to restart the container later (which may not be a podman issue). I believe both of these are relatively easy to fix/ignore, and are in our `scheduler-docker-local` scheduler plugin.

Outside of that, I don't have any plans to support podman instead of docker. I don't use podman, none of my servers use podman, and I don't have any desire to support something I don't use. If the change was relatively small to ensure podman support, I'd welcome it. If someone wanted to create a community podman scheduler plugin, that would be cool too.

Hope that gives context.

**Comment by almereyda** [comment]
Thank you for these details about your perspective on Podman support. This
will be very good to have here, in case someone comes up with a similar
desire to run through Podman like me.
