### ISSUE TITLE
 The repository 'https://ppa.launchpadcontent.net/nginx/stable/ubuntu jammy Release' does not have a Release file.

### ISSUE THREAD

**Issue by aplinxy9plin** [dokku/dokku#5660]
### Description of problem

Got  ```The repository 'https://ppa.launchpadcontent.net/nginx/stable/ubuntu jammy Release' does not have a Release file.``` error while try to install dokku by get started guide.
```
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

### Steps to reproduce

Try to run it on Ubuntu 22.04 machine
```
# using a branch results in installing from source
wget https://dokku.com/install/master/bootstrap.sh;
sudo DOKKU_BRANCH=master bash bootstrap.sh
```

got this:
```
user@machine:~$ sudo DOKKU_BRANCH=master bash bootstrap.sh
Preparing to install https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
E: The repository 'https://ppa.launchpadcontent.net/nginx/stable/ubuntu jammy Release' does not have a Release file.
```

### dokku report $APP_NAME

latest

**Comment by aplinxy9plin** [comment]
May be you can add support of check on nginx already exist on machine. Or can add custom repository for nginx.

**Comment by josegonzalez** [comment]
Thats not a ppa we install  in Dokku. The place its failing it as where we try to run `apt-get update`. I believe you might have a bad ppa installed on your server (maybe through some other automation or because of an OS upgrade?) that is getting picked up by the `apt-get update` call. Check your `/etc/apt/sources.list.d` directory for the apt repo.

Note: I just tried this on a fresh Ubuntu 22.04 install and was unable to replicate your issue.

**Comment by josegonzalez** [comment]
Not sure what "a docker build" is in this context, but again, we don't install that dependency. You can remove it from your system if you're seeing it come up during the install process.
