### ISSUE TITLE
Dokku apps database best practice

### ISSUE THREAD

**Issue by phaberest** [dokku/dokku#5741]
I have a few apps I'm switching from a VPS where they were all using the same mysql database to Dokku where they will have their own containers.

I'm just wondering, from a performances perspective would it be the best choice to create one database for each of my apps or would it be better to link all of them to the same service?

**Comment by josegonzalez** [comment]
That kinda depends. I like segregating them because it helps with scaling out later - I can just export that entire datastore and only have it impact one app. I typically don't collocate things when I have datastores on external services.

Some datastores behave better when they have a more holistic view of system resources, but I can't say which those are. Ultimately, I think it might make sense to speak with folks with deeper experience in your chosen datastore to see what pattern best fits your usage.

Hope that helps.
