### ISSUE TITLE
Support linking services to vector logging container

### ISSUE THREAD

**Issue by obrienmd** [dokku/dokku#5784]
## High Level Plan

- Add two new properties that take a comma-delimited list of networks
  - initial-network
  - post-create-network
- Refactor the vector container starting to use a docker compose template instead of a docker run command
- Add a plugin trigger allowing folks to specify a custom template for the vector container
- Add a `:show-config` subcommand that shows the templated docker compose config
- Template out the networks as appropriate
  - We should use `network_mode: bridge` if there is no network set
  - if only an initial-network is set, use the networks key as normal
  - if only a post-create-network is set, use [this hack](https://github.com/docker/compose/issues/3476#issuecomment-1120732371) to join the bridge network in addition to the other one
- Add a note to the migration docs about stopping the old vector container and starting it with the new config

### Description of feature

I'm attempting to ingest logs for all apps (via vector) into a clickhouse service hosted on dokku (using dokku-clickhouse). There doesn't appear to be a way to link a dokku service to the vector container (i.e. dokku clickhouse:link clickhouse_dokku_logs vector), as the vector container is not a "normal" dokku app.

I'm not sure what the best approach here would be - my instincts are:

1. Treating vector as a "normal" dokku app probably has significant side-effects / risks that don't immediately come to mind.
2. Building a custom way to link services to vector, such as "dokku clickhouse:link-vector" seems like a lot of work / maintenance.

There's always a reasonable chance I'm just missing something :) As I'm typing this, it seems that perhaps I could just expose clickhouse on localhost, though I need to play around with that to figure out if that's true, and (again, completely instincts) that doesn't feel as "right" to me.

**Comment by josegonzalez** [comment]
You could attach the service to a custom network and start vector manually, attaching it to your custom network after its created. We run vector via `docker run` (though should probably use compose) as shown here: https://github.com/dokku/dokku/blob/c6396ddfb834e2726a2460ec47bfad970c272628/plugins/logs/functions.go#L69

**Comment by obrienmd** [comment]
Makes sense - would that Attachment of the vector container to the custom network "stick", i.e. after host reboot, dokku upgrades, etc.?

**Comment by josegonzalez** [comment]
Yeah it should.

**Comment by josegonzalez** [comment]
I've finally come back to this, and it doesn't look like there is a way to have vector attach to both the default bridge network as well as a custom network. All the workarounds no longer work, and from searching this evening, it doesn't seem like the Docker folks care to actually fix this.

The underlying "issue" is that you can't set aliases for the default bridge network. I feel like compose should just not do that then vs saying we can't attach a container to a given network, but I'm not a docker developer so /shrug.

If anyone really wants this functionality, please ask the docker folks to implement it and then post here. That being said, since this isn't possible, I'm going to close the ticket.
