### ISSUE TITLE
GoAccess integration?

### ISSUE THREAD

**Issue by blopker** [dokku/dokku#5860]
### Description of feature

Hey! First thanks for Dokku, I've been running if for years and even helped with the initial letsencrypt plugin that eventually became official.

One thing that I've always wanted though is easy access to log analytics out of the box. I don't really want to ship all my logs to some service. Anyway, I started playing with GoAcess (https://goaccess.io) recently, and it seems to fit the bill. The command I'm currently using is `zcat -f /var/log/nginx/$1-access.log.* | goaccess --log-format=COMBINED` where $1 is the app_name. For an app that has been up for over a year, it takes a couple seconds to process everything, but it then gives me a bunch of good insights.

For instance, it became clear to me I needed a default vhost because bots were hammering my IP and taking up resources. 

Anyway, I noticed Dokku has Vector log integration, so I wanted to get the temperature on if GoAccess is something that would be integrated? Something like `dokku logs:analyze`.

Here's a screenshot of my app for reference:
<img width="966" alt="image" src="https://github.com/dokku/dokku/assets/757503/23bb08d1-39fc-4e4e-a327-ffe73e5a1944">

Thanks!

**Comment by blopker** [comment]
For completeness in case anyone wants to try this, the better command to use is `zcat -f /var/log/nginx/$1-access.* | goaccess /var/log/nginx/$1-access.log /var/log/nginx/$1-access.log.1 --log-format=COMBINED` because zcat doesn't pick up the first two ungzipped log rotation files.

**Comment by josegonzalez** [comment]
One problem with this is that not all installs will use nginx for their proxy - we also support Caddy, Haproxy, and Traefik. Those wont be able to benefit from this.

Additionally, IIRC we also dont support the ability to specify a custom access log format, which might cause issues with this - though we can probably live with that.

Maybe this could be a plugin trigger:

```shell
# takes two arguments
plugn trigger access-log-analyzer $APP $PROXY_TYPE
```

Each access plugin can implement it as necessary (the specifics would be different for each, especially as logs for the other three don't get written outside of the container iirc).

Is this something you'd be interested in working on? I can help you implement this over discord/slack. If not, I'm more likely to close this ticket since it's not super core functionality (though definitely seems nifty).

**Comment by blopker** [comment]
Thanks for the reply! I knew there were other proxies, but I didn't know they don't write out their logs to the host's disk. I see that this would get complicated quickly. Making each proxy write logs to the host would make this a bit easier. For the custom log format, Nginx logs work as is since they seem to follow the Common Log format, so no worries there. I don't know about the other proxies, however. Caddy at least seems to support CLF, but advises against it: https://caddyserver.com/docs/caddyfile/directives/log#format-modules

I have a solution that works for me currently (documented above). However, I'd be open to working on a Dokku command if others find it useful. I haven't seen any +1's on this yet, so the need is unclear. Totally feel free to close this for now. I'd revisit it if there seems to be interest.

Although maybe log analysis is a Dokku Pro feature? I wouldn't be mad :)

**Comment by josegonzalez** [comment]
There's a few changes coming to Dokku Pro, and maybe something along these lines :)

Going to close this for now, but if someone is interested in helping bring this to all the plugins, let me know!
