### ISSUE TITLE
zsh completions on server

### ISSUE THREAD

**Issue by voxelin** [dokku/dokku#6023]
### Description of feature

There are bash-completions for dokku, but some people might use `zsh` on their server instead. It would be helpful to add an option to generate completions for `zsh` as well.

**Comment by josegonzalez** [comment]
I don't run zsh on my server and don't know enough about completions to add support. If someone else wants to contribute this functionality, I would certainly take a pull request, but I otherwise don't have time to work on this.

If you'd like to sponsor this functionality, please see [this document](https://github.com/dokku/.github/blob/master/SPONSORING.md).
