### ISSUE TITLE
Heroku buildpack tryes to use irrelevant pgdg distribution

### ISSUE THREAD

**Issue by Studenich** [dokku/dokku#6344]
### Description of problem

When I try to deploy my app it fails on pg building stage because it can't find `bionic-pgdg` distribution as it was removed from http://apt.postgresql.org/pub/repos/apt 
> 2023-11-05: Ubuntu bionic (18.04) and kinetic (22.10) removed from apt.postgresql.org.

I tried to clear build cache with https://dokku.com/docs/advanced-usage/repository-management/#clearing-app-cache but it didn't help me.

Could you help me please with this issue?
Thank you

### dokku report $APP_NAME

-

### Additional information

-

### Output of failing deploy after running: dokku trace:off

```shell
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-apt.git
=====> Detected Framework: Apt
-----> Reusing cache
-----> Updating apt caches
       Ign:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
       Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
       Err:3 http://apt.postgresql.org/pub/repos/apt bionic-pgdg Release
       404  Not Found [IP: 147.75.85.69 80]
       Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
       Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
       Reading package lists...
remote: E: The repository 'http://apt.postgresql.org/pub/repos/apt bionic-pgdg Release' no longer has a Release file.
```

### Output of failing deploy after running: dokku trace:on

```shell
-
```

**Comment by josegonzalez** [comment]
First: We ask for folks to fill out the issue template not for my health, but so I can provide some actual support after understanding the environment in which the app is running in. In the future, please fill that out.

---


Second: Bionic is no longer supported by Ubuntu so I would 100% imagine this would start breaking in some apps. You're almost certainly going to need to update your builder image. Since you didn't provide any information as to what your runtime environment is, I can't help you figure out next steps there. Please consult our [upgrade docs](https://dokku.com/docs/getting-started/upgrading/) for more information on how to upgrade.

---

Third:

This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](https://dokku.com/docs/getting-started/where-to-get-help/#monitored-locations). 

Issues pertaining to buildpacks will be closed and/or locked.

**Comment by Studenich** [comment]
sorry for incomplete information and thank you for replaying 🙏

**Comment by Studenich** [comment]
@josegonzalez I've received dokku report, updated the issue, is there any chance that you could comment this please? Thank you

**Comment by josegonzalez** [comment]
You need to update dokku and herokuish. Thats the whole response. Nothing else I can do here.
