### ISSUE TITLE
Environment Variables *only for* runtime (dokku config:set <app> --runtime-only  KEY1=VALUE1)

### ISSUE THREAD

**Issue by gavindsouza** [dokku/dokku#6426]
### Description of feature

I've set an environment variable I need to start a process with via `dokku config:set`. Given that all envvars are made available during all phases, I see a lot of errors (which can be safely ignored but look scary to the "untrained" eye). Technically, the earliest this variable could be set after the buildpacks setup in the build phase when it's dependency is installed.

The only way that I know of being able to handle this is by adding a `Dockerfile` (The project in question uses `DOKKU_IMAGE`).

**Comment by gavindsouza** [comment]
I'm using https://github.com/dokku-community/dokku-apt to install `libjemalloc` and setting `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so`. So, `ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.` pops up thousands of times during the build phase until after the apt buildpack is executed. But also pops up once before every `dokku run <app> <cmd>`

**Comment by josegonzalez** [comment]
Could you use a custom buildpack to write an executable profile script in `/app/.profile` that contains the LD_PRELOAD value?

**Comment by josegonzalez** [comment]
Thinking about this more, you could create an `apt-env` file and set `export LD_PRELOAD=""` in there to blank out `LD_PRELOAD` during the running of the apt buildpack (which is probably your first one). That would let your build work as expected.

Closing as you probably still need libjemalloc for the following buildpacks in order to compile  against and we're 100% not going to support phasing in environment variables for specific buildpacks phases. If you don't need them for the following buildpacks, we're still not going to support runtime-only env vars as thats not Heroku works, and we're trying to emulate that as much as possible here.

**Comment by gavindsouza** [comment]
Thanks for sharing the project goal and providing workarounds. Your suggestion of setting LD_PRELOAD via the `.profile` script worked. I added something in `app.json`'s predeploy hook to set this if the jemalloc SO is found. Thanks again for your suggestions and your work on dokku!
