### ISSUE TITLE
k3s scheduler: ability to add extra labels

### ISSUE THREAD

**Issue by taraszka** [dokku/dokku#6625]
### Description of feature

We can add annotations already, but some tools at Kubernetes require labels instead. Let's add something like that:

```
scheduler-k3s:labels:set <app|--global> <property> (<value>) [--process-type PROCESS_TYPE] <--resource-type RESOURCE_TYPE>
```

The same way how annotations are currently added.

**Comment by taraszka** [comment]
I think I can code it/add this to the dokku

**Comment by josegonzalez** [comment]
Yeah that seems good, probably just copy-paste the code that added custom annotation support. That was done [here](https://github.com/dokku/dokku/pull/6562).

Probably also want to ensure the label keys/values are valid while you're at it, and that we don't use more than N labels (in addition to the ones dokku injects) so that we don't go over any limits.
