### ISSUE TITLE
Clarify ssh-keys commands to run when adding ssh keys in docker-based installation

### ISSUE THREAD

**Issue by cabaalexander** [dokku/dokku#6730]
### Description of problem

[Here](https://github.com/dokku/dokku/blob/master/docs/getting-started/install/docker.md?plain=1#L71) on the readme it says:
> ...run the appropriate ssh-keys commands.

And I wonder what are those `appropriate ssh-keys commands`, is there any link that can be appended here ? And is it accurate regarding running `dokku` within docker ?

### Steps to reproduce

Check docs

### dokku report $APP_NAME

Check docs

**Comment by josegonzalez** [comment]
The docs in the docs folder link out to the user management docs in the next line:

```
Please see the [user management documentation](https://github.com/dokku/dokku/blob/master/docs/deployment/user-management.md) for more information.
```

Since you're looking at the docs in source code mode, that link doesn't appear. If you go to the preview:

<img width="334" alt="Screenshot 2024-03-23 at 7 37 53 PM" src="https://github.com/dokku/dokku/assets/65675/5bf95aaf-c1db-4a48-8b94-26df08a1054a">

You'll see they are linked:

<img width="583" alt="Screenshot 2024-03-23 at 7 38 07 PM" src="https://github.com/dokku/dokku/assets/65675/3c27bec0-1b3f-4a10-a59b-b8ed67d1090b">

Our [docs site also has it linked properly](https://dokku.com/docs/getting-started/install/docker/#ssh-key-management).

That said, we can probably include a better example before linking users off to the correct page.
