### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by atduarte** [dokku/dokku#6856]
### Description of feature

New Ubuntu LTS was released yesterday, and it's not possible to install Dokku on it.

**Comment by josegonzalez** [comment]
Yep, that sounds right since it was released yesterday. The packages themselves should work if you manually install it, but they haven't been released for Ubuntu 24.04 just yet as I haven't had time to do any actual testing.

**Comment by josegonzalez** [comment]
In addition to Dokku itself, the following repositories will all need updates in order to publish their packages to Ubuntu 24.04:

- [docker-container-healthchecker](https://github.com/dokku/docker-container-healthchecker)
- [docker-image-labeler](https://github.com/dokku/docker-image-labeler)
- [dokku-event-listener](https://github.com/dokku/dokku-event-listener)
- [dokku-update](https://github.com/dokku/dokku-update)
- [gliderlabs-sigil](https://github.com/gliderlabs/sigil)
- [herokuish](https://github.com/gliderlabs/herokuish)
- [lambda-builder](https://github.com/dokku/lambda-builder)
- [netrc](https://github.com/dokku/netrc)
- [plugn](https://github.com/dokku/plugn)
- [procfile-util](https://github.com/dokku/procfile-util)
- [sshcommand](https://github.com/dokku/sshcommand)

If you (or @Reggino) would like to contribute those PRs (usually to the Makefile) to add that support, I can get those merged/released, and then work on the official support for Dokku.

**Comment by josegonzalez** [comment]
All that is left now is sigil and herokuish. I'm working on ensuring these all get release automation at the same time, so adding support in the future should be a simple PR + a manual workflow trigger!

**Comment by search5** [comment]
@josegonzalez When do you plan to release a version of dokku that supports ubuntu server 24.04?

**Comment by josegonzalez** [comment]
Probably whenever I get to figuring out how to automate the herokuish release, and whatever the bug is in the latest sigil that prevents the new package from working.

**Comment by HectorMalot** [comment]
I've gone ahead and made the PR for herokuish following your earlier change to add 22.04 a few years back: https://github.com/gliderlabs/herokuish/pull/1253 

Is this the issue with Sigil: https://github.com/gliderlabs/sigil/issues/115 ? I'm happy to have a look, but could use a bit of guidance on where to start looking.

**Comment by josegonzalez** [comment]
The sigil change was merged. I'll see about building herokuish for 24.04, and then we'll need this repo to get it too.

**Comment by polgiron** [comment]
hello, any update on this please? I'd like to set up Dokku on a new server and use the latest ubuntu 24.04. Thanks!

**Comment by HectorMalot** [comment]
> The sigil change was merged. I'll see about building herokuish for 24.04, and then we'll need this repo to get it too.

Great! anything I I can do to help?

**Comment by chgad** [comment]
> I've gone ahead and made the PR for herokuish following your earlier change to add 22.04 a few years back: [gliderlabs/herokuish#1253](https://github.com/gliderlabs/herokuish/pull/1253)
> 
> Is this the issue with Sigil: [gliderlabs/sigil#115](https://github.com/gliderlabs/sigil/issues/115) ? I'm happy to have a look, but could use a bit of guidance on where to start looking.

Checking the status of the mentioned issues, everything should be ready, isn't it?
Any planned release dates so far?

**Comment by eramoss** [comment]
Sorry for bringing this subject up again, but I think that all the dependencies of dokku is already supporting Ubuntu 24.04, has something that I can help to add the support for that release?

**Comment by dewey** [comment]
@eramoss https://github.com/gliderlabs/herokuish/pull/1295 was just merged yesterday, so I think a release should be closer now.

**Comment by jensenbox** [comment]
Excited to see this in action! I set up a new server just so I could try Dokku out but have had to wait for this to land.

**Comment by josegonzalez** [comment]
Yeah the last thing is the 0.35 release, which I hope to get out this week.

**Comment by tarbaig** [comment]
Can't wait for this to land, until than I'll have to use an old ubuntu version ;-(

**Comment by giovankes** [comment]
any ETA.

i'm sorry if i am asking repeated questions, i love what u guys do!

**Comment by strugee** [comment]
Adding keyword "noble" since I searched for `ubuntu noble` and this issue didn't turn up.

**Comment by josegonzalez** [comment]
Dokku version 0.35.0 - just released - moves everything (CI, our official images, adding a supported OS) to use Ubuntu 24.04 Noble by default.
