### ISSUE TITLE
Improve Monorepo support: Include source files outside of `build-dir` in the Build Step

### ISSUE THREAD

**Issue by WilsonCazarre** [dokku/dokku#6928]
### Description of feature

Hi, everyone 👋. First of all I want to thank the authors for such a great project, I've been using it for couple of weeks and it's being truly helpful.

However, I've been encontering a problem that it's honestly been really hard to deal with.

At my company, we're using Turborepo with PNPM workspaces to manage our projects. This setup is great because it allows us to easily share code between our projects.

The issue is that Dokku doesn't have the best support for it right now.

## The Problem
First let's assume a simple monorepo setup like this.
```
.
|-- apps/
|   |-- dashboard/
|   |   |-- # Next project
|   |   `-- package.json
|   `-- admin/
|       |-- # Next project
|       `-- package.json
|-- packages/
|   `-- ui/
|       |-- # Shared react components
|       `-- package.json
|-- package.json
`-- package-lock.yaml
```
The way that turborepo manage dependencies in a setup like this is by having a singular `package-lock.yaml` in the root of the project.
The current ways that dokku has of building a monorepo assumes that every project inside of it is completely isolated from one another.

So let's suppose that I've used this command to tell dokku to build my `dashboard` app:
```
dokku builder:set dashboard build-dir apps/dashboard
```

When dokku tries to build it, it will fail for 2 reasons:
- First the dependencies listed on dashboard that comes from the `packages` folder will not be available.
- There will be only the `package.json` listed on `apps/dashboard` and not the lock file on the root.

## Solution?

I'm actually not sure how this can be solved as of right now, but Vercel has a way of dealing with this problem by providing this handy option of "Include source files outside of the Root Directory in the Build Step", and I think that a similar solution can be implemented here, perhaps by a new flag:

```
dokku builder:set $APP include-source-files-outside-root true
```

![image](https://github.com/dokku/dokku/assets/46715026/931d8168-a065-45b0-a727-527bc2421f3d)

I would love to hear some thoughts on this matter, so please comment if you can think of a another (perhaps even simpler?) solution!

**Comment by josegonzalez** [comment]
The "issue" here is that apps are generally built by whatever builder you designate - heroku buildpacks, dockerfile, nixpacks, CNB, lambda, whatever. Each builder has - for better or worse - a "working directory" that we change to in order to build your app. That is what the `build-dir` is - its the build context.

Many monorepos are something like a python app and a node app in the same repo, not sharing configs. Those are easy to do a monorepo for - just change the `build-dir` context and you're done. Thats what I built the existing support for - cases where you might have a Procfile for one "app" and a different one for another (or whatever other files you can think of). Changing the `build-dir` also allows for more complex cases, but its basically changing the initial working directory for your app.

---

If we want to change the build-dir but keep all other files, the builder needs to be aware of that. In other words, if you're using Heroku Buildpacks via Herokuish, the buildpack you use would need to have a way for us to say "here is the codebase but change the directory for X steps" where `X` steps might be stuff like "only dependency installation" or "only whatever compiles the app". I don't think thats tenable since... we don't control buildpacks or anything like that. Thats also the case for every other builder (other than the lambda ones, but honestly I don't really think this should apply there since lambda functions tend to be small units of code that don't share dependencies within a given repo).

---

Taking a step back, if I wanted to start your app today, what would that process look like? I clone your repo and then.... how do I get everything compiled and all processes running? There's probably a world here where you can implement this with a Dockerfile + some extra env vars, but maybe there is a way to do this without that?

Note that the Dokku project strives to be a good copy of Heroku - it gives a great baseline experience - so if its possible there, it should be possible here.

**Comment by josegonzalez** [comment]
It's been a couple weeks without follow-up. Happy to improve things here, but its not clear that there is a good way forward without more feedback.

Feel free to comment and we'll try and come up with something that works :)
