### ISSUE TITLE
Support for Whats Up Docker

### ISSUE THREAD

**Issue by codingmatty** [dokku/dokku#7024]
### Description of feature

I have been using Dokku for a long time and realized I need to keep up with updates on Docker images, but it does not seem compatible with the way that Dokku creates it's own image that extends the provided Docker image. It does not seem like there is a way to deploy the docker image directly.

Has anyone ever tried to do something like this or have a different solution to monitor updates?

**Comment by josegonzalez** [comment]
We support image-based deployment via the `git:from-image` command as documented [here](https://dokku.com/docs/deployment/methods/image/).

Looking at the docs for WUP, doesn't seem like there is a way to trigger a command on the cli, but that should be what we do. I think maybe a service that accepts that HTTP payload and then executes the command might be the best bet.

At this time, there is no open-source persistent daemon that is part of Dokku which would expose execution of the workflow you want, so you'd need to build that on your own.

**Comment by codingmatty** [comment]
The way WUP works is by tying into the Docker socket, which lists the containers, but the way Dokku shows up is as a Dokku image.

Example:
```
dokku/authelia:latest           "/app/entrypoint.sh"     22 minutes ago   Up 22 minutes (healthy)   9091/tcp                                      authelia.web.1
```

WUP then tries to look through registries for `dokku/authelia:latest` which fails... 

---

I am fine with setting up a custom cron job to look at the current version and latest version of the underlying docker image, but I'm having trouble figuring out what the correct command would be to see what current version is being used by the Dokku container...

**Comment by josegonzalez** [comment]
I believe you can check the output of the following command to get image sources for docker image-based deploys:

```shell
dokku apps:report $APP --app-deploy-source-metadata
```

**Comment by codingmatty** [comment]
That seems close, but it only works if I set a specific version. If I use latest then it just shows latest. I need the image SHA to compare against.

**Comment by josegonzalez** [comment]
To be honest I can't help you with your specific ask:

- We retag the image on purpose as thats how we know we can use the image for deployment. There isn't a way around that.
- We don't run an API, so you'd need to write something on your own (a cron task is fine I suppose)
- I think the general consensus is to _not_ use the latest tag to denote what you are deploying. I would always pin to a specific version, and if you cannot for whatever reason, specify the image digest instead of the `latest` tag. Whatever you told us to deploy is what we'll pull/deploy - we won't resolve the tag to a sha because there isn't any docker api to do that (short of pulling an image and doing a comparison).

For cases where you are deploying an image, I would recommend you have some CI mechanism that deploys the image instead. At least on Github, you can create a placeholder Dockerfile with a reference to the upstream image, and then setup dependabot to update that image whenever upstream changes. On merge to main/master, you can use our [official action](https://github.com/marketplace/actions/dokku) to deploy the image to your app. This would avoid an extra process on the server and ensure you're always aware of exactly what is being deployed to your servers.
